### ISSUE TITLE
Implement open & close folder glyphs (icons)

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/vim-devicons#104]
Work in progress:

![screencast_17-aug-2015-07 59 50](https://cloud.githubusercontent.com/assets/8083459/9319284/bd7b5fa8-451a-11e5-8f62-c33355ded82f.gif)

:smiling_imp:

**Comment by lerrua** [comment]
Nice. :+1:

**Comment by ryanoasis** [comment]
Fin (not perfect but for now)
