### ISSUE TITLE
blurry icons/statusline misalignment using SauceCodePro

### ISSUE THREAD

**Issue by kcmannem** [ryanoasis/vim-devicons#107]
these issues do not appear when using the normal source code pro unmatched font. Here is an image of the blurry icons in NERDTree.
![screen shot 2015-08-24 at 7 08 39 pm](https://cloud.githubusercontent.com/assets/9054726/9454887/a28833fa-4a93-11e5-96bf-ca75467a6068.png)

here is a picture of the misalignment
![screen shot 2015-08-24 at 7 09 58 pm](https://cloud.githubusercontent.com/assets/9054726/9454901/c6543b1c-4a93-11e5-82de-e15403ffea84.png)
you can see the gaps between the arrows on the left side.

**Comment by ryanoasis** [comment]
:worried: I will try to look into it. Actually I think I have seen it before but I probably ignored it :blush: 

Thanks!

**Comment by her** [comment]
Which status line are you using?

**Comment by ryanoasis** [comment]
This should be long since fixed since [Nerd Fonts v1.0.0](https://github.com/ryanoasis/nerd-fonts/releases/tag/v1.0.0)

@kcmannem please don't be afraid to re-open if you still have the issue or need help :smile:
