### ISSUE TITLE
No devicons with pached font in terminal

### ISSUE THREAD

**Issue by aborilov** [ryanoasis/vim-devicons#108]
Hi!
I've patched this font https://github.com/Gonzih/inconsolata-lgc-for-powerline with nerd-fonts font-patcher.
In gvim all looks great, but in terminal(urxvt) font look fine, but no devicons in vim.
![screenshot](https://cloud.githubusercontent.com/assets/2526284/9514155/3843aca4-4ca0-11e5-87e1-b90af1f9b811.png)
as you can see from screenshot, urxvt found font, but without devicons.

**Comment by ryanoasis** [comment]
can you try running the font patcher with the `-s` flag ? 

That should force the glyphs to be single width (mono) which is required for terms like urxvt

**Comment by ryanoasis** [comment]
@aborilov were you ever able to figure it out?

**Comment by aborilov** [comment]
Sorry, will try this week.

ср, 7 окт. 2015, 18:44, Ryan L McIntyre <notifications@github.com>:

**Comment by aborilov** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/2526284/10359288/cb163d06-6d9f-11e5-9912-2250cf3cf159.png)

It's better now, but not all icons shows properly.

**Comment by ryanoasis** [comment]
@aborilov can you try updating whatever font you are using to the latest version?

Or if you could send the font to me I can verify if the glyph is missing or not

**Comment by aborilov** [comment]
https://github.com/aborilov/dotfiles/blob/master/.fonts/Inconsolata%20LGC%20for%20Powerline%20Plus%20Nerd%20File%20Types%20Mono.ttf
Here's pathed font.
and here
https://github.com/Gonzih/inconsolata-lgc-for-powerline/blob/master/Inconsolata%20LGC%20for%20Powerline.ttf
original font

**Comment by ryanoasis** [comment]
Sorry for the delayed response, I will try to check this out

**Comment by ryanoasis** [comment]
@aborilov I am really sorry for the late reply. I did download your patched font. The glyphs look correct at a glance.

One this I did notice is that the version is a bit old (makes sense considering the lateness of my reply)

![selection_20_02_16_21 58 37_970x981_001](https://cloud.githubusercontent.com/assets/8083459/13200593/89c8d6e0-d81d-11e5-8e7e-45d8cfc1f4c1.png)


A few ideas:

* try to repatch the font with the latest version of nerd fonts

* try to see what character is being rendered for `.sh` extension (highlight the glyph and type `ga` in normal mode should show what it actually is)

![selection_20_02_16_22 00 08_334x241_001](https://cloud.githubusercontent.com/assets/8083459/13200592/8511b16c-d81d-11e5-89dc-1fab9db6ff31.png)

**Comment by ryanoasis** [comment]
@aborilov Just pinging to see if you still have this issue (assuming you are still using Nerd Fonts or vim-devicons :blush: )

I'll give you some more time (especially since I replied so late initially) but then I will close this out.
Thanks

**Comment by aborilov** [comment]
Hi! Thanks for answer, for now all works great, of course still using Nerd Fonts with vim-devicons.

**Comment by ryanoasis** [comment]
Thanks!

**Comment by vadimshvetsov** [comment]
@ryanoasis I have an original OS X font - Monaco, patched with fontforge and nerd script - font-patcher. Here it is. Why I can't see devicons in NerdTree? With mononoki nerd font I can see all devicons

**Comment by kutsan** [comment]
@vadimshvetsov Maybe related https://github.com/ryanoasis/nerd-fonts/issues/210?

**Comment by vadimshvetsov** [comment]
@kutsan Wow, thanks, totally
