### ISSUE TITLE
Error with 0.6.0 Update

### ISSUE THREAD

**Issue by mhartington** [ryanoasis/vim-devicons#109]
Not sure whats up, but got this error when I updated. 

```
Error detected while processing /Users/mhartington/.nvim/bundle/vim-devicons/nerdtree_plugin/webdevicons.vim:
line  118:
E121: Undefined variable: g:DevIconsEnableFoldersOpenClose
E15: Invalid expression: g:DevIconsEnableFoldersOpenClose
Error detected while processing /Users/mhartington/.nvim/bundle/vim-devicons/plugin/webdevicons.vim:
line  114:
E121: Undefined variable: g:DevIconsEnableFoldersOpenClose
E15: Invalid expression: g:DevIconsEnableFoldersOpenClose
Press ENTER or type command to continue
```

**Comment by ryanoasis** [comment]
eeek ouch. Thanks. I think I see the issue

**Comment by ryanoasis** [comment]
@mhartington Can you see if it works for you now?

**Comment by mhartington** [comment]
Hmm, still getting something

``
Error detected while processing /Users/mhartington/.nvim/bundle/vim-devicons/nerdtree_plugin/webdevicons.vim:
line  118:
E121: Undefined variable: g:DevIconsEnableFoldersOpenClose
E15: Invalid expression: g:DevIconsEnableFoldersOpenClose
Press ENTER or type command to continue
```

**Comment by ryanoasis** [comment]
crap yep

**Comment by ryanoasis** [comment]
I have it fixed on my end. How about you?

**Comment by mhartington** [comment]
That one seems to have done it :+1: 
Thanks!

**Comment by ryanoasis** [comment]
Awesome :tada: :cold_sweat: 

No thank you! I was lucky to get your report soon after pushing! 

Probably time to think about adding some basic build tests. I did not catch the error because of my `vimrc` settings.

**Comment by mhartington** [comment]
https://github.com/kana/vim-vspec ?

**Comment by ryanoasis** [comment]
Yeah something like that. I have seen that one and a few nice other ones. 

BTW for 'ts' icons you'll need a latest font from https://github.com/ryanoasis/nerd-fonts :smile:

**Comment by mhartington** [comment]
Already downloaded :grin: 
Holy Icons! Thats a big update to SourceCode Pro.
Thanks a lot

**Comment by ryanoasis** [comment]
:wink: Yeah, however there are still some basic problems with the patched fonts (most of the open tickets are related to the fonts).

I am probably going to simply the directory structure and make it easier to download the font that has everything.. because right now its very hard to see and know which one you want IMHO

**Comment by mhartington** [comment]
Happy to help out how ever I can.

**Comment by ryanoasis** [comment]
Thanks :+1:
