### ISSUE TITLE
Dots after icons in NERDTree, only in GVim

### ISSUE THREAD

**Issue by KabbAmine** [ryanoasis/vim-devicons#110]
First of all, thanks for your awesome plugin.

With GVim, I had the same problem as the one in #84 ...

![devicon1](https://cloud.githubusercontent.com/assets/5658084/9557611/1134bee0-4de6-11e5-88b0-343ca617edc4.png)

... and unsetting `list` in nerdtree's buffer solved it.

```
autocmd FileType nerdtree setlocal nolist
```
![devicon2](https://cloud.githubusercontent.com/assets/5658084/9557633/33e7246e-4de6-11e5-8c3e-e65b762f12bd.png)

It will be good then to add this workaround in the README.

**Comment by ryanoasis** [comment]
Thanks for this! I will at least add to readme as you suggested :smile:

**Comment by KabbAmine** [comment]
Good :smiley: You'll close the issue when the README will be updated then.

**Comment by ryanoasis** [comment]
Yep :+1:

**Comment by vohtaski** [comment]
I have exactly the same issue. Everything is fine in terminal
but is cut in MacVim (7.4).

I tried the proposed solution to add `autocmd FileType nerdtree setlocal nolist` to my `.vimrc`,
but with no success.

Are there some additional settings that I can try?
BTW, the icons are cut not only in NERDTree but also in vim-airline.

![screen shot 2016-04-14 at 22 59 36 pm](https://cloud.githubusercontent.com/assets/158421/14543494/b1f5760e-0294-11e6-9aec-c0923942c116.png)

**Comment by vohtaski** [comment]
actually I just noticed that there are dots.

In my case, there is not dots. Just cut icon, so maybe it's another issue

**Comment by ryanoasis** [comment]
Uh oh :cry: 

You can try tweaking this fix in the code to see if it gives any more clues: https://github.com/ryanoasis/vim-devicons/blob/master/plugin/webdevicons.vim#L557-L559

Other than that there are other settings but I don't see they would help: `g:WebDevIconsUnicodeGlyphDoubleWidth`, `WebDevIconsNerdTreeAfterGlyphPadding`

**Comment by vohtaski** [comment]
I checked your code and it looks the problem might be with fonts or MacVim, because even in the code it's cut:
![screen shot 2016-04-14 at 23 46 47 pm](https://cloud.githubusercontent.com/assets/158421/14544872/810f8abe-029b-11e6-8d03-23bfaad572fe.png)

**Comment by ryanoasis** [comment]
Hmm yes actually that is how I usually see it too because they are double width characters so they get a little messed up when viewed without any applied "fix" to their display.

Can you try to see if this helps things: `:set ambiwidth=double`

**Comment by vohtaski** [comment]
Thanks a lot @ryanoasis !
`:set ambiwidth=double` did the trick. It works now!

**Comment by ryanoasis** [comment]
@vohtaski Cool I am glad that actually worked for you, it also worked for me but caused some issues regarding powerline symbols using Airline:

![selection_15_04_16_11 48 43_663x156_001](https://cloud.githubusercontent.com/assets/8083459/14567040/2b551b4c-0300-11e6-828a-368fb95d7668.png)

**Comment by vohtaski** [comment]
@ryanoasis Yep, I had the same issue, the bigger problem is that it also broke the indentLine plugin :(

**Comment by ryanoasis** [comment]
@vohtaski could you paste the output of `:version` for macvim?

I'm particular I want see which patches you have.
Thanks

**Comment by vohtaski** [comment]
here it is:
```
:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May  4 2016 17:30:35)
MacOS X (unix) version
Included patches: 1-1816
Compiled by _spotlight@Traviss-Mac-369.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +dialog_con_gui  +insert_expand   +mouse_sgr       +rightleft       +transparency
+arabic          +diff            +job             -mouse_sysmouse  +ruby/dyn        +user_commands
+autocmd         +digraphs        +jumplist        +mouse_urxvt     +scrollbind      +vertsplit
+balloon_eval    +dnd             +keymap          +mouse_xterm     +signs           +virtualedit
+browse          -ebcdic          +langmap         +multi_byte      +smartindent     +visual
++builtin_terms  +emacs_tags      +libcall         +multi_lang      +startuptime     +visualextra
+byte_offset     +eval            +linebreak       -mzscheme        +statusline      +viminfo
+channel         +ex_extra        +lispindent      +netbeans_intg   -sun_workshop    +vreplace
+cindent         +extra_search    +listcmds        +odbeditor       +syntax          +wildignore
+clientserver    +farsi           +localmap        +packages        +tag_binary      +wildmenu
+clipboard       +file_in_path    +lua/dyn         +path_extra      +tag_old_static  +windows
+cmdline_compl   +find_in_path    +menu            +perl/dyn        -tag_any_white   +writebackup
+cmdline_hist    +float           +mksession       +persistent_undo -tcl             -X11
+cmdline_info    +folding         +modify_fname    +postscript      +termguicolors   -xfontset
+comments        -footer          +mouse           +printer         +terminfo        +xim
+conceal         +fork()          +mouseshape      +profile         +termresponse    -xsmp
+cryptv          +fullscreen      +mouse_dec       +python/dyn      +textobjects     -xterm_clipboard
+cscope          -gettext         -mouse_gpm       +python3/dyn     +timers          -xterm_save
+cursorbind      -hangul_input    -mouse_jsbterm   +quickfix        +title           -xpm
+cursorshape     +iconv           +mouse_netterm   +reltime         +toolbar
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_
X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib  -L/usr/local/lib -o Vim -framework Cocoa -framewor
k Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.16/darwin
-thread-multi-2level/CORE
```

**Comment by ryanoasis** [comment]
@vohtaski Thanks
