### ISSUE TITLE
Plus sign after the icon on nerdtree

### ISSUE THREAD

**Issue by kassio** [ryanoasis/vim-devicons#111]
I'm getting this:
![python 2015-08-28 20-53-30](https://cloud.githubusercontent.com/assets/120483/9559252/d9ed8706-4dc6-11e5-8442-68ba93716dd5.png)

I'm using iterm2:
![preferences 2015-08-28 20-52-19](https://cloud.githubusercontent.com/assets/120483/9559243/b15402ac-4dc6-11e5-95c0-7420baccd927.png)

Also, I'm using neovim.

Thank you.

**Comment by ryanoasis** [comment]
Can you see if #110 is any help to you?

**Comment by kassio** [comment]
You're right! It worked! Thank you a lot!

**Comment by ryanoasis** [comment]
No problem. Glad that worked for you. :smile: 

I probably need to add to the readme more details as suggested by #110
