### ISSUE TITLE
Some folders in NERDTree use file glyphs instead of directory ones

### ISSUE THREAD

**Issue by KabbAmine** [ryanoasis/vim-devicons#112]
In NERDTree, a directory named for example `folder.ext` will be considered by devicons as a file: `file.ext`, so the plugin will use a filetype glyph instead of directory glyph.

![dev1](https://cloud.githubusercontent.com/assets/5658084/9561330/5868323e-4e49-11e5-8090-532bb549b5c9.png)

Having `let g:DevIconsEnableFoldersOpenClose = 1` works as expected when the directory is opened.

![dev2](https://cloud.githubusercontent.com/assets/5658084/9561338/890e73b2-4e49-11e5-8991-dc28520601ae.png)

I didn't take a look to the code but I assume that you're using regex to get if its a file or a directory. If you can use the highlighting group names directly in NERDTree, it will be easier to get the type ('NERDtreeDir' or 'NERDtreeFile').

**Comment by ryanoasis** [comment]
This is a good point. I had set it up so directories could be matched on as well however most of the time this is probably not the desired result (as your example demonstrates).

So I think by default directories should not try to find matches but I would allow an option to do that.

The proper directory detection is present it's just that I currently allow them to be matched as well

Thanks :smile:

**Comment by KabbAmine** [comment]
> So I think by default directories should not try to find matches but I would allow an option to do that.

I agree :+1:
