### ISSUE TITLE
Folders icon doens't work with other fonts

### ISSUE THREAD

**Issue by lerrua** [ryanoasis/vim-devicons#113]
Hi there.

I'm using Fira Mono Medium font that download at https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/FiraMono (an amazing font) and works fine with dev-icons but dont looks good using folders config like this

```
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:DevIconsEnableFoldersOpenClose = 1
```
![screen shot 2015-08-31 at 11 52 05 pm](https://cloud.githubusercontent.com/assets/154603/9595143/6aa7b52a-503b-11e5-975f-2a8fc0580f09.png)

![screen shot 2015-08-31 at 11 55 57 pm](https://cloud.githubusercontent.com/assets/154603/9595182/ee6e7c5e-503b-11e5-8b1a-58b658696e74.png)

**Comment by ryanoasis** [comment]
That's odd.

Can you see what char code it gives when you highlight the folder with cursor and enter `ga` ?

I just tried:
* https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/FiraMono/Fira%20Mono%20Bold%20for%20Powerline%20Plus%20Nerd%20File%20Types.otf

And they seemed to have the glyphs.

This is what I am seeing in my terminal vim when I set those 2 options and Fira font:

![selection_01_09_15_10 53 04_357x462_001](https://cloud.githubusercontent.com/assets/8083459/9607527/aadc99ec-5097-11e5-83f9-b5a08688e50c.png)


--

Another issue this brings up is that the patched versions should also be named "Fura" _NOT_ "Fira" to avoid possible licensing issues. I will need to fix this when I can re-generate.

**Comment by ryanoasis** [comment]
@lerrua were you able to solve this?

**Comment by ryanoasis** [comment]
@lerrua I am going to close this. I was not able to replicate this and there was no follow up.

Feel free to re-open though if you still have the issue :smile:
