### ISSUE TITLE
icons not showing

### ISSUE THREAD

**Issue by tnguyen14** [ryanoasis/vim-devicons#114]
I've followed the instruction of downloading the patched font and set my iTerm to use that font (Fura Mono Bold for Powerline Plus Nerd File Types Mono). However, the file icons are not showing. Instead, I see these:

<img width="227" alt="screen shot 2015-09-29 at 12 13 44 am" src="https://cloud.githubusercontent.com/assets/1652595/10155170/2fed522c-663f-11e5-806f-7bce4383e72c.png">

I am not sure what I could be doing wrong here. Could someone help?

**Comment by ryanoasis** [comment]
See if [this](https://github.com/ryanoasis/nerd-fonts/issues/13) fixes your problem (iterm ascii settings)

Related: #85 #90

**Comment by tnguyen14** [comment]
ryanoasis/nerd-fonts#13 seems to have fixed it (setting the Non-ASCII font in iTerm).

However, the width of the character still seems a little distorted vertically. Any suggestion on how to fix that?

<img width="298" alt="screen shot 2015-09-29 at 10 09 20 am" src="https://cloud.githubusercontent.com/assets/1652595/10166522/64a1707c-6692-11e5-89ab-b63f11b47c61.png">

**Comment by tnguyen14** [comment]
@ryanoasis pinging you again - any idea/ suggestion on why the font seems so compressed on my iTerm?

**Comment by ryanoasis** [comment]
Which font are using (the exact font name)?

Some of the fonts are completely monospaced and some are Mono but have double width glyphs

**Comment by tnguyen14** [comment]
I use `Fura Mono Regular for Powerline Plus Nerd File Types Mono`. Should I use something different?

**Comment by ryanoasis** [comment]
Can you try `Fura Mono Regular for Powerline Plus Nerd File Types`

**Comment by tnguyen14** [comment]
That seems to have fixed it. Thanks :)

I'll close this issue for now. I think that the README could be update to include that little nugget of info about Non-ASCII font for iTerm on OS X. More than happy to create a PR for it if you'd like.

**Comment by ryanoasis** [comment]
Great.

Yeah I have been meaning to add something.

If you want to submit a PR that'd be cool  (I just may tweak it a bit - mostly related to position in the readme. Screenshots of the iTerm settings would be nice also.

**Comment by sureshsaragadam** [comment]
Install nerd-fonts

https://github.com/ryanoasis/nerd-fonts
`
git clone https://github.com/ryanoasis/nerd-fonts.git
cd nerd-fonts
./install.sh
reboot
`
