### ISSUE TITLE
"E16: Invalid range" with CtrlPMRUFiles: does not clean up file name

### ISSUE THREAD

**Issue by blueyed** [ryanoasis/vim-devicons#115]
I sometimes see the following error when using `:CtrlPMRUFiles`:

    Error detected while processing function <SNR>277_AcceptSelection..webdevicons#ctrlPOpenFunc:
    line    5:
    E16: Invalid range

The line in question is https://github.com/ryanoasis/vim-devicons/blob/master/plugin/webdevicons.vim#L549:

> let line = s:strip(substitute(line, "[-]", "", ""))

That might be an issue with Neovim, I've not investigated yet.

But the result is that the error shows up and then a (empty/new) file is opened with the leading icon, although I've selected an existing one from the list.

`E16` refers to `cmdline-ranges` - so it might not be about the range of characters for `substitute`, but then `E16` might refer to both of them?!

**Comment by ryanoasis** [comment]
@blueyed Sorry that I have been unable to look into this yet. Didn't see anything in `:messages` after executing. Maybe you are right and that is specific to Neovim.

**Comment by blueyed** [comment]
@ryanoasis 
It does not happen reproducible / always for me, but only sometimes - I have not found a pattern/way yet to trigger it.

I think there might be a better/simpler way to handle and clean up the entries?

**Comment by mudox** [comment]
I run into the same problem both in my Neovim & Vim running in iTerm2.
```vim
let t = "\ue0a0 and \ue0b0" | echo t | echo substitute(t, "[-]", "", "")
```
I got the panic:
E16: Invalid range

**Comment by mudox** [comment]
The cause of problem is the adoption of the old regex engine by `set regexengine=1`, I set it to 1 in my vimrc.

**Comment by ryanoasis** [comment]
Update:

I was not able to replicate the issue on `CtrlPMRUFiles`

but I was able to replicate it with @mudox given example (on vim and gvim):
`let t = "\ue0a0 and \ue0b0" | echo t | echo substitute(t, "[-]", "", "")`
when
`set regexpengine=1`

Changing it to something like this might end up working (although seems eo be removing extra character):
`let t = "\ue0a0 and \ue0b0" | echo t | echo substitute(t, "[\%xe000-\x%f8ff]", "", "")`

**Comment by mudox** [comment]
> Changing it to something like this might end up working (although seems eo be removing extra character):
let t = "\ue0a0 and \ue0b0" | echo t | echo substitute(t, "[\%xe000-\%xf8ff]", "", "")

I looked into the doc `:help /collection`, in the collection syntax, the syntax `\%xhhhh` is considered as literal characters separately, not an atom denoting a unicode character, so the code above just removed the first character 'a' found which falls between range [0-\\].

The `:help /collection` also said,
>  \d123	   decimal number of character
>  \o40	   octal number of character up to 0377
>  \x20	   hexadecimal number of character up to 0xff
>  \u20AC   hex. number of multibyte character up to 0xffff
>  \U1234	   hex. number of multibyte character up to 0xffffffff

However, in my test, only `regexpengine` be set to 0 or 2 can the syntax `[\ue000-\uf8ff]` work without panic.

```vim
set regexpengine=0 | let t = "\ue0a0 and \ue0b0" | echo t | echo substitute(t, "[\ue000-\uf8ff]", "", "g")
set regexpengine=2 | let t = "\ue0a0 and \ue0b0" | echo t | echo substitute(t, "[\ue000-\uf8ff]", "", "g")
```
And the syntax mentioned in `:help NFA` does not work in my test

**Comment by ryanoasis** [comment]
Great info thanks! :+1: I will try to look more into this too when I can

**Comment by ryanoasis** [comment]
The NFA seems to be working for me:

per `:h NFA`:
```vim
Vim will automatically select the right engine for you.  However, if you run
into a problem or want to specifically select one engine or the other, you can
prepend one of the following to the pattern:

	\%#=0	Force automatic selection.  Only has an effect when
	        'regexpengine' has been set to a non-zero value.
	\%#=1	Force using the old engine.
	\%#=2	Force using the NFA engine.
```

Testing:

```vim
set regexpengine=0 | let t = "\ue0a0 and \ue0b0" | echo t | echo substitute(t, '\%#=2[\ue000-\uf8ff]', "", "g")
set regexpengine=1 | let t = "\ue0a0 and \ue0b0" | echo t | echo substitute(t, '\%#=2[\ue000-\uf8ff]', "", "g")
set regexpengine=2 | let t = "\ue0a0 and \ue0b0" | echo t | echo substitute(t, '\%#=2[\ue000-\uf8ff]', "", "g")
```

This way the plugin doesn't have to mess with setting regexpengine and risk messing up other code or plugins.

hmm... actually I just tested this in neovim on Fedora and the one with setting `regexpengine=1` does *not* work with the prepended pattern :cry:

**Comment by ryanoasis** [comment]
@blueyed 
> I think there might be a better/simpler way to handle and clean up the entries?

This got me thinking and I think I may have a possibly better way, see below

--

@blueyed , @mudox 

Here is a possible solution I may go with:

https://gist.github.com/ryanoasis/53a8d4c96f7acddaf93d

And here is a profile comparing the 3 (basically no performance difference):

https://gist.github.com/ryanoasis/4ac41f1f69e80aeac889

**Comment by ryanoasis** [comment]
Please try out [0.8.1](https://github.com/ryanoasis/vim-devicons/tree/0.8.1) branch. If no feedback or no issues reported I will merge into master Monday. Thanks :bow:
