### ISSUE TITLE
Squished icons using mintty (windows)

### ISSUE THREAD

**Issue by cj** [ryanoasis/vim-devicons#116]
The icons seem to be squished when using `mintty` (http://babun.github.io)

![](http://i.imgur.com/8iSwgzi.png)

**Comment by ryanoasis** [comment]
Which font are you using? There are single width symbol and double width glyph versions of each patched font variant

**Comment by ryanoasis** [comment]
seems to relate to #78

**Comment by cj** [comment]
@ryanoasis I think it is related.  I replied in #78

**Comment by cj** [comment]
@ryanoasis hope you had a good weekend.  I sent you a message on gitter.

**Comment by ryanoasis** [comment]
@cj I finally got around to trying the fonts you sent me.

Looked okay on Linux and also tried Windows but using the font in `gvim` it would crash :worried: 

Then tried `Babun (mintty)` with my own patching of PragmataPro. I could not get the "true" mono patched version of `PragmataPro` to show up in `Options > Text > Font`. Were you able to get the font to show up (it sounds like you were)?

**Comment by cj** [comment]
@ryanoasis Thank you for taking a look.  It doesn't actually show up in the menu, you have to manually set the font in the config.  Feel free to message me on gitter and I can screenshare with you.

**Comment by ryanoasis** [comment]
Ah okay, can you tell me how to set it in the config?

I can maybe do a screenshare... just not sure when will be the best time.

**Comment by cj** [comment]
@ryanoasis sorry, just saw this.  I'm free whenever.  Just message me on gitter.

`.babun/cygwin/home/{home folder}/.minttyrc`

then just add: `Font=PragmataPro Mono Plus Nerd File Types`

**Comment by cj** [comment]
@ryanoasis have you had a chance to look into this further?  I just tried a fresh install and the latest font patcher.  I still get the same issue

**Comment by ryanoasis** [comment]
@cj No sorry I have not had a real chance yet. 

I think I did quickly try what config settings you gave me but I can't exactly remember what the result was.

**Comment by cj** [comment]
no worries.  let me know when you're around and free.  I'll keep my gitter.im open.  I'd love to get to the bottom of this :)

**Comment by ryanoasis** [comment]
This should be fixed lately. Related to #78 (which has now been closed) :smile: 

@cj Let me know if this is still an issue
