### ISSUE TITLE
press F5 in Cltrp MRU mode got a panic

### ISSUE THREAD

**Issue by mudox** [ryanoasis/vim-devicons#117]
When I pressed F5 to get rid of no more existed files, I got
![screen shot 2015-10-25 at 9 19 37 pm](https://cloud.githubusercontent.com/assets/2283394/10715798/46b979b6-7b5e-11e5-8912-ce26f27c168f.png)
After I added `let g:webdevicons_enable_ctrlp = 0`, the panic gone

**Comment by ryanoasis** [comment]
@mudox Thanks, replicated it

**Comment by ryanoasis** [comment]
Ouch this one hurts, looks like I have to copy a few more methods to get the ctrlp override working :worried:

**Comment by ryanoasis** [comment]
Actually I am going to discontinue the support for the kien ctrlp repo  (https://github.com/kien/ctrlp.vim) and only support the active ctrlp fork (https://github.com/ctrlpvim/ctrlp.vim).

This will be easier going forward

**Comment by mudox** [comment]
I've switched to [ctrlpvim/ctrlp.vim](https://github.com/ctrlpvim/ctrlp.vim) for a while, nice fork.

**Comment by ryanoasis** [comment]
@mudox if you are using [ctrlpvim/ctrlp.vim](https://github.com/ctrlpvim/ctrlp.vim) can you try updating it to the lastest master?

Upon updating (at least for me) I can no longer replicate the issue.

There was recently a [PR](https://github.com/ctrlpvim/ctrlp.vim/commit/d13e8ee2b543e8fdc247dd0fb1495e16976ca423) that got merged for vim-devicons support (without all the messy hack that is required for [kien/ctrlp.vim](https://github.com/kien/ctrlp.vim))

**Comment by mudox** [comment]
:+1: It's fixed, thank you very much
