### ISSUE TITLE
OS icon displays as Linux with Neovim on Mac

### ISSUE THREAD

**Issue by trodrigu** [ryanoasis/vim-devicons#118]
This is minor as I like penguins, but why would it be showing a Linux Penguin instead of an Apple in Neovim?  Thanks man these icons are money.

**Comment by ryanoasis** [comment]
@trodrigu haha.

The deciding factor is the file's format, check `:echo &fileformat` to see if it is returning `unix`.

For reference on how it should be working see #66 

Thanks for the kind words about the icons, actually most of them are *not* created by me. I have only created a few by hand and the rest have been pulled from other sources

**Comment by trodrigu** [comment]
It is in fact returning `unix,dos`

**Comment by ryanoasis** [comment]
It seems that the file itself does not have Mac line endings but seems like the old rule where Mac would use (CR) now on OS X it is not the case (LF) ?

You can try setting `set ffs=mac,unix,dos` in your `vimrc` and see if that does what you want :blush:

**Comment by trodrigu** [comment]
After reading [this](http://vim.wikia.com/wiki/File_format) it seems as though Mac OS X endings are in fact line feed (LF).  Also it is designated as `unix` so I added in an `if` to see if the OS is `Darwin` in this [pull](https://github.com/ryanoasis/vim-devicons/pull/121).

**Comment by ryanoasis** [comment]
Good stuff. Thanks
