### ISSUE TITLE
HTML icon  not working

### ISSUE THREAD

**Issue by robertbnd** [ryanoasis/vim-devicons#119]
Hi! Just a question Why all icons are working correctly but html is a rare simbol?
![html](https://cloud.githubusercontent.com/assets/4907027/10823269/7c1941e4-7e20-11e5-89b9-633120fc67a5.png)

and github 
![git](https://cloud.githubusercontent.com/assets/4907027/10823298/a344f74a-7e20-11e5-880c-524a164f3eda.png)

**Comment by robertbnd** [comment]
The problemas was I had installed Font Meslo  https://github.com/powerline/fonts because on the github of airline is the font we need install.  I deleted it.

**Comment by ryanoasis** [comment]
@robertbnd Ah okay glad you got it figured out :smile: . I am closing this issue for now then :+1:
