### ISSUE TITLE
Add tests for build process (Github Actions)

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/vim-devicons#122]
implement travis ci

add tests later?

**Comment by her** [comment]
hey @ryanoasis not sure if this helps but I added a Rakefile to my PR on 'Instructions' branch, but this pleased the robo and the build is passing... 

so it's a start? 🙃

**Comment by ryanoasis** [comment]
@her Thanks. No problem, you don't have to worry about the build failing for now :smile: because I dont really have any tests yet :blush:

**Comment by her** [comment]
Well at least now there are pretty green checks✅ in the meantime? 😆 haha

**Comment by ryanoasis** [comment]
Pushing this off again to get more immediate things done (including PRs and fixes that are waiting to be pushed up!)

**Comment by ryanoasis** [comment]
Now that we have this (#236) I updated the name and focus of this ticket to be implemented automated tests of some kind

**Comment by her** [comment]
That’s awesome 👏

**Comment by ryanoasis** [comment]
@her Again, thanks for all your contributions.

**Comment by her** [comment]
hey @ryanoasis was looking at this, seems really straightforward since @kutsan has added `.travis.yml` file next steps seem to be signing up at Travis-ci.com and adding vim-devicons 

https://docs.travis-ci.com/user/tutorial/

Link for the curious! 

Maybe easy to just connect it and see how it behaves, then we can go from there?

**Comment by ryanoasis** [comment]
@her Thanks! Wow I completely dropped the ball on getting the integration, not sure why I thought it was already setup!

I did go through the link but then found we still have to use the travis-ci.ORG

info here:
---
Existing Open Source Repositories on travis-ci.org #
Open source projects and their build history will continue to run on travis-ci.org at this time.

However, you can be included in the closed beta testing to start migrating your open source repositories to travis-ci.com.

To have any public repository migrated over, it must be first activated on travis-ci.com using GitHub Apps.
Send us an email to support@travis-ci.com with the subject “Open Source Migration Beta Testing”
Check out what the beta testing includes on this open source to travis-ci.com migration guide.
```

**Comment by ryanoasis** [comment]
We have now moved to Github actions (thanks to @kazukazuinaina)

**Comment by kazukazuinaina** [comment]
@ryanoasis 

Could you check this PR?

https://github.com/ryanoasis/vim-devicons/pull/329

**Comment by her** [comment]
@kazukazuinaina that PR looked great and it's merged! 

Can we close this issue? :) Think we can have other issues (and even reference this one if needed) to track any future work

**Comment by kazukazuinaina** [comment]
@her 

Thanks for comment!
Okay, I close this issue.
Of course, if I have any problems with testing, I'll address them, Thanks!
