### ISSUE TITLE
Vim become slow after update to 0.7.0 

### ISSUE THREAD

**Issue by zaferot** [ryanoasis/vim-devicons#127]
Hi All. After the upgrade to 0.7.0 my Vim is extremely lagging and there are strange visual artifacts. Please see that attached screenshot. I had to disable the plugin for now.
My vimrc is in my profile. I use patched Meslo LG S (patched via font-patcher).
Please let me know if you need any additional information.
Thanks!
![snapshot1](https://cloud.githubusercontent.com/assets/4263125/11322251/793dc836-90eb-11e5-86b2-188b4203ade8.jpg)

**Comment by her** [comment]
Also getting this +1

[![https://gyazo.com/8f8104e79428bfda9cdd25673e514443](https://i.gyazo.com/8f8104e79428bfda9cdd25673e514443.png)](https://gyazo.com/8f8104e79428bfda9cdd25673e514443)

**Comment by ryanoasis** [comment]
Eek! :open_mouth: 

Yep I have questions:
* What OS? OS X?
* GUI or terminal vim?
* Did the problem immediately go away upon disabling devicons?
* was devicons the only plugin updated?
* with the issue occurring do you have anything in the  output of `:messages`?
* can you give me a list of your plugins or a link to your vimrc?

I will try to replicate today. Cheers

**Comment by zaferot** [comment]
HI @ryanoasis,

> What OS? OS X?

Arch Linux

> GUI or terminal vim?

Terminal

> Did the problem immediately go away upon disabling devicons?

Yes. ( but Vim has to be restarted).

> was devicons the only plugin updated?

There were two or three plugins updated.

> with the issue occurring do you have anything in the output of :messages?

Now, when the plugin is enabled the issue is constant. It's not periodic or temporary.
`:messages` output gives me `Messages maintainer: Bram Moolenaar <Bram@vim.org>`.

**Comment by her** [comment]
OS X, terminal vim -v 7.4.922

>Did the problem immediately go away upon disabling devicons? was devicons the only plugin updated?

yes 😭

>with the issue occurring do you have anything in the output of :messages?

I had to disable the plugin before troubleshooting because it broke so hard 🤕

>can you give me a list of your plugins or a link to your vimrc?

My current plugin list: 

'altercation/vim-colors-solarized'
'scrooloose/nerdtree'
'tpope/vim-fugitive'
'airblade/vim-gitgutter'
'scrooloose/syntastic'
'junegunn/goyo.vim'
'Valloric/YouCompleteMe'
'junegunn/vim-emoji'
'Yggdroot/indentLine'
'itchyny/lightline.vim'


Hope that helps 😊

**Comment by epilande** [comment]
Also noticed my vim got super laggy after updating to `0.7.0`. Once I disabled vim-devicons, the lag went away. 

I'm using OSX, iTerm, & Neovim.

**Comment by ryanoasis** [comment]
Here is the fix if anyone needs it ASAP: https://gist.github.com/ryanoasis/7be48afae7c700d1a465  :tada:

^ caches the system call, it was my fault that I didn't realize that new system call in the PR would be executed SO often

I will push something tomorrow :sleeping:

**Comment by her** [comment]
thanks @ryanoasis! good stuff 🤓👏🏻
