### ISSUE TITLE
Remove and Confine Font Installation(nerd-font) Instructions to Nerd-Font Repository

### ISSUE THREAD

**Issue by her** [ryanoasis/vim-devicons#128]
Currently vim-devicons is sort of a blender of instructions encompassing and overlapping two repositories. Streamlining the instructions by siloing them in their respective repo's would really simplify the readme.md 

Font-Configuration should fold into general devicons Instructions where Font Installation is moved to Nerd-Fonts 

Users then are greeted by a sane process guide 

Get Font > Install Plugin > Enjoy 

I have a working branch of this I can push later, just wanted to get your thoughts on this @ryanoasis

**Comment by ryanoasis** [comment]
These have both been merged. This is done I think. Closing (reopen if there is more to it).
