### ISSUE TITLE
Error when using open/close symbol for folders

### ISSUE THREAD

**Issue by Arelav** [ryanoasis/vim-devicons#130]
When i set in my .vimrc:
let g:DevIconsEnableFoldersOpenClose = 1

I accept the error when pressing o to open  folder in NERDTree:

Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..178[26]..177[3]..WebDevIconsNERDTreeMapActivateNode:
line   32:
E119: Not enough arguments for function: 140

**Comment by ryanoasis** [comment]
@Arelav Thanks for the report!

This might be due to latest NERDTree 5.0.0 release: https://github.com/scrooloose/nerdtree/blob/master/CHANGELOG

I will take a look

**Comment by thornycrackers** [comment]
I am also having a similar issue with this:

Error detected while processing function nerdtree#ui_glue#invokeKeyMap..73..72..WebDevIconsNER
DTreeMapActivateNode:
line   32:
E119: Not enough arguments for function: 35

**Comment by ryanoasis** [comment]
**update:**

works from: https://github.com/scrooloose/nerdtree/commit/a0de028688b4802de65c1b17963d7e5479035530 and older

breaks on: https://github.com/scrooloose/nerdtree/commit/665f326577e319f4fd1321ee664365b0a81b8d37 and newer

**Comment by ryanoasis** [comment]
feel free to test this out in [0.8.0 branch](https://github.com/ryanoasis/vim-devicons/tree/0.8.0)

Not fully tested but seems stable
