### ISSUE TITLE
Unite file_rec/async question

### ISSUE THREAD

**Issue by mhartington** [ryanoasis/vim-devicons#131]
Is there any particular reason why you the icons won't work with unite's `file_rec/async` search method?

**Comment by mhartington** [comment]
Added file_rec/async to https://github.com/ryanoasis/vim-devicons/blob/master/plugin/webdevicons.vim#L398

```
call unite#custom#source('file,file_rec,file_rec/async,buffer', 'converters', 'devicons_converter')
```
Seems to work fine in my tests. Would love to make a PR for this.

**Comment by ryanoasis** [comment]
@mhartington Good stuff I think! :+1: 

I can't remember the exact reasoning and I don't think it was a good one (I am not a Unite regular user so I didn't use/test all the types).

**Comment by mhartington** [comment]
If you have any unit test or anything I may need to ping you about that. Never unit tested something in vim before. 

Mike Hartington

**Comment by ryanoasis** [comment]
@mhartington There is currently no unit testing in place. I would love to have some unit tests ideally but maybe later. I am working to get at least some _basic_ tests integrated with Travis CI: mostly to check for errors in using the plugin/settings.
