### ISSUE TITLE
getting some weird characters for the icon folder.

### ISSUE THREAD

**Issue by Jose-27** [ryanoasis/vim-devicons#134]
not sure what is happening here. I am getting some weird characters for the icon folders. I am using ubuntu 14.04 Any help will be appreciated 
![screenshot from 2015-12-20 13 18 56](https://cloud.githubusercontent.com/assets/5156260/11919302/96b70d54-a71c-11e5-9b83-72b11d7281f8.png)

**Comment by ryanoasis** [comment]
What font are you using?

**Comment by ryanoasis** [comment]
@Jose-27 are you still having this issue or were you able to resolve?

**Comment by Jose-27** [comment]
sorry not anymore, thanks anyways

**Comment by ryanoasis** [comment]
Thanks for confirming. Going to close this.

By the way, just for details sake, do you remember what the solution was?

**Comment by chrisbward** [comment]
I'm starting to get these now - gnome terminal in neovim, I have the font installed...
