### ISSUE TITLE
Mac and Terminal

### ISSUE THREAD

**Issue by xavierartot** [ryanoasis/vim-devicons#136]
Hi,
I'm using the termimal on Mac.
And for me it doesn't work
I'm using Iterm

line 167
```
set encoding=utf-8
set guifont=Droid\ Sans\ Mono\ for\ Powerline\ Plus\ Nerd\ File\ Types:h11
```

the plugin is at a end:
```
"nice icons in NERDTree
Plugin 'ryanoasis/vim-devicons'

"Translate
"Plugin 'iadept/vim-gtranslate' 

" All of your Plugins must be added before the following line
call vundle#end() " required
```

I have a cross in airline and nerdTree nothing happens?

my .vimrc
https://github.com/xavierartot/github-vim/blob/master/.vimrc

**Comment by ryanoasis** [comment]
Sorry for the delayed response. Could you attach a screenshot of what you see (might help me more quickly identify possible issues)?

**Comment by ryanoasis** [comment]
@xavierartot are you still having this issue?

**Comment by xavierartot** [comment]
no

**Comment by ryanoasis** [comment]
If you don't mind me asking, do you know/remember what the issue or fix was?

**Comment by r01010010** [comment]
I'm having same issue, instead of the icons I see `[?]` where the icon should be. I downloaded 'devicons' and installed the `ttf`, the name apparently is changed to `icomoon`. I'm using iterm2.
