### ISSUE TITLE
Plugin probably shouldn't show interstitial error message about ctrlp

### ISSUE THREAD

**Issue by michaelmrose** [ryanoasis/vim-devicons#137]
While this is actually very useful information I don't think any plugin on principal should cause vim to pause to show users information on load.

In the context of a plugin manager ONE plugin, your plugin manager informing users about no longer supported plugins with an up to date fork would be a great feature.

However plenty of people use a large number of plugins imagine how annoying using vim would be if a significant number of plug ins used this methodology.

At minimum it should be configured to only show this info once.

**Comment by ryanoasis** [comment]
Thanks. Good points.. maybe I didn't realize how annoying this would be (especially since I don't use the unsupported plugin). :+1: 


> At minimum it should be configured to only show this info once.

Do you by chance know to accomplish this?


It might be some time before I get to this. If it is too long PR are very welcomed :smile:

**Comment by michaelmrose** [comment]
I think the easiest way would be to drop a file in the plugins own dir and test for the existence of the file before showing the message.  Preferably after things have loaded so as not to slow that down

**Comment by betoharres** [comment]
I don't use the unsuported version and somehow I'm getting the same message.

**Comment by ryanoasis** [comment]
@betoharres Are you sure you have the latest version of [ctrlpvim/ctrlp.vim](https://github.com/ctrlpvim/ctrlp.vim)?

Because it is searching for a variable I added in a [PR](https://github.com/ctrlpvim/ctrlp.vim/pull/104) (`g:ctrlp_mruf_map_string`)
