### ISSUE TITLE
wrong icon

### ISSUE THREAD

**Issue by robertbnd** [ryanoasis/vim-devicons#138]
![screenshot from 2016-02-03 13-23-28](https://cloud.githubusercontent.com/assets/4907027/12794409/812d7a8c-ca7a-11e5-84e9-41b9bdfad6ae.png)

Do you have a idea why I get the wrong icon?

**Comment by ryanoasis** [comment]
Which font are you using?

What version of vim-devicons do you have?
`echo webdevicons#version()`

Can you try downloading the latest version of that font from [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts) ?

**Comment by robertbnd** [comment]
Sorry I don't know what happened... now  it's works thanks, I believe I installed the wrong font.

**Comment by ryanoasis** [comment]
Great! Thanks for the update! :tada: 

Closing.
