### ISSUE TITLE
Is it possible to colorize only the icon?

### ISSUE THREAD

**Issue by rahmatawaludin** [ryanoasis/vim-devicons#142]
Just wondering, I know that we could colorize the filename with the icon. How about colorize only the icon? Is that possible?

Something like js icon in yellow, html5 icon in orange, php icon in purple, ruby icon in red, etc..

**Comment by ryanoasis** [comment]
Yes, it is. I was just messing around with this because of your questions.

Similar to https://github.com/scrooloose/nerdtree/issues/433#issuecomment-92590696

Here is what worked for me:

```vim
" test highlight just the glyph (icons) in nerdtree:
autocmd filetype nerdtree highlight haskell_icon ctermbg=none ctermfg=Red guifg=#ffa500
autocmd filetype nerdtree highlight html_icon ctermbg=none ctermfg=Red guifg=#ffa500
autocmd filetype nerdtree highlight go_icon ctermbg=none ctermfg=Red guifg=#ffa500

autocmd filetype nerdtree syn match haskell_icon ## containedin=NERDTreeFile
" if you are using another syn highlight for a given line (e.g.
" NERDTreeHighlightFile) need to give that name in the 'containedin' for this
" other highlight to work with it
autocmd filetype nerdtree syn match html_icon ## containedin=NERDTreeFile,html
autocmd filetype nerdtree syn match go_icon ## containedin=NERDTreeFile
```

**Comment by rahmatawaludin** [comment]
Hmm.. I still can't get it to work. Here's what I do..

![screen shot 2016-03-01 at 9 09 06 am](https://cloud.githubusercontent.com/assets/1274849/13415430/525f1d5a-df8d-11e5-9458-e0f756d43c9a.png)

I even put those line on my vimrc and restart my vim.

**Comment by ryanoasis** [comment]
Hmm I put them at the bottom of my `vimrc`. I just checked that it works for me in terminal vim (xfce terminal).

I don't _think_ iTerm or neovim should have any particular issues.

You could make sure they show up for nerdtree syntax (`:syn` when in a nerdtree buffer).

I don't have any particular ideas right now :cry:

**Comment by rahmatawaludin** [comment]
Never mind, its not really important. You could just close this issue.. :)

**Comment by ryanoasis** [comment]
Hmm okay, well if you do get it working or still want some help ping back on this issue :smile:. 

Actually this is good info I think so I will probably leave this issue open and at the very least add what worked for me to the readme and/or wiki :+1:
