### ISSUE TITLE
Is it possible to dynamically disable devicons when patched font not found?

### ISSUE THREAD

**Issue by rahmatawaludin** [ryanoasis/vim-devicons#144]
Just wondering. Is this possible?
Or just simply a command to disable devicons manually when I've started vim.

**Comment by ryanoasis** [comment]
That is interesting. I am not so sure. If it is gui vim I guess you could check the value of `:set guifont?` and do some matching on it to look for 'Nerd Fonts' or similar but even this wouldn't be 100%.

In vim it is determined by the terminal so I don't think there is such a way.

**Comment by rahmatawaludin** [comment]
Is there an ex command to disable devicon when I'm already in vim?

**Comment by ryanoasis** [comment]
You can disable the plugin with:

`let g:webdevicons_enable = 0` from the [config options section](https://github.com/ryanoasis/vim-devicons#extra-configuration)

**Comment by ryanoasis** [comment]
Closing this. re-open if you need more information or help :smile:
