### ISSUE TITLE
haxe support

### ISSUE THREAD

**Issue by jdonaldson** [ryanoasis/vim-devicons#146]
I'd like a haxe icon:
http://haxe.org/

Here's an svg:
https://commons.wikimedia.org/wiki/File:Haxe_logo.svg

**Comment by jdonaldson** [comment]
wrong repo for this request.

**Comment by ryanoasis** [comment]
:stuck_out_tongue_closed_eyes: No problem.

Which repo was this meant for just out of curiousity? :smile:

**Comment by jdonaldson** [comment]
https://github.com/vorillaz/devicons/issues/99

I thought this repo tracked the actual font assets.

**Comment by ryanoasis** [comment]
I see. Yeah then [devicons](https://github.com/vorillaz/devicons) is probably the best place to request :+1: , however alternatively I have added additional glyphs on the [Nerd Fonts project](https://github.com/ryanoasis/nerd-fonts) in case you are unable to get the request through for whatever reason

**Comment by jdonaldson** [comment]
Thanks!  Good to know there's another option.  I appreciate you putting together this package, several people were asking what app i was using, not realizing it was a terminal screen.

**Comment by ryanoasis** [comment]
Hey no problem and thank you!

> ...not realizing it was a terminal screen.

:laughing: that is awesome

**Comment by kLabz** [comment]
@jdonaldson did you find a way to have the haxe glyph in the end?

**Comment by jdonaldson** [comment]
Nope, the other pull request did not get a response.  Maybe you could try
another?  I'll get around to it evenutally if not.
