### ISSUE TITLE
Replacing underscores is bad.

### ISSUE THREAD

**Issue by dominikduda** [ryanoasis/vim-devicons#147]
In Ruby on Rails underscore before file name indicates that file is [partial](http://guides.rubyonrails.org/layouts_and_rendering.html#using-partials). I am pretty sure other langs/frameworks use same convention.

I didn't go very deep into this but as far as I know vim-devicons plugin removes (or replaces) underscores for some reason (e. g. in NERDTree). This isn't good. Not knowing at the first glance whether file is partial or not is pretty annyoing.

**Comment by ryanoasis** [comment]
First, thanks for the report.

I am not too sure that it is this plugin but it is possible or maybe a combination with other plugins is causing underscores to be removed. I just haven't encountered it yet personally.

So far I have not seen what you are describing and I just did a quick test of a new file as viewed in NERDTree below:
![selection_15_03_16_12 29 51_392x328_001](https://cloud.githubusercontent.com/assets/8083459/13785378/b616d9ce-eaa9-11e5-8d9f-c29186242b08.png)


The glyphs are added through NERDTree flags api so if there is some replacing perhaps something has changed on that plugin or possibly conceal is doing something funky: https://github.com/ryanoasis/vim-devicons/blob/f8841e2bd46e9fed95c0389190e3ef1b6ba77440/plugin/webdevicons.vim#L334-L337


Are you seeing this with all files that have leading underscores?

Can you post your vimrc or list the plugins you use?

You can try `:set conceallevel=0` to see if that helps

Thanks!

**Comment by dominikduda** [comment]
So I fixed the problem  (I'm not sure how) and I can't go to back to buggy state.

I observed in on like 2-3 files, so I think all of the underscores were replaced. 

I added this to my .gvimrc (Although removing it doesn't make bug come back):
```
if exists("g:loaded_webdevicons")
    call webdevicons#refresh()
endif
```

Im leaving list of my plugins in case bug will happen to somebody else in the future (So there will be something to compare with):
```
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-easytags'
Plugin 'easymotion/vim-easymotion'
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/syntastic'
"ctrl+p search
Plugin 'kien/ctrlp.vim'
Plugin 'JazzCore/ctrlp-cmatcher'
Plugin 'Valloric/YouCompleteMe'
Plugin 'tpope/vim-commentary'
"confrim autocompletion with tab
Plugin 'ervandew/supertab'
Plugin 'tpope/vim-surround'
Plugin 'bling/vim-airline'
Plugin 'bronson/vim-trailing-whitespace'
"select region +/-
Plugin 'terryma/vim-expand-region'
Plugin 'terryma/vim-multiple-cursors'
"maximize/minimize window on f3
Plugin 'szw/vim-maximizer'
Plugin 'ngmy/vim-rubocop'
Plugin 'tpope/vim-endwise'
Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'jiangmiao/auto-pairs'
Plugin 'slim-template/vim-slim'
Plugin 'lambdalisue/vim-fullscreen'
"language specific
Plugin 'vim-ruby/vim-ruby'
Plugin 'tpope/vim-haml'
Plugin 'tpope/vim-rails'
Plugin 'ryanoasis/vim-devicons'
call vundle#end()
filetype plugin indent on
```

I was messing with my .gvimrc a lot I could made some change which I can't find now.

Also i moved "Plugin 'ryanoasis/vim-devicons" to the end of the list.

**Comment by ryanoasis** [comment]
Thanks, I want to at least try to replicate it so I will leave the issue open for now.

It probably won't be anytime soon that I get to this however unless it starts popping up more

**Comment by ryanoasis** [comment]
Cannot seem to replicate this with the given `vimrc` above. Closing this for now, we can re-open if the problem crops up again.
