### ISSUE TITLE
"ls" with icon implementation of this? (SEE: https://github.com/ryanoasis/bash-devicons)

### ISSUE THREAD

**Issue by dimitrieh** [ryanoasis/vim-devicons#150]
sorry if this is not the place to ask!

I was wondering if there is an implementation of this for the "ls" command. So I get an overview of my files and directories within my shell, but with the icons! ;)

**Comment by ryanoasis** [comment]
Not a problem.

Hey this is a really good idea. I thought I might have seen some similar implementations but can't remember where I spotted them (if at all).

If I get some time maybe I will throw something together (or of course feel free) :smile:

**Comment by strages** [comment]
Would be awesome! Wil see ;) not really my kind of thing to produce though, would be awesome to use!

**Comment by rosshadden** [comment]
Yeah I can see this being more general than just vim.  To the point where maybe you even eventually flip the title:  `devicons-vim`.  And have `devicons-unix`, `devicons-sublime`, etc.  But then again, who has time for that :wink:

**Comment by ryanoasis** [comment]
> eventually flip the title: devicons-vim

Not totally opposed to that. I have already changed the repo and name once (was vim-webdevicons)

The name was partly based on http://vorillaz.github.io/devicons but I have added glyphs from other icon sets as well as some custom ones ([Nerd Fonts](https://github.com/ryanoasis/nerd-fonts))

**Comment by ryanoasis** [comment]
Hey this is pretty basic and fragile but I started on something: https://github.com/ryanoasis/bash-devicons

**Comment by rosshadden** [comment]
Just my two cents:  I don't think you should call it `bash-devicons`.  `ls` is a unix binary, which really doesn't have anything to do with `bash`.  Many people don't even use `bash`; for example I use `zsh`.  And since you're prefixing the binaries with `devicons-`, it might make sense to be consistent with the name, calling it `devicons-<name>`, like `devicons-unix` or whatever you decide.

</rant>! :smile:

**Comment by ryanoasis** [comment]
@rosshadden Thanks for the feedback.

Heh, I plead ignorance on that so thanks for the info.

I was thinking of actually splitting the 'ls' script into a separate repo (devicons-ls or something) and have the 'bash' portion basically just the function in bash that determines the filetype extension so it could be included with other scripts in the future.. or something :blush:

**Comment by ryanoasis** [comment]
Going to close this out, considering this: https://github.com/ryanoasis/bash-devicons
