### ISSUE TITLE
missing config info for pattern based symbols in readme

### ISSUE THREAD

**Issue by adelarsq** [ryanoasis/vim-devicons#152]
For some reason the config:

```vim
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['js'] = 'a'
```

Don't work for files with name like ```jquery-1.7.1.js```, ```jquery-1.7.1.min.js```, ```jquery.min.js``` or ```jquery.js```, but works for ```jquery.js```:

<img width="337" alt="screenshot" src="https://cloud.githubusercontent.com/assets/430272/15093934/f2abb0bc-146b-11e6-977f-22495c7765dd.png">

Configs:

```vim
let g:webdevicons_enable = 1
let g:webdevicons_enable_nerdtree = 1
let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '
if !has("gui_running")
    if has("win32")
        let g:webdevicons_enable = 0
    endif
endif
if g:sysop == "mac"
    vim let g:WebDevIconsOS = 'Darwin'
endif
silent! if emoji#available()
    let g:webdevicons_conceal_nerdtree_brackets = 1
    let g:WebDevIconsUnicodeGlyphDoubleWidth = 1
    let g:WebDevIconsUnicodeDecorateFolderNodes = 1
    let g:DevIconsEnableFoldersOpenClose = 1
    let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {}
    let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['js'] = 'a'
endif
```

#### Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] What **version** of vim are you using?
  MacVim 7.4 patch 1816
- [x] What **version** of vim-devicons are you using?
  0.8.2
- [x] Are you using vim from the terminal or a GUI vim?
  GUI
- [x] Are you using Mac, Linux or Windows?
  Mac

**Comment by adelarsq** [comment]
There is an undocumented config that did solve the problem:

```vim
let g:WebDevIconsUnicodeDecorateFileNodesPatternSymbols = {}
let g:WebDevIconsUnicodeDecorateFileNodesPatternSymbols['.*jquery.*\.js$'] = 'a'
let g:WebDevIconsUnicodeDecorateFileNodesPatternSymbols['.*angular.*\.js$'] = 'a'
let g:WebDevIconsUnicodeDecorateFileNodesPatternSymbols['.*backbone.*\.js$'] = 'a'  
let g:WebDevIconsUnicodeDecorateFileNodesPatternSymbols['.*require.*\.js$'] = 'a'   
let g:WebDevIconsUnicodeDecorateFileNodesPatternSymbols['.*materialize.*\.js$'] = 'a'
let g:WebDevIconsUnicodeDecorateFileNodesPatternSymbols['.*materialize.*\.css$'] = 'a'
let g:WebDevIconsUnicodeDecorateFileNodesPatternSymbols['.*mootools.*\.js$'] = 'a' 
```   
With some time I will create a pull request for this.

**Comment by ryanoasis** [comment]
Thanks that makes sense. The configuration is mentioned on the readme but you are right in that it doesn't exactly show very well how to use it. 👍

**Comment by ryanoasis** [comment]
Just went through this again and yes the pattern matches take precedence over the file extensions (which is probably what we want) but you are right in that the readme is missing the information for the option.
