### ISSUE TITLE
Vundle doc/tags

### ISSUE THREAD

**Issue by cescoferraro** [ryanoasis/vim-devicons#164]
I am quite new to vim, so this might be more of a question, than a bug. Although, it does not prevent me any functionality, I think something is not right.

Everytime I run vundle :PluginInstall command, it clones a copy of vim-devicons at "~/.vim/plugins" as expected. 👍 
The problem is that it creates a folder called "doc/tags" inside this freshly cloned repo, that is not on the original repo. So this mess with my dotfile's `git status`, I can still push my repo normally, but no othe vim plugin that I have used so far bahaves this way.

![screen shot 2016-09-11 at 2 41 50 pm](https://cloud.githubusercontent.com/assets/6259987/18419302/ee34061c-782d-11e6-9e73-02590536d9b4.png)

**Comment by ryanoasis** [comment]
Sorry for the delayed reply. This link may be of some help to you: http://usevim.com/2012/12/21/vim-101-help-tags/
:smile:

**Comment by ryanoasis** [comment]
@cescoferraro Is this still an issue?

**Comment by cescoferraro** [comment]
@ryanoasis I wish I could avoid it.
But its not a Vundle issue at all
