### ISSUE TITLE
Error thrown when sourcing vim without opening NERDTree

### ISSUE THREAD

**Issue by tommyc38** [ryanoasis/vim-devicons#167]
#### Required Info
- [ ] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
  Yes.  
- [ ] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
  Yes.
- [ ] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
  Yes
- [ ] What **version** of vim are you using? 
  Vim 8.0
- [ ] What **version** of vim-devicons are you using?
  0.8.3
- [ ] Are you using vim from the terminal or a GUI vim?
  Vim from terminal
- [ ] Are you using Mac, Linux or Windows?
  macOS Sierra

I get the error in the screenshot only if i resource vim without opening NERDTree first.  My vim air-line goes blank also until I switch another buffer. 
#### Optional Info

<img width="989" alt="screen shot 2016-10-03 at 8 09 09 pm" src="https://cloud.githubusercontent.com/assets/10190567/19060714/b1565bb0-89a7-11e6-8bd8-1d076444bc16.png">

**Comment by ryanoasis** [comment]
Thanks for your report. I will look into this

**Comment by ryanoasis** [comment]
@tommyc38 Can you please provide a link to your `vimrc` or preferably provide the minimum vimrc setup to replicate this issue?

Unable to replicate so far but a few guesses: Make sure devicons plugin loads after Nerdtree.
