### ISSUE TITLE
Include Order Instructions Wrong

### ISSUE THREAD

**Issue by F1LT3R** [ryanoasis/vim-devicons#168]
#### Required Info

N/A (Documentation issue)

#### Optional Info

There's a conflict in your documentation.

First is says that "DevIcons" should load **before** plugins.

<img width="794" alt="screen shot 2016-10-10 at 12 11 55 pm" src="https://cloud.githubusercontent.com/assets/1218446/19242848/fc93dca2-8ee2-11e6-8d33-c84210d4dc39.png">

Then it says that "DevIcons" should load **after** plugins.

<img width="906" alt="screen shot 2016-10-10 at 12 12 16 pm" src="https://cloud.githubusercontent.com/assets/1218446/19242867/1d30b304-8ee3-11e6-801d-84084693bec4.png">

Which is it? Before or after?

**Comment by ryanoasis** [comment]
@F1LT3R Hey good catch.

The latter is correct (it should load **after** the plugins mentioned *not* before).

Feel free to submit a PR or if you aren't interested in that I will fix it soon. Thanks!
