### ISSUE TITLE
Support vimfiler in explorer mode?

### ISSUE THREAD

**Issue by Leeiio** [ryanoasis/vim-devicons#171]
Now i found vim-devicons support vimfiler only when use `:VimFiler` but not `:VimFilerExplorer`, so do you have a plan to support it?
Thanks!

**Comment by ryanoasis** [comment]
So I figured this out :smile: 

Would you prefer the icons column before or after the files (type) ?

![vimfilerexplorer](https://cloud.githubusercontent.com/assets/8083459/19412818/b325a28c-92eb-11e6-8302-e3f4033e8bce.png)

**Comment by Leeiio** [comment]
I prefer before the files(type) :)
It's more intuitive.

**Comment by ryanoasis** [comment]
@Leeiio Sure.. actually I can make it configurable

**Comment by ryanoasis** [comment]
I decided to remove the 'type' column as it is redundant when VimDevIcons are present.

Customization/configuration of the columns could be added later if there is enough demand. For now I think this does what you want.

**Comment by Leeiio** [comment]
Nice! Thank you!

**Comment by DerWeh** [comment]
If it's easy to realize, I would prefer the option to put the icons right in front of the filename. The `nerdtree` layout seems way clearer.
Especially in the explorer mode the icons are simply to far away from the name to be helpful.

**Comment by asilvadesigns** [comment]
glad I found this issue! I was curious about a way to put icons in front of the filename.. any chance that can happen!? : )

**Comment by ryanoasis** [comment]
@asilvadesigns Yeah we could add an option for that.

**Comment by asilvadesigns** [comment]
@ryanoasis do you drink coffee? If so, I would sponsor at least a few cups of some good beans.

**Comment by ryanoasis** [comment]
@asilvadesigns Haha yeah I do sometimes :smile: Thanks! that's very kind but totally not necessary :blush: that being said I won't turn down anything that supports the project (even indirectly).. I just wouldn't know how to handle such things to be honest :blush: 

Honestly VimDevicons hasn't been getting as much love as Nerd Fonts lately but I'll probably try to cobble together a release for December :smile: and this could be included without too much effort (there is already [1 open PR](https://github.com/ryanoasis/vim-devicons/pull/217) ready to go).
