### ISSUE TITLE
Update readme with minimum version of Ctrlp and NERDTree info

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/vim-devicons#176]
#### Required Info

* Add information on the readme about needing an up to date version of [CtrlP](https://github.com/ctrlpvim/ctrlp.vim) and [NERDTree](https://github.com/scrooloose/nerdtree) vim plugins (as the devicons plugin will cause warnings when certain features are not detected). This is not as clear as it should be on the readme.

see: #174 for source of the raised enhancement

#### Optional Info

none

**Comment by Melon-Bread** [comment]
I should be able to do this, is there any particular location in the README you want it? I feel it could got a couple of places, but I think in installation would be best.

**Comment by ryanoasis** [comment]
Closed with #177
