### ISSUE TITLE
All icons in MacVim can be only show half.

### ISSUE THREAD

**Issue by hashmaparraylist** [ryanoasis/vim-devicons#179]
In the airline's tab and statusbar

![2016-10-21 9 38 58](https://cloud.githubusercontent.com/assets/864384/19583821/566ef2d8-9772-11e6-9ef9-330190077cc8.png)

![2016-10-21 9 39 03](https://cloud.githubusercontent.com/assets/864384/19583827/5eb6e5ae-9772-11e6-9f05-46b334e0fb52.png)

In the startify

![2016-10-21 9 39 07](https://cloud.githubusercontent.com/assets/864384/19583840/7aa708ca-9772-11e6-834d-771194d75dc0.png)

---

MacVim Version:

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 14 2016 09:19:30)
MacOS X (unix) version
Included patches: 1-32
Compiled by travis@Traviss-Mac-592.local

---

OS Version:
macOS Sierra 10.12

**Comment by ryanoasis** [comment]
Thanks for the report and relevant details

This is dup/related to #133

**Comment by alex-shamshurin** [comment]
The same is here

**Comment by R4YM3** [comment]
bump

**Comment by ryanoasis** [comment]
Closing, let's use #133 to track on this
