### ISSUE TITLE
it does not work all, just some. what's the promble?

### ISSUE THREAD

**Issue by liangguohuan** [ryanoasis/vim-devicons#181]
- nvim --version: 0.1.6-dev
- Vim (version: ): 8.0
- Operating system/version: Ubuntu 14.04.5 LTS
- Terminal name/version: Gnome-Terminal: 3.6.2

it just work for `nerdtree` and `vim-startify`

I do set code like below:

```
" loading the plugin 
let g:webdevicons_enable = 1
" adding the flags to NERDTree 
let g:webdevicons_enable_nerdtree = 0
" adding the custom source to unite 
let g:webdevicons_enable_unite = 1
" adding the column to vimfiler 
let g:webdevicons_enable_vimfiler = 1
```

**Comment by ryanoasis** [comment]
@liangguohuan Sorry for the delayed response. Can you provide a screenshot and a minimal `vimrc` (particularly the loading of plugins) ?

**Comment by liangguohuan** [comment]
Thanks for your response. The simple `vimrc` file i test like:

~~~
" nvim python virtual environments.
let g:python_host_prog  = '/home/hanson/.pyenv/versions/neovim2/bin/python'
let g:python3_host_prog = '/home/hanson/.pyenv/versions/neovim3/bin/python'

set nocompatible              " be iMproved, required
filetype off                  " required

" vim-plug start
call plug#begin('~/.vim/bundle')

Plug 'https://github.com/ryanoasis/vim-devicons.git'
Plug 'https://github.com/Shougo/unite.vim.git'
Plug 'https://github.com/Shougo/vimfiler.vim.git'

" All of your Plugs must be added before the following line
call plug#end()
filetype plugin indent on    " required

" vim: fdm=marker ts=4 sw=4 sts=4 expandtab
~~~

**Comment by ryanoasis** [comment]
@liangguohuan 
Can you move `Plug 'https://github.com/ryanoasis/vim-devicons.git'` to _after_ the unite and vimfiler lines and retry? 

The plugin should load _after_ the others.

**Comment by liangguohuan** [comment]
it works, thanks!

**Comment by ryanoasis** [comment]
Sure anytime 😄 . Glad you got it working. Thanks for the update also.
