### ISSUE TITLE
Cutting off text

### ISSUE THREAD

**Issue by cj** [ryanoasis/vim-devicons#186]
It seems to be cutting off the text.  ![](http://i.imgur.com/TrLnOhr.png)  I'm trying to figure out what is causing it.  Has anyone else run into this issue?

**Comment by cj** [comment]
It seems as though it needs extra width on the right, because as you move the cursor to the right the text moves, but the icons stay still.

**Comment by cj** [comment]
Seems to be an issue with `konsole`.

**Comment by ryanoasis** [comment]
@cj If you disable vim-devicons does the problem still occur in konsole ?

**Comment by cj** [comment]
@ryanoasis I think it is an issue with konsole.  Closing this for now.

**Comment by ryanoasis** [comment]
@cj Good idea. Thanks for the follow-up
