### ISSUE TITLE
nerdtree, when press "up a dir", the folder icon missing

### ISSUE THREAD

**Issue by wuqiong4945** [ryanoasis/vim-devicons#189]
system : ubuntu 16.04
vim version : 7.4

![screenshot from 2017-01-02 22-52-45](https://cloud.githubusercontent.com/assets/1294412/21591516/e3330de2-d13f-11e6-919f-86ad8a9e41c2.png)

**Comment by ryanoasis** [comment]
Thanks for the report. I'll take a look

**Comment by ryanoasis** [comment]
@wuqiong4945 Sorry for the long delay. 

I am not able to replicate the issue. Do you still have the issue with the latest version?

Which keymap is this? `u` or `U` or something else?

**Comment by ryanoasis** [comment]
@wuqiong4945 Ah okay now I see it. It is with <kbd>U</kbd> (uppercase U)

**Comment by slabua** [comment]
I have encountered this bug, initially in a different way but I also tried by pressing `u` and it still happens.
Here are the steps that reproduced the issue for me:
1. Navigate inside a folder by pressing `e`
2. Move up entering the parent folder `../` with `<CR>`

![peek 2018-01-14 16-40-slowed](https://user-images.githubusercontent.com/1002978/34917825-7ec4a804-f94b-11e7-9ec5-e8c8ddd336d4.gif)

**Comment by slabua** [comment]
I have also noticed that the behaviour is different depending on whether `let g:DevIconsEnableFoldersOpenClose` is set to 0 or 1.
In my recording above, I have set it to 1. When the issue occurs, the icon gets fixed by cycling open/close status for the particular folder. If it's set to 0, instead, cycling open/close the folder doesn't fix the appearance.

**Comment by OliverLew** [comment]
@ryanoasis I am having this problem even now.
Reproducible just by
1. start vim in a folder
2. toggle nerdtree and
3. press 'u'/'U'

The only happens the first time I go to the parent dir, e.g. press 'u' when first time open nerdtree or after I jump to a bookmark.

Tested with a minimal .vimrc below and on Archlinux, urxvt, vim 8.1, Hack nerdfont and plugins fresh installed.

![Screenshot_2019-11-17_15-35-42](https://user-images.githubusercontent.com/12032219/69004666-32a71380-0952-11ea-8cdc-8082c8b7987e.png)
![Screenshot_2019-11-17_15-35-52](https://user-images.githubusercontent.com/12032219/69004668-363a9a80-0952-11ea-9bb1-e6816cc20d5c.png)

`.vimrc`:
```vim
call plug#begin('~/.vim/bundle')
Plug 'scrooloose/nerdtree'
Plug 'ryanoasis/vim-devicons'
call plug#end()
```

**Comment by kazukazuinaina** [comment]
@OliverLew 

Thanks!
I have confirmed that this problem reproduces.
I will investigate this issue.

**Comment by agschipor** [comment]
I have the same problem, too.
