### ISSUE TITLE
No Icons shown in vimfiler explorer mode when listchars set

### ISSUE THREAD

**Issue by Jeansen** [ryanoasis/vim-devicons#192]
I have the following in my .vimrc:
`"set listchars=nbsp:·,trail:·,precedes:«,extends:»,eol:↲,tab:◄-`
With this, I do not see the icons in VimFilerExplorer. They are overlapped by `»`. Removing the extends part from my listchars string solves this. Maybe it would be better to introduce a margin?

**Comment by ryanoasis** [comment]
Thanks for the report. I will test this out

**Comment by ryanoasis** [comment]
@Jeansen Sorry for the long delay. On a very quick check I am not seeing an issue.

Is this on gvim or terminal vim?
Which font?
Can you show a screenshot?

**Comment by Jeansen** [comment]
Just checked. Seems to be working  ...... Thanks for getting back to me, anyway! :)
