### ISSUE TITLE
Nerdtree-git-plugin update adds ignored status, but icon seems missing

### ISSUE THREAD

**Issue by ismay** [ryanoasis/vim-devicons#193]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)

- [x] What **version** of vim are you using?
```
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20170218-86441-v9u4vo/neovim-0.1.7/build/config -I/tmp/neovim-20170218-86441-v9u4vo/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170218-86441-v9u4vo/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20170218-86441-v9u4vo/neovim-0.1.7/build/include
Compiled by ismay@macbook.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"
```
- [x] What **version** of vim-devicons are you using?
0.8.5
- [x] Are you using vim from the terminal or a GUI vim?
iTerm2 neovim
- [x] Are you using Mac, Linux or Windows?
macos Sierra 10.12.3

So nerdtree-git-plugin was [just updated](https://github.com/Xuyuanp/nerdtree-git-plugin/pull/46#event-968784048). The update works fine, and together with vim-devicons shows whether files/folders are ignored (with a proper nerdfont):

<img width="263" alt="screen shot 2017-02-20 at 13 41 04" src="https://cloud.githubusercontent.com/assets/7355199/23125801/d87a3114-f773-11e6-9aa0-cbc632b19eaa.png">

However the icon seems to be missing. Would be nice to show an appropriate icon here. The setup that I used to generate the screenshot above can be found here: https://github.com/ismay/dotfiles

**Comment by ryanoasis** [comment]
> ignored status
That's cool.

I wonder what the default char was. I will look into this. Perhaps you can set it to a custom codepoint?
Perhaps there is a standard glyph here that Nerd Fonts is missing.

**Comment by ismay** [comment]
> Perhaps you can set it to a custom codepoint?

How would I do that?

**Comment by ryanoasis** [comment]
Actually it _looks_ like that _is_ the correct character it just looks like a missing default :stuck_out_tongue: 

Mine looks a bit different but essentially the same:

![selection_001](https://cloud.githubusercontent.com/assets/8083459/23128083/84509696-f74b-11e6-8f73-2e90df188e63.png)

Looks like you can change the default codepoints used with: `g:NERDTreeIndicatorMapCustom`

**Comment by ismay** [comment]
Ah ok. So what would the config for `g:NERDTreeIndicatorMapCustom` look like in this case?

**Comment by ryanoasis** [comment]
I got it from the repo and changed it slightly (but having trouble testing):

```vim
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ 'Ignored'   : '⛌',
    \ "Unknown"   : "?"
    \ }
```

**Comment by ismay** [comment]
So it seems that the icon is supposed to look like that for the font I'm using:

![screen shot 2017-02-24 at 10 22 29](https://cloud.githubusercontent.com/assets/7355199/23297791/2bc3f882-fa7b-11e6-8c02-9d4bd631c157.png)

Seems to be working fine. Was just that the appearance of the icon made me think that something was missing.

**Comment by ryanoasis** [comment]
Yep looks like that's how it is supposed to look. Thanks for the update. Closing this.
