### ISSUE TITLE
Folder icons bug

### ISSUE THREAD

**Issue by ismay** [ryanoasis/vim-devicons#194]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)

- [x] What **version** of vim are you using?
```
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20170218-86441-v9u4vo/neovim-0.1.7/build/config -I/tmp/neovim-20170218-86441-v9u4vo/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170218-86441-v9u4vo/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20170218-86441-v9u4vo/neovim-0.1.7/build/include
Compiled by ismay@macbook.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"
```
- [x] What **version** of vim-devicons are you using?
0.8.5
- [x] Are you using vim from the terminal or a GUI vim?
iTerm2 neovim
- [x] Are you using Mac, Linux or Windows?
macos Sierra 10.12.3

When using the folder open/close icons:

```
  let g:WebDevIconsUnicodeDecorateFolderNodes = 1
  let g:DevIconsEnableFoldersOpenClose = 1
```

They don't always work as expected.

1. The top folder icon doesn't open/close:

<img width="265" alt="screen shot 2017-02-20 at 14 21 40" src="https://cloud.githubusercontent.com/assets/7355199/23126624/f0b8f400-f777-11e6-880b-9e0409e6484a.png">

But ones below do:

<img width="250" alt="screen shot 2017-02-20 at 14 22 36" src="https://cloud.githubusercontent.com/assets/7355199/23126638/091cc31e-f778-11e6-9b20-c6eced4098eb.png">

2. When closing a node with the `close parent of node` command the icon doesn't respond:

<img width="251" alt="screen shot 2017-02-20 at 14 23 19" src="https://cloud.githubusercontent.com/assets/7355199/23126672/3226b4ea-f778-11e6-89eb-78194fe8a046.png">

But it does when you close the folder with `open & close node` command

**Comment by ryanoasis** [comment]
for **2** I was able to replicate and good catch thanks :smile: 

---

for **1** I was not able to replicate but don't doubt you saw that. can you provide more info or steps?
I tried to make a directory structure similar to yours (folder with only have a folder and then some files) but could not identify a pattern to reproduce

**Comment by ismay** [comment]
For 1 I did some more testing. It actually doesn't have anything to do with being the top node. Steps to recreate (for me):

1. Create folder that contains only another folder (which contains a file): `level-1/level-2/a-file.txt`
2. Open folder with `open & close node` command
3. Icon does not respond

Now if you close and open again it _will_ respond. It can be fixed by putting a file in folder `level-1`. So apparently it has to do with that folder only containing a folder. I could recreate this with the same folder structure at any place in the file tree (so not only at the root but also at lower levels).

**Comment by ismay** [comment]
![screen shot 2017-02-24 at 10 14 45](https://cloud.githubusercontent.com/assets/7355199/23297510/1a7406f4-fa7a-11e6-85e1-3e126b50d006.png)

**Comment by ryanoasis** [comment]
It took longer than I thought but I have a working solution that is not too bad :smile:

**Comment by ryanoasis** [comment]
I wasn't able to record but I have a screenshot that shows the results of `O` keypress (Recursively open the selected directory):

![selection_001](https://cloud.githubusercontent.com/assets/8083459/25777322/0d2fe11e-32a8-11e7-8579-424da0621672.png)

**Comment by ismay** [comment]
Ah nice! One thing still remains for me: when closing a folder with `close parent of node` the icon still doesn't seem to respond.

**Comment by ryanoasis** [comment]
Yep correct. I was able to just finish fixing those as well: `x` (Closes the parent of the selected node.) and `X` (Recursively closes all children of the selected directory.)

**Comment by ismay** [comment]
Ah nice!

**Comment by ryanoasis** [comment]
I am going to release this in a few hours :package: , if you would _like_ to help test the [`0.9.1` branch](https://github.com/ryanoasis/vim-devicons/tree/0.9.1)  is up. Thanks

**Comment by ismay** [comment]
Did some testing (the changes should be in master now right?), this is what I found:

1. The top folder icon doesn't open/close: folder icon doesn't open on first open, but after that it opens/closes correctly (when opening/closing with `NERDTreeMapActivateNode`). So no change here.

<img width="228" alt="screen shot 2017-05-08 at 12 52 39" src="https://cloud.githubusercontent.com/assets/7355199/25801304/464de69e-33ed-11e7-902b-3b40e9d9e248.png">

<img width="260" alt="screen shot 2017-05-08 at 12 52 47" src="https://cloud.githubusercontent.com/assets/7355199/25801315/4ed0cb9c-33ed-11e7-883d-f449eda9e4d7.png">

2. Has been fixed.

Hope this helps. Thanks for the updates!

**Comment by ryanoasis** [comment]
Ah okay I must have missed that in my haste. Yes master has the latest.

Thanks for testing! :smile:

**Comment by ismay** [comment]
No problem, happy to help 👍 Let me know when more testing needs to be done!

**Comment by ryanoasis** [comment]
@ismay Hmm I still didn't quite get the issue, how do you replicate it? I am not seeing it :blush: Thanks

**Comment by ismay** [comment]
My dotfiles are here: https://github.com/ismay/dotfiles I don't know if that's too much, but with those (and in that repo), you can trigger the bug by opening vim and then nerdtree, and opening the first node by pressing <kbd>l</kbd>. Note that it only happens for folders contained in a folder with files.

Hope that helps!

**Comment by ryanoasis** [comment]
@ismay Thanks for the details. Looks like you remapped `o` to be `l`. Ah okay now I see the pattern that you mentioned:

![selection_002](https://cloud.githubusercontent.com/assets/8083459/25924139/337ab27c-35af-11e7-999d-aa207ebba172.png)

**Comment by ryanoasis** [comment]
Not ideal but a workaround for this would be to set:
```vim
let NERDTreeCascadeSingleChildDir=0
```

At least until we have a fix (working on it!)

**Comment by ryanoasis** [comment]
This has been fixed! 😄
