### ISSUE TITLE
Add support for .tex, .r and .rmd files.

### ISSUE THREAD

**Issue by qifei9** [ryanoasis/vim-devicons#195]
I am not sure whether this is the right place to ask for it. However it would be wonderful if this plugin could support `.tex` (latex), `.r` (R language) and `.rmd` (rmarkdown) filetypes.

For `.rmd` file, it could be the same icon as `markdown` file.
For `.tex` and `.r` files, I see icons in file-icons font https://github.com/file-icons/source/blob/master/charmap.md.

**Comment by ryanoasis** [comment]
Sure actually this us a good place. Nice I don't think I knew about this font. I can try to add it to [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts)

**Comment by petobens** [comment]
+1 ! It would be awesome to add this font to Nerd Fonts

**Comment by ryanoasis** [comment]
@qifei9 , @petobens 
Unfortunately going to push this off it will require updates to Nerd Fonts and I just cannot find suitable glyphs for these in the current offering.

I am trying to get v0.9.0 out the door :package:

**Comment by michaelquinn32** [comment]
Font-awesome just added support for R. I know that you have plenty on your plate, but how long does it normally take for FA upgrades to appear here?
https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md#5011----2018-05-01

Thanks for all of your work!

**Comment by ryanoasis** [comment]
@michaelquinn32 Ah okay nice. So Nerd Fonts is currently on 4.7.0 (hasn't made the jump to 5.x yet). There is discussion whether or not to make FA 5 the default or switch to Font Awesome Extension.

> I know that you have plenty on your plate

Thanks for the understanding. :smile: 

Relevant tickets: 
https://github.com/ryanoasis/nerd-fonts/issues/221
https://github.com/ryanoasis/nerd-fonts/issues/241

**Comment by michaelquinn32** [comment]
Great! Thanks for everything that you've been working on. It's all much appreciated.

**Comment by vando026** [comment]
Hi Just following up on this thread. If anyone wants to use the r glyph for the .r filetype (and dont want to wait for the upgrade to FA5), you can:

source ~/.local/share/fonts/i_material.sh
echo $i_mdi_language_r
# ﳒ
and copy the output from the terminal or open material.sh in gvim and copy the glyph (from line 2009) and then paste it into the following configuration 

let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {} " needed
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['r'] = 'ﳒ'

which you can put in your vimrc. This works for me with Vim 8.1 and Ubuntu 18.04.

**Comment by alexhallam** [comment]
I think `.Rproj` files could use an icon also. `i_mdi_vector_rectangle` seemed sensible. 

let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['rproj'] = '鉶'

**Comment by andregpss** [comment]
Is there a latex/tex icon already? I just installed devicons and `.tex` files shows the default icon.

**Comment by ryanoasis** [comment]
## proposal:

latex (.tex):
![Selection_036](https://user-images.githubusercontent.com/8083459/79009400-33fcf680-7b14-11ea-8802-484e8ab79246.png)
_I think this actually looks better than say vscode's latex icon (TeX)_

.r:
![Selection_038](https://user-images.githubusercontent.com/8083459/79009420-3d865e80-7b14-11ea-96eb-b53a783b4779.png)

.Rproj:
![Selection_037](https://user-images.githubusercontent.com/8083459/79009406-38291400-7b14-11ea-8219-e28b504e87da.png)

**Comment by kazukazuinaina** [comment]
@ryanoasis 
I think this proposal is looked good to me.

**Comment by sadtab** [comment]
Hi @ryanoasis , I think I just found a bug in NERDTree with devicons, I think its related to this issue. Every file with TeX icon flip to the right of screen

![image](https://user-images.githubusercontent.com/25584481/90785970-4a596100-e303-11ea-85ed-d3921468f65f.png)

But if i change the extention every thing goes back to normal :

![image](https://user-images.githubusercontent.com/25584481/90786101-77a60f00-e303-11ea-9bf3-6aefecaf2dea.png)
