### ISSUE TITLE
Support .zsh, .ksh., .bash, etc. shell script extensions

### ISSUE THREAD

**Issue by chauncey-garrett** [ryanoasis/vim-devicons#196]
I see that `.sh` and `.fish` are [already supported](https://github.com/ryanoasis/vim-devicons/blob/93387d7fba06f8ba7ee52dc00d08919f8a35341d/plugin/webdevicons.vim#L230-L231). Please add support for other shell script extensions as well.

**Comment by ryanoasis** [comment]
Yes correct. good suggestion. thanks :+1:

**Comment by ryanoasis** [comment]
For now I am adding these:

`bash`, `zsh`, `ksh`, `csh`, `awk`, `ps1`

**Comment by ryanoasis** [comment]
Release in v0.9.0

**Comment by chauncey-garrett** [comment]
@ryanoasis Thank you!

**Comment by ryanoasis** [comment]
Sure no problem :smile:
