### ISSUE TITLE
Folder titles off by a single space after opening

### ISSUE THREAD

**Issue by ismay** [ryanoasis/vim-devicons#197]
Sorry for spamming you with issues, but I couldn't find this in the faq or other issues. With the following settings:

```
  let g:WebDevIconsUnicodeDecorateFolderNodes = 1
  let g:DevIconsEnableFoldersOpenClose = 1
```

When opening a folder, the titles of the opened folder move to the left a single space (scripts and tmux folders):

![image](https://cloud.githubusercontent.com/assets/7355199/23298457/182138aa-fa7e-11e6-95f6-ce96fda7febc.png)

I'm assuming that's a bug? My setup is the same as in the previous issue, I can copy it over if you'd like. Let me know if you need more info.

**Comment by ryanoasis** [comment]
> Sorry for spamming you with issues

No worries! :smile: 

Interesting issue. This is enough info for now I will try to replicate this weekend :sweat_smile:

**Comment by ryanoasis** [comment]
I think I have found the issue. We can target this for the next release. Thanks again :smile:

**Comment by ismay** [comment]
Cool np, looking forward to it! 👍

**Comment by XadillaX** [comment]
This PR hurts me.

before:

![](https://cloud.githubusercontent.com/assets/2842176/26519771/a59ed238-42f8-11e7-99c3-27c4161e2eb5.png)

after:

![](https://cloud.githubusercontent.com/assets/2842176/26519773/b61f1c58-42f8-11e7-9911-f64bd82d5af1.png)

**Comment by ryanoasis** [comment]
@XadillaX Ouchie! :blush: :cry: sorry about that...

Can you tell us your `vimrc` settings for vimdevicons, or are you using all default settings?

**Comment by v45k0** [comment]
Hey @ryanoasis,
I have the same problem as @XadillaX - this patch causes a regression for me. Just updated vim-devicons from v0.8.6 to the latest v0.9.2

I am using the following version of gvim:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
```

Custom settings applied for devicons:
```
let g:webdevicons_enable_nerdtree = 1
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:WebDevIconsNerdTreeAfterGlyphPadding = ''
let g:WebDevIconsNerdTreeGitPluginForceVAlign = 1
let g:DevIconsEnableFoldersOpenClose = 1
let g:DevIconsEnableFolderExtensionPatternMatching = 1
```
 
I traced down the problem to the following line: https://github.com/ryanoasis/vim-devicons/blob/master/plugin/webdevicons.vim#L748 on the latest version.
Is there any particular reason why the function is called with a disabled artifact fix? 
When the flag is enabled the plugin applies the correct paddings/fixes as expected.   
 
@ryanoasis Let me know if I should submit the pull request with the fix.

**Comment by ryanoasis** [comment]
Really sorry about the delays people. Hopefully we can straighten things out next release :crossed_fingers:

**Comment by ryanoasis** [comment]
Plan of action here: https://github.com/ryanoasis/vim-devicons/issues/225#issuecomment-360335841
