### ISSUE TITLE
Icons show as question marks

### ISSUE THREAD

**Issue by pdoak** [ryanoasis/vim-devicons#198]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)

- [x] What **version** of vim are you using?
  `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 22 2017 05:25:57)
MacOS X (unix) version
Included patches: 1-211
Compiled by Homebrew
`
- [x] What **version** of vim-devicons are you using?
`0.8.5`
- [x] Are you using vim from the terminal or a GUI vim?
`Terminal`
- [x] Are you using Mac, Lin

#### Optional Info

- [x] Provide **screenshots** where appropriate
![image](https://cloud.githubusercontent.com/assets/1565586/23300058/d876415c-fa7b-11e6-98c5-15c6874b9d85.png)
![image](https://cloud.githubusercontent.com/assets/1565586/23300245/9b512ae8-fa7c-11e6-9812-0c6d7c99ca37.png)

- iTerm: Build 3.1.20170221-nightly

My vimrc has `encoding=utf-8` and vim-devicons is loaded after vim-airline.

Any thoughts as to why this is not working?

**Comment by ryanoasis** [comment]
Hey @pdoak what font are you using?

for more steps please follow these steps to see if they are helpful to you: https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting#not-working-general (Just updated!)

**Comment by ArtStepanyuk** [comment]
I'm having the same issue on Mac on linux works fine

**Comment by pdoak** [comment]
I've solved the problem. It was a problem with the font.

**Comment by ryanoasis** [comment]
Thanks for the update @pdoak 

@ArtStepanyuk and @AntonRatnick can you tell me which fonts you are using and if you still have the issue?

**Comment by AntonRatnick** [comment]
I use ITerm2 on my mac. Problem solved.  
I just set in iterm preferences right ASCII font.

**Comment by ryanoasis** [comment]
Thanks for the updates. I'm considering this closed for now

**Comment by rwpino** [comment]
Hi, I read the FAQ, when I run echo `g:WebDevIconsUnicodeDecorateFileNodesDefaultSymbol ` the result is  (question mark inside a square), any ideas, I m running iterm2 on mac sierra 10.12.4

**Comment by gHashTag** [comment]
@AntonRatnick Tell me how you solved the problem, I have Mac, iTerm2 and NeoVim

1. Step:
```
brew tap caskroom/fonts
brew cask install font-hack-nerd-font
```
2. Step: Config in .vimrc
```
set encoding=utf8
let g:airline_powerline_fonts = 1
```
3. Step:
![2017-10-23 22 23 32](https://user-images.githubusercontent.com/6774813/31908850-dbb55adc-b840-11e7-8570-8be3c95e4f6d.png)

**Comment by ryanoasis** [comment]
@gHashTag Hey it looks like you are not using a [Nerd Font](https://github.com/nerd-fonts). That is required for vimdevicons to work "out of the box". It looks to me like you are only using a Powerline font

**Comment by gHashTag** [comment]
@ryanoasis Thanks for the quick response. Does not this command put a font? 
```
brew tap caskroom/fonts
brew cask install font-hack-nerd-font
```
How to solve this problem?

**Comment by ryanoasis** [comment]
@gHashTag Hey sorry I did miss that part of your comment, however from your last screen shot the hack nerd font you downloaded with brew cask is not selected as your font. Is it available to be selected in the 'change font' ?

**Comment by gHashTag** [comment]
@ryanoasis It is he?
![2017-10-24 15 13 48](https://user-images.githubusercontent.com/6774813/31942479-0f68e096-b8ce-11e7-8a92-04b67a643d71.png)

**Comment by gHashTag** [comment]
@ryanoasis have ideas how to solve the error?

**Comment by gHashTag** [comment]
Thanks. Everything is working. It was necessary to choose this font in iTerm2:
![2017-10-26 22 21 18](https://user-images.githubusercontent.com/6774813/32072687-2623da6e-ba9c-11e7-870d-bff70734d864.png)

**Comment by wlisrausr** [comment]
Hi @ryanoasis, I've this same problem right now. I already installed the NerdFont using Brew, but it seems I can't find any fonts that related to `Nerd` in my iTerm preferences. Am I missing something in here?

**Comment by wlisrausr** [comment]
Never mind, I found it. Thanks @ryanoasis

**Comment by kitaev-chen** [comment]
> @ryanoasis Thanks for the quick response. Does not this command put a font?
> 
> ```
> brew tap caskroom/fonts
> brew cask install font-hack-nerd-font
> ```
> How to solve this problem?

I'm using mac to connect remote linux, it doesn't work after I installed fonts on remote linux, but after installed fonts on mac and do:
`fc-cache -f -v`
then choose hack-nerd-font, it finally works!

**Comment by ryan-stanley** [comment]
we might also need to set the encoding to utf-8 in the vimrc file.
```
set encoding=utf-8
``` 
 -> https://github.com/vim-airline/vim-airline/issues/142#issuecomment-22717382

**Comment by nag-anoop** [comment]
@ryanoasis man you are crazily awesome!!!!! Thanks your input helped me to get what I wanted.

**Comment by dalu98** [comment]
Hi, I want to know does this plugin only support font that patched glyphs?

It seems like this plugin will not work when I was not using nerd font.

**Comment by xxidbr9** [comment]
> @AntonRatnick Tell me how you solved the problem, I have Mac, iTerm2 and NeoVim
> 
> 1. Step:
> 
> ```
> brew tap caskroom/fonts
> brew cask install font-hack-nerd-font
> ```
> 
> 2. Step: Config in .vimrc
> 
> ```
> set encoding=utf8
> let g:airline_powerline_fonts = 1
> ```
> 
> 3. Step:
>    ![2017-10-23 22 23 32](https://user-images.githubusercontent.com/6774813/31908850-dbb55adc-b840-11e7-8570-8be3c95e4f6d.png)

### FWI



```bash
brew tap homebrew/cask-fonts
brew install font-hack-nerd-font
```
##### My Config 
<img width="1178" alt="Jepretan Layar 2022-01-29 pukul 00 26 12" src="https://user-images.githubusercontent.com/51733515/151593448-5ae30891-9405-47dd-a9fe-9096161acd24.png">

**Comment by loeschg** [comment]
Some updated commands for those visiting these days:

```
brew tap homebrew/cask-fonts
brew install font-hack-nerd-font --cask
```

**Comment by qlixes** [comment]
> 

these works on M1 Pro with OS Ventura

**Comment by devlopersabbir** [comment]
# I'm also facing this issue with my Mac.
![image](https://user-images.githubusercontent.com/82939905/236501740-7df8e814-169e-469f-912b-28370b57a672.png)
I have solved the file question mark issue but I haven't fixed `the folder` question mark issue.
> As we can see here is my screenshot.
![image](https://user-images.githubusercontent.com/82939905/236502508-ffdebbc4-cbd2-49b5-a978-ed739f360afa.png)

**Comment by jacint-mihaly-david** [comment]
Turning off the option underlined with red did the trick for me. Still seeing an extra question mark before the icon though 🤷‍♂️ 
Also check your lua config as I accidentally copied an override with the question mark symbol 🤷‍♂️ 

<img width="1074" alt="Screenshot 2023-07-08 at 16 54 28" src="https://github.com/ryanoasis/vim-devicons/assets/107406590/b4748983-6f40-4854-92f4-ce96ab6f5e35">
