### ISSUE TITLE
colorize ctrlP icons

### ISSUE THREAD

**Issue by divramod** [ryanoasis/vim-devicons#201]
hey, thx for the great work!

i want to ask if it is possible to color the icons shown in ctrlp?

**Comment by ryanoasis** [comment]
@divramod Thanks I really appreciate that! :smile: 

It is possible but I think this suggested change would make it a lot easier: https://github.com/ctrlpvim/ctrlp.vim/pull/316

I know you are asking specifically about ctrlp but if you use NERDTree you'd like this: https://github.com/tiagofumo/vim-nerdtree-syntax-highlight

---

@HerringtonDarkholme any thoughts?

cc @tiagofumo (just in case you had some thoughts :smile:)

**Comment by tiagofumo** [comment]
I didn't even know that icons show up in ctrlp, because mine don't. I tried configuring it just now, to see if I could make it to work, but I couldn't. My guess is that doing something similar to what I did for NERDTree is going to cause a lot of lag, given that I already have some complaints about lag on my plugin.

**Comment by ryanoasis** [comment]
@tiagofumo Oh you can't see the icons in ctrlp? Can I ask what mode you are in? They _should_ show up in mru or file mode (not buffer currently -- that was breaking ctrlp integration).

---

:laughing: Love right back to ya! :smile: No worries here from my side, I am pretty chill and but I have learned that a lot of people on GitHub (or online in general) are... how you say very _direct_.

**Comment by divramod** [comment]
thx for the feedback guys. i have the colouring already running for nerdtree and it looks awesome.
so as it looks like we have to wait for the landing of https://github.com/ctrlpvim/ctrlp.vim/pull/316
But the pull request is already 6 month old ;-/

**Comment by her** [comment]
@divramod since this https://github.com/ctrlpvim/ctrlp.vim/pull/316 has been merged, is it working for you now?

**Comment by HerringtonDarkholme** [comment]
This can be done by adding `syntax/ctrlp.vim` to runtime path. I don't have time for OSS for a while so I hope I can find syntax file I created years ago...

**Comment by reportaman** [comment]
@her Yes it works, I confirm! @ryanoasis This ticket should be closed probably be closed. For those looking for how to use coloring, please add filetype "ctrlp" in the auto command filetype list for answers on this thread: https://github.com/ryanoasis/vim-devicons/issues/158

**Comment by kalindu1** [comment]
> I didn't even know that icons show up in ctrlp, because mine don't. I tried configuring it just now, to see if I could make it to work, but I couldn't. My guess is that doing something similar to what I did for NERDTree is going to cause a lot of lag, given that I already have some complaints about lag on my plugin.
> 
> PS: I love you @ryanoasis, lol. Sometimes I get worried about "sounding" rude to people that are cool to me, so I just want to point that out hahaha. #jokes

Laod the CtrlP plugin before vim-devicons.

**Comment by divramod** [comment]
thx!
