### ISSUE TITLE
Mac/Win instructions tweak

### ISSUE THREAD

**Issue by Taverius** [ryanoasis/vim-devicons#208]
You can use `_` instead of `\<space>` in `set guifont=`.

#justthesmallthings

**Comment by ryanoasis** [comment]
@Taverius Thanks! I did not know this :smile: 

```
A '_' can be used in the place of a space, so you don't need to use
	  backslashes to escape the spaces.
```

Would you like to open a Pull Request? If not I will make the change but it will be in a few days at the earliest..
