### ISSUE TITLE
conceal_nerdtree_brackets seemingly not working

### ISSUE THREAD

**Issue by rijkvanzanten** [ryanoasis/vim-devicons#209]
I just did a fresh install of the plugin and can't get the `webdevicons_conceal_nerdtree_brackets` option to work. 

#### Required Info
- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)

_What **version** of vim are you using?_
VIM - Vi IMproved 7.4

_What **version** of vim-devicons are you using?_
0.9.2

_Are you using vim from the terminal or a GUI vim?_
Terminal. Specifically iTerm2 3.0.15

_Are you using Mac, Linux or Windows?_
MacOS Sierra 10.12.5

#### Optional Info
I'm using PragmataPro as font, patched with [nerd-fonts patcher](https://github.com/ryanoasis/nerd-fonts)

<img width="316" alt="screen shot 2017-06-04 at 22 28 34" src="https://cloud.githubusercontent.com/assets/9141017/26765105/2a3e70ac-4975-11e7-9ce1-07fb6a9c3dc0.png">

My full `.vimrc`:
```
" Set detection indentation and plugin
filetype plugin indent on

" Enable line-numbers
set nu

" Enable syntax-highlighting
syntax on

" Enable automatic indentation
set autoindent

" Set onedark colorscheme
colorscheme onedark

highlight Normal ctermbg=NONE

" Activate pathogen plugins
execute pathogen#infect()

" Setup NERDTree
map <C-n> :NERDTreeToggle<CR>

" Setup Syntastic
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['xo']
let g:syntastic_ignore_files = ['node_modules']
let g:syntastic_mode_map = { 'mode': 'passive' }
nmap <leader>sc :SyntasticCheck<CR>

" Set ~/.vim/swapfiles as .swp location
:set directory=$HOME/.vim/swapfiles//

" Config devicons
set guifont=PragmataPro\ NERD\ Font\ Complete:h12
set encoding=utf-8

let g:WebDevIconsUnicodeGlyphDoubleWidth = 0
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:DevIconsEnableFoldersOpenClose = 1

let g:webdevicons_conceal_nerdtree_brackets = 1
```

Do I have made a mistake in configuring this plugin, or is it a bug?

Either way; amazing work on vim-devicons and your other plugins :)

**Comment by UFOwl** [comment]
I have a similar problem. I set `ambiwidth=double` in vimrc file, and find there is an extra space after each file icon while no space after folder icon.
![image](https://user-images.githubusercontent.com/6611701/27115650-b22253cc-50fe-11e7-949b-fc312cf9d649.png)

**Comment by ryanoasis** [comment]
@rijkvanzanten Thanks for the report. I assume you still are having the problem?

I don't see anything wrong with your configuration.

Can you see what value is being set for `conceallevel` when in the nerdtree buffer? i.e. `set conceallevel?`

For me it gives: `conceallevel=3`

You said this is your full vimrc? Can you list what other vim plugins you are using?

The only thing I can see right now is some other plugin conflicting with this conceal setting.

> Either way; amazing work on vim-devicons and your other plugins :)

Hey thanks I really appreciate the kind words :heart: :smile:

**Comment by rijkvanzanten** [comment]
I started completely over with everything Vim related and switched from Pathogen to Vundle. It works immediately. Not sure what caused it the previous time.. 

The above `.vimrc` was my complete one indeed. My new full `.vimrc` is over at: https://github.com/rijkvanzanten/dotfiles/blob/master/.vimrc if you want to debug some more
