### ISSUE TITLE
Add Support for Rust .rs files

### ISSUE THREAD

**Issue by fungl164** [ryanoasis/vim-devicons#212]
It would be great to see the proper icon show up for Rust files.  The current one is an eyesore.  
<br>Thanks for this great plugin!

Rust Icon: http://vorillaz.github.io/devicons/#/singleicon/rust

**Comment by ryanoasis** [comment]
Hey @fungl164 thanks for the kind words! :smile: 

So the thing is the current one _is_ the rust glyph from vorillaz's devicons, it is just that Nerd Fonts has shifted it from it's original codepont of `e6a8` to `e7a8`

![selection_001](https://user-images.githubusercontent.com/8083459/32027826-3ac30384-b9b9-11e7-9c0f-b7beac383025.png)

**Comment by fungl164** [comment]
Interesting...I'm just noticed I was using the Code New Roman Nerd Font which has this issue.  Some other Nerd Fonts don't...though the icon looks super small.  Thank you for the reply.  Is there a way to manually control the icon via a configuration option? Thnxs!

**Comment by ryanoasis** [comment]
Hmm so some Nerd Fonts look okay and some don't? Can you elaborate or provide a screenshot?

> Thank you for the reply

No worries

> Is there a way to manually control the icon via a configuration option?

Sorry, no, not at the moment. You could try the `--adjust-line-height` option but I doubt it will help.

**Comment by fungl164** [comment]
Hi, sorry for the delay.  Been extremely busy lately...

Anyway, here is a screenshot with Code New Roman Nerd Font as you requested:
<img width="191" alt="screen shot 2017-10-26 at 5 31 46 pm" src="https://user-images.githubusercontent.com/1827730/32417080-d02e2bcc-c221-11e7-930e-88cb6fefefe8.png">

From the looks of it, .rs files get the ionic icon assigned...thnxs for looking into this!

**Comment by ryanoasis** [comment]
@fungl164 Thanks for the screenshot! :+1:

**Comment by ryanoasis** [comment]
Can you try updating your font? This shouldn't be using that glyph.

executing `ga` over the glyph should yield `e7a8`:

![selection_017](https://user-images.githubusercontent.com/8083459/37246803-5f9f7b94-247e-11e8-9f88-236b771cef2b.png)

**Comment by fungl164** [comment]
Hi, downloaded this: 
```https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/CodeNewRoman/complete/Code%20New%20Roman%20Nerd%20Font%20Complete.otf```

and now see this:
<img width="583" alt="screen shot 2018-03-11 at 10 50 41 am" src="https://user-images.githubusercontent.com/1827730/37254853-155fd03c-251a-11e8-803e-3e7f7b99af64.png">

Just FYI, I am using neovim v0.2.2 on iTerm2 OSX (High Sierra)

Should I be using a different file for this font?  Many thnxs!

**Comment by ryanoasis** [comment]
@fungl164 That's very strange, I'll take a look when I can

**Comment by ryanoasis** [comment]
@fungl164 did you ever find a solution to this? I wasn't able to look into it myself.

Trying to follow-up on old issues.

**Comment by kazukazuinaina** [comment]
Try updating vim-devicons to the latest version. At the very least, I've found that the rust icon looks fine in many environments. This issue will not be answered for a long time, so I will close it.
If you have any problems, please feel free to restart or create a new issue, thanks!
