### ISSUE TITLE
No module named vim_devicons.powerline.segments

### ISSUE THREAD

**Issue by anoopd** [ryanoasis/vim-devicons#214]
I was trying to install devicons with powerline  ........ but i am getting the error 

ImportError: Failed to obtain segment function

Can somebody help me  .............  

powerline-lint is giving me  ......... 

Error while checking segments (key /segments/right/list item 0/function)
  in "/Users/anoopd/.config/powerline/themes/vim/default.json", line 88, column 62:
     ... vim_devicons.powerline.segments.webdevicons_file_format",
                                         ^
failed to import module vim_devicons.powerline.segments
  in "/Users/anoopd/.config/powerline/themes/vim/default.json", line 88, column 30:
                    "function": "vim_devicons.powerline.segments. ...
                                 ^

Error while checking segments (key /segments/left/list item 1/function)
  in "/Users/anoopd/.config/powerline/themes/vim/default.json", line 9, column 62:
     ... vim_devicons.powerline.segments.webdevicons",
                                         ^
failed to import module vim_devicons.powerline.segments
  in "/Users/anoopd/.config/powerline/themes/vim/default.json", line 9, column 30:
                    "function": "vim_devicons.powerline.segments. ...

**Comment by delphinus** [comment]
Vim recognizes Python modules by adding special paths to `sys.path`.  So the module `vim_devicons` can use only in Vim, and it is valid that `powerline-lint` claims those errors.

What did you write to your `.vimrc`?  Then I can advice, maybe.

**Comment by anoopd** [comment]
hi delphinus ,
                          Thank you so much for your reply , I haven't added anything to my `.vimrc`  . It just worked well with Nerdtree . Using iTerm2 , Powerline and has my vim configured for powerline .  After getting it working with Nerdtree , I tried to add the segments to `~/.config/powerline/themes/vim/default.json`   as in your example `https://raw.githubusercontent.com/wiki/ryanoasis/vim-devicons/samples/v0.8.x/powerline/themes/vim/default.json`   ..........  The instructions say " file type segment " and add
 `{
	"function": "vim_devicons.powerline.segments.webdevicons",
	"priority": 10,
	"draw_soft_divider": false,
	"after": "  "
}`

I am a bit confused about where to add this , in your example file you have just added it , and i am getting the above error when i try this that way  ....... i am not sure about how to do it in " file type segment "  , should i remove the file_type segment completely and replace it with the above ?

**Comment by anoopd** [comment]
get
    contents, _contents_func, module, function_name, name = get_segment_info(data, segment)
  File "/Users/anoopd/Library/Python/2.7/lib/python/site-packages/powerline/segment.py", line 69, in get_function
    raise ImportError('Failed to obtain segment function')
ImportError: Failed to obtain segment function
2017-11-14 11:29:41,139:ERROR:vim:segment_generator:Failed to import attr webdevicons_file_format from module vim_devicons.powerline.segments: No module named vim_devicons.powerline.segments
Traceback (most recent call last):
  File "/Users/anoopd/Library/Python/2.7/lib/python/site-packages/powerline/__init__.py", line 382, in get_module_attr
    return getattr(__import__(module, fromlist=(attr,)), attr)
ImportError: No module named vim_devicons.powerline.segments
2017-11-14 11:29:41,140:ERROR:vim:segment_generator:Failed to generate segment from {u'function': u'vim_devicons.powerline.segments.webdevicons_file_format', u'priority': 90, u'exclude_modes': [u'nc'], u'draw_soft_divider': False}: Failed to obtain segment function
Traceback (most recent call last):
  File "/Users/anoopd/Library/Python/2.7/lib/python/site-packages/powerline/segment.py", line 328, in get
    contents, _contents_func, module, function_name, name = get_segment_info(data, segment)
  File "/Users/anoopd/Library/Python/2.7/lib/python/site-packages/powerline/segment.py", line 69, in get_function
    raise ImportError('Failed to obtain segment function')
ImportError: Failed to obtain segment function


I am getting this  error once i start vim, after i added the two configurations  , but the icons are working , please have a look 
![screen shot 2017-11-14 at 11 31 08 am](https://user-images.githubusercontent.com/925418/32765229-7f10fc0a-c92f-11e7-8f30-712a4ee661c6.png)

**Comment by delphinus** [comment]
You should add lines into `.vimrc` in according to [the guide of Poweline][guide].

[guide]: https://powerline.readthedocs.io/en/master/usage/other.html#vim-statusline

The lines to add differs by your installation process of Powerline, the `pip` way or the `git clone` way.  By these lines, Vim can find the `vim_devicons` module.

**Comment by anoopd** [comment]
Hi delphinus ,

                   I **already** have powerline working with vim , i installed it using pip way before and it is working perfectly , i do  have the lines 

     python from powerline.vim import setup as powerline_setup
    python powerline_setup()
     python del powerline_setup

in my .vimrc .  I am getting the above error when i try to add the two segments , ok leave it as it is not that important . Devicons works nicely for nerdtree and that is all i need for now  .  Thank you for your help

**Comment by mustafagonul** [comment]
Hi annopd,

I could not find the proper place to put the two configurations you have mentioned in your previous messages:

**file type segment**

```json
{
	"function": "vim_devicons.powerline.segments.webdevicons",
	"priority": 10,
	"draw_soft_divider": false,
	"after": "  "
}
```

**file format segment**

```json
{
	"function": "vim_devicons.powerline.segments.webdevicons_file_format",
	"draw_soft_divider": false,
	"exclude_modes": ["nc"],
	"priority": 90
 }
```

I appreciate if you can help me regarding this issue.

Thanks,
Mustafa

**Comment by ryanoasis** [comment]
I am closing very old tickets, @anoopd please re-open if this is still an issue for you

**Comment by anoopd** [comment]
Hi mustafagonul ,

         Yesterday only i saw your comment   .............. I have added the two sections in the config file for powerline like what the wiki said  [https://raw.githubusercontent.com/wiki/ryanoasis/vim-devicons/samples/v0.8.x/powerline/themes/vim/default.json] here . My config file is at `~/.config/powerline/themes/vim/default.json` . But i am still getting the error that i mentioned earlier . The icons are working great with Nerdtree but not in status bar . They are working once i press enter and `:source%` my vimrc . Not sure what has gone wrong
