### ISSUE TITLE
Square brackets around icons

### ISSUE THREAD

**Issue by jackharvey1** [ryanoasis/vim-devicons#215]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)

`vim` version: 8.0
`vim-devicons` version: 0.9.3
I'm using vim from iTerm2
I'm using MacOS High Sierra

`.vimrc`:
```
" editor settings
set list
set listchars=eol:↵,tab:.\ ,trail:·,extends:→,precedes:←

set encoding=utf8

set t_Co=256
"syntax on
"syntax enable
set relativenumber
set background=dark
colorscheme monokai
set guifont=Cousine:h11
set hlsearch
let g:airline_powerline_fonts = 1

" tabbing shortcuts
nnoremap <F8> :tabprevious<CR>
nnoremap <F9> :tabnext<CR>

filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab

" status line
set statusline=%t       "tail of the filename
set statusline+=[%{strlen(&fenc)?&fenc:'none'}, "file encoding
set statusline+=%{&ff}] "file format
set statusline+=%h      "help file flag
set statusline+=%m      "modified flag
set statusline+=%r      "read only flag
set statusline+=%y      "filetype
set statusline+=%=      "left/right separator
set statusline+=%c,     "cursor 
set statusline+=%l/%L   "cursor line/total lines
set statusline+=\ %P    "percent through file

"" open automatically
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

"" close if only file
"tocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" using vim-plug
call plug#begin('~/.vim/plugged')
    Plug 'scrooloose/nerdtree'

    "syntax highlighting
    Plug 'neovim/node-host', { 'build': 'npm install' }
    Plug 'billyvg/tigris.nvim', { 'build': './install.sh' }

    "linting
    Plug 'vim-syntastic/syntastic'
    "only look for local eslint
    Plug 'mtscout6/syntastic-local-eslint.vim'
    " prettier
    Plug 'prettier/vim-prettier', {
      \ 'do': 'yarn install',
      \ 'for': ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown'] }

    "status bar
    Plug 'vim-airline/vim-airline'

    Plug 'ryanoasis/vim-devicons'
call plug#end()

if exists("webdevicons#refresh")
    call webdevicons#refresh()
endif

" syntastic setup
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['eslint']

" NERDTree setup
let NERDTreeShowHidden=1
map <C-n> :NERDTreeToggle<CR>
```

This is what I'm seeing:
<img width="251" alt="screen shot 2017-11-17 at 10 31 54 pm" src="https://user-images.githubusercontent.com/21218317/32971860-27da2726-cbe7-11e7-8b31-3b7b0dbd9caa.png">

All I could find was the `webdevicons#refresh()` work around but that didn't seem to do it.

**Comment by EricFalkenberg** [comment]
I am having the same issue. Same exact setup (vim/devicons version and Iterm2).
I've solved the weird offset with the following and added directory icons.
```
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:WebDevIconsNerdTreeAfterGlyphPadding = ''
```

This is what mine looks like now

![Bracket Hell](https://imgur.com/icvRxUg)

**Comment by ryanoasis** [comment]
Sorry for the delay in responding. I will _try_ to look into this this weekend...

**Comment by EricFalkenberg** [comment]
@jackharvey1 I figured it out on my local machine. Let me know if this works for you.
It looks like the built-in vim 8.0 on OSX is compiled without the `|+conceal|` flag.

try installing vim with brew and running that in place of the built-in

**Comment by jackharvey1** [comment]
@EricFalkenberg Brilliant, that's done it, thanks!

@ryanoasis No problem, thanks for responding, I get that you do this in your spare time. If you still want to look into this and want more info on my setup let know.

**Comment by ryanoasis** [comment]
@jackharvey1 I appreciate that thanks! Will do! :smile:

**Comment by ryanoasis** [comment]
I am considering this closed now, with some added info on the Wiki:  https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting#square-brackets-around-icons

Feel free to reopen if issue comes back

**Comment by EricFalkenberg** [comment]
Thanks for all the help @ryanoasis

**Comment by ryanoasis** [comment]
@EricFalkenberg No problem! Glad it is resolved :smile:

**Comment by vadimshvetsov** [comment]
@ryanoasis I'm not sure that this solution fixes all cases.

It looks normal until I do `:source $MYVIMRC`. Any workarounds, to remove brackets after update?

<img width="1045" alt="screenshot 2018-04-01 13 58 39" src="https://user-images.githubusercontent.com/16336572/38172428-013c6088-35b5-11e8-9ffe-6a2fdb4ed165.png"><img width="1045" alt="screenshot 2018-04-01 13 59 04" src="https://user-images.githubusercontent.com/16336572/38172427-0121bdb4-35b5-11e8-8d31-74fd25db0220.png">

vim --version output
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 30 2018 07:37:16)
macOS version
Included patches: 1-1650
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               +ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -
```

And my [.vimrc](https://github.com/vadimshvetsov/dotfiles/blob/master/.config/nvim/init.vim)

**Comment by kutsan** [comment]
@vadimshvetsov Maybe instead of

```vim
syntax on
```

you should use,

```vim
if !exists('g:syntax_on')
	syntax enable
endif
```

?

**Comment by vadimshvetsov** [comment]
Below is helpful code from readme, sorry

```
if exists("g:loaded_webdevicons")
	call webdevicons#refresh()
endif
```

@kutsan thanks, why should I use it?

**Comment by kutsan** [comment]
@vadimshvetsov 

> Below is helpful code from readme, sorry

What? I don't understand.

> thanks, why should I use it?

To prevent overriding syntax items upon `source`. Just try it.

**Comment by vadimshvetsov** [comment]
@kutsan I meant that code from readme, which I pasted above is a solution :)

**Comment by kutsan** [comment]
@vadimshvetsov No, actually it is not a real solution, rather workaround. If you have `syntax on`, and after that `webdevicons#refresh()` in your `init.vim`. When you invoke `source $MYVIMRC`, vim sees `syntax on` and thus overrides your syntax items, including your concealed NERDTree brackets. And then you invoke `webdevicons#refresh()`, which [conceals](https://github.com/ryanoasis/vim-devicons/blob/390b0142f1b6f02bdecc4867009e83c9ecc01db2/plugin/webdevicons.vim#L395-L396) the brackets again. `if !exists('g:syntax_on') | syntax enable | endif` is superior because re-sourcing `init.vim` doesn't override your syntax items. See [this](https://stackoverflow.com/questions/33380451/is-there-a-difference-between-syntax-on-and-syntax-enable-in-vimscript) for more.

**Comment by vadimshvetsov** [comment]
@kutsan Thanks a lot. I think this one must be considered to go in docs @ryanoasis

**Comment by kutsan** [comment]
@vadimshvetsov No problem, always.

**Comment by kutsan** [comment]
@vadimshvetsov Are you invoking `source $MYVIMRC` command inside your NERDTree buffer? If yes, then yes, it is expected because your `init.vim` has `set number`, you are setting the number option for *that* buffer.

**Comment by vadimshvetsov** [comment]
Thanks a lot, it's reasonable.

**Comment by kutsan** [comment]
@vadimshvetsov Furthermore, for example I don't have one `init.vim`/`vimrc`. My [`~/.vim/`](https://github.com/kutsan/dotfiles/tree/master/.vim) folder contains various scripts across folders and invoking `source $MYVIMRC` literally does nothing for me. Either I need to source them one by one or I need to use plugins like [vim-reload](https://github.com/xolox/vim-reload) but I choose not to; for now restarting vim reasonable action for me.

**Comment by vaklinzi** [comment]
I had the same problem but the solutions here worked perfectly. But I have one another problem as well. After (:so %), the icons become white (without color). @kutsan Any idea why and how to fix ti?

**Comment by kutsan** [comment]
@vaklinzi Can I see your config? Probably you need to put some if statement around your `syntax enable` as I said above.

**Comment by KingOfCramers** [comment]
This gets me 90% of the way there, but the brackets are still showing on the top and bottom folder in my NERDTree. My vimrc is here https://gist.github.com/KingOfCramers/480c8fbb02c6e4372f7e24fe78454b18. Any idea what's going wrong?

<img width="235" alt="Screen Shot 2020-04-20 at 8 30 49 PM" src="https://user-images.githubusercontent.com/32515581/79812428-e15ae000-8346-11ea-8479-14fd30b25e0d.png">
<img width="244" alt="Screen Shot 2020-04-20 at 8 37 40 PM" src="https://user-images.githubusercontent.com/32515581/79812429-e1f37680-8346-11ea-9f28-164d09a3c561.png">

**Comment by quanghienle** [comment]
@KingOfCramers I'm having the same problem here :(

**Comment by rationalthinker1** [comment]
I'm having this problem too. It is definitely not solved.

**Comment by smileart** [comment]
Still not solved. Using Neovim installed from brew.

**Comment by sayansil** [comment]
In my case, the `'luochen1990/rainbow'` plugin was causing the issue. Removing it solved it. 

![yes](https://i.imgur.com/UdxFHgm.gif)

So I would suggest checking if any bracket-related plugins are interfering with this.

**Comment by Magicrafter13** [comment]
Similar to @KingOfCramers , but in my case:
icons for files are fine, but there are always square brackets around directories
![image](https://user-images.githubusercontent.com/29127566/94986752-1da98380-0516-11eb-9613-2f0644150d3c.png)

**Comment by kgadek** [comment]
Had similar issue — all was fine until reload (nvim 0.5 current nightly). I managed to fix it:

* dropped `syntax on` & `filetype plugin indent on` from my ~`.vimrc`~ `.config/nvim/init.vim`,
* moved `Plug 'ryanoasis/vim-devicons'` as the very last item, just before `call plug#end()`.

---

Regarding (instrumental!) hint by @kutsan, I've additionally discovered that [junegunn/vim-plug](https://github.com/junegunn/vim-plug/#usage), on `call plug#end()`, invokes `syntax enable` and `filetype plugin indent on` automatically — [they're _seemingly_ doing The Right Thing™](https://github.com/junegunn/vim-plug/blob/d16273e07231260e02412625f98651bc6ceebb56/plug.vim#L422):
```viml
  filetype plugin indent on
  if has('vim_starting')
    if has('syntax') && !exists('g:syntax_on')
      syntax enable
    end
```

As for vim-plug items order — my `Plug 'ryanoasis/vim-devicons'` was after `Plug 'scrooloose/nerdtree'` but before `Plug 'vim-airline/vim-airline'`. No idea why this helped for NERDtree though…

**Comment by hezhizhen** [comment]
I can't conceal the square brackets for dirs and not all dirs have square brackets. It's so weird...

**Comment by b2ns** [comment]
@sayansil , :+1:  thanks .
 
remove [luochen1990/rainbow](https://github.com/luochen1990/rainbow) solve my problem.
so , any plugins dealing with brackets may cause this problem.

**Comment by FedericoBruzzone** [comment]
It works for me

```
let g:rainbow_active = 0

autocmd FileType * let g:rainbow_active=1
```
