### ISSUE TITLE
Better document how to use vim-devicons with a Fontconfig fallback

### ISSUE THREAD

**Issue by duganchen** [ryanoasis/vim-devicons#218]
I recommend adding step-by-step instructions to the following section of the Wiki, for how to use an unpatched font and a Fontconfig fallback. I'd do it myself if I had edit access to the wiki.

https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting#do-i-have-to-use-a-patched-font-such-as-nerd-fonts

1. Install the NERD Font symbol fonts:

* [Symbols Nerd Font:style=1000-em](https://github.com/ryanoasis/nerd-fonts/blob/master/src/glyphs/Symbols-1000-em%20Nerd%20Font%20Complete.ttf)
* [Symbols Nerd Font:style=2048-em](https://github.com/ryanoasis/nerd-fonts/blob/master/src/glyphs/Symbols-2048-em%20Nerd%20Font%20Complete.ttf)

2. Install [10-nerd-font-symbols.conf](https://github.com/ryanoasis/nerd-fonts/blob/master/10-nerd-font-symbols.conf) for Fontconfig

**Comment by ryanoasis** [comment]
@duganchen That's a great idea/improvement :smile: thanks!

Oh you know what I always thought I had the wiki publicly editable, I have now removed the restriction. You should now be able to edit the wiki :smile:

**Comment by ryanoasis** [comment]
Now done. Thanks.

ref: https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting#do-i-have-to-use-a-patched-font-such-as-nerd-fonts
