### ISSUE TITLE
Icons show in Terminal but not in iTerm

### ISSUE THREAD

**Issue by shammellee** [ryanoasis/vim-devicons#226]
I've tried the following fonts and all work in Terminal but not in iTerm

```vim
set guifont=DroidSansMonoForPowerline_Nerd_Font:h10
```
```vim
set guifont=Knack_Nerd_Font:h10
```
```vim
set guifont=InconsolataForPowerline_Nerd_Font:h10
```
```vim
set guifont=FuraMonoForPowerline_Nerd_Font:h10
```

I've also changed to `Font` and `Non-ASCII Font` values in iTerm to the corresponding Nerd Font.

**Comment by ryanoasis** [comment]
@shammellee Does the font not work at all or the glyphs for filetypes aren't showing?

Could you provide a screenshot?

**Comment by MadRukus** [comment]
Was having this issue with nerd fonts complete and powerlevel9k theme which worked in Terminal but not iTerm2. Not the exact same scenario but I created another profile name, set it as default and set the fonts and it solved my issue. If you have not tried that might want to see if it works.

**Comment by reorx** [comment]
I encountered the same problem here. Screenshots below:

Terminal.app:
![image](https://user-images.githubusercontent.com/405972/47134589-dc474b80-d2df-11e8-8e7e-b514e70ff955.png)
![image](https://user-images.githubusercontent.com/405972/47134599-e49f8680-d2df-11e8-9179-6ff7d4351338.png)
![image](https://user-images.githubusercontent.com/405972/47134623-f5e89300-d2df-11e8-8e3c-7066dfa5a53f.png)

Iterm2.app:
![image](https://user-images.githubusercontent.com/405972/47134667-1add0600-d2e0-11e8-8fbb-32732dc9e4d6.png)
![image](https://user-images.githubusercontent.com/405972/47134679-26303180-d2e0-11e8-86b0-1afa61cf81d0.png)
![image](https://user-images.githubusercontent.com/405972/47134689-334d2080-d2e0-11e8-9646-ace9fa3c2cf7.png)

System info:
- MacOS 10.13.6
- iTerm2 Build 3.2.4beta1
- neovim 0.3.1

**Comment by shammellee** [comment]
After over a year of several failed attempts, I finally got it working with the following…

```sh
$ brew tap homebrew/cask-fonts
$ brew cask install font-hack-nerd-font
```

In my `.vimrc` (after enabling airline, powerline, etc.)…
```
set encoding=utf-8
let g:airline_powerline_fonts = 1
```

In iTerm2, change the Non-ASCII font to a Nerd Font (eg, Droid Sans Mono Nerd Font Complete)

Restart Vim

**Comment by jinleileiking** [comment]
brew install --cask  font-hack-nerd-font

**Comment by thijssmudde** [comment]
All I had to do was set the font in Iterm2 preferencess to a Nerd Font.

**Comment by nahumzs** [comment]
<img width="963" alt="image" src="https://github.com/ryanoasis/vim-devicons/assets/19418590/7599fb0c-c5ea-416f-aa27-8479610dcef1">

switched to `nerd font` on the font option

**Comment by eaoliver** [comment]
I had this issue.  It appeared to be a stale configuration in iTerm2.  After hours of banging my head against the wall (Nerd Fonts worked in Terminal), I toggled the Terminal > Terminal Emulation > Character encoding from 'Unicode (UTF-8)' (which it was on), so the same value.  

After starting a new iTerm window, it finally worked as expected.

**Comment by tim-phillips** [comment]
For some reason I had to select the profile from the Profiles menu in the macOS menu bar in the top left.
