### ISSUE TITLE
Too many spaces in tabline

### ISSUE THREAD

**Issue by Dcryfm** [ryanoasis/vim-devicons#227]
There are two spaces after the icon:

![](https://github.com/Dcryfm/jsdoc/blob/master/issues_images/vim-devicons/%23227.png?raw=true)

I have read devicons documentation, it seems no relevant settings.

**Comment by ryanoasis** [comment]
I think this is due to `appendArtifactFix`, right now there is no configuration for it.

See #225

**Comment by ryanoasis** [comment]
Things should be better and more consistent now. Let me know if you still see issues, there should be no extra spaces unless you configure it to be that way. We can reopen
