### ISSUE TITLE
Screen flashing if DevIconsEnableFoldersOpenClose option is enabled

### ISSUE THREAD

**Issue by kutsan** [ryanoasis/vim-devicons#230]
When I have `let g:DevIconsEnableFoldersOpenClose = 1`, all `redraw!`s behave like this, makes my screen flashing.

![](https://i.imgur.com/IKeZHvR.gif)

Removing all `redraw!` lines, solves the problem without any issue.

https://github.com/ryanoasis/vim-devicons/blob/82df484ca2205eb48409fd99923f1f6f80f1ee4b/nerdtree_plugin/webdevicons.vim#L197

-----

#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] What **version** of vim are you using?
  - `nvim v0.2.2`
- [x] What **version** of vim-devicons are you using?
  - `v0.10.0`
- [x] Are you using vim from the terminal or a GUI vim?
  - Terminal
    - [x] Which terminal are you using?
      - Alacritty
- [x] Are you using Mac, Linux or Windows?
   - Mac

**Comment by ryanoasis** [comment]
Yeah that's pretty bad. I think we added it to fix glyph artifacts on gui him. Similar to the artifact discussion I think these redraws need to be configurable with the default being off for terminal.

Will add more detail when I get back to my dev environment.

Thanks for the report

**Comment by kutsan** [comment]
Thanks friend! I am looking forward to.

**Comment by ryanoasis** [comment]
This should now be fixed.

redraw is configurable with `g:DevIconsEnableNERDTreeRedraw`. It is off by default if no gui and on by default if gui. Also configurable by user to override regardless if the end user wishes. :smile:

**Comment by kutsan** [comment]
Awesome! Thanks!
