### ISSUE TITLE
Make prePadding configurable

### ISSUE THREAD

**Issue by kutsan** [ryanoasis/vim-devicons#231]
https://github.com/ryanoasis/vim-devicons/blob/82df484ca2205eb48409fd99923f1f6f80f1ee4b/plugin/webdevicons.vim#L719

We can configure the after padding but there is no way for pre one. I want to add a little bit more spaces before each glyph but I have to do that manually.

**Comment by ryanoasis** [comment]
Yes this is a very good idea. I think next release we will make a lot of things configurable: artifactFix, redraw, this left side padding

**Comment by kutsan** [comment]
Thanks!
