### ISSUE TITLE
Vim-Startify no longer works out of the box

### ISSUE THREAD

**Issue by ezpuzz** [ryanoasis/vim-devicons#233]
https://github.com/mhinz/vim-startify/commit/983919aee26706ff546814ce053eebc5d9c961cf
https://github.com/mhinz/vim-startify/commit/e1716c4ef14f3559e3c112c2d103e42fc89d0149

easy enough to set up following the startify docs above, don't know if you wanted to update readme

**Comment by ryanoasis** [comment]
@ezpuzz Thanks for the heads up! We'll get this fixed up in the next release!

When I first read the issue title I went "oh no" then after seeing the changes I said "that's cool" :smile:

**Comment by ryanoasis** [comment]
I agree by default we should try to have it work out of the box and also give a config that we allow users to turn off the 'out of the box' nature for full flexibility.

**Comment by ryanoasis** [comment]
Better late than never.

Hopefully this doesn't cause any issues, if it does we can remove the default config and let the user do it in their `vimrc` but I want to try to stick to the nature of DevIcons "just working" after install and minimal setup.
