### ISSUE TITLE
Add support for .vue files.

### ISSUE THREAD

**Issue by cj** [ryanoasis/vim-devicons#235]
[Vuejs](https://vuejs.org/) is becoming increasingly more popular, it would be great to add support for [.vue](https://vuejs.org/v2/guide/single-file-components.html) files.

Thank you again for such a great plugin!

**Comment by ryanoasis** [comment]
Great suggestion! I am becoming of fan of Vue :smile: 

This will be supported out of the box when [Nerd Fonts v2.0](https://github.com/ryanoasis/nerd-fonts/milestone/18) releases

If you get your hands on one of the patched fonts in master you can actually make this work right _now_ :stuck_out_tongue: 

```vim
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['vue'] = '﵂'
```

![selection_014](https://user-images.githubusercontent.com/8083459/36929956-4a005ee8-1e66-11e8-97df-dbc1445f5b49.png)

**Comment by cj** [comment]
Awesome!  Works like a charm!  Thank you!

**Comment by ryanoasis** [comment]
@cj Great! :+1: 

I think we'll support it "out of the box" in the next release.

**Comment by ryanoasis** [comment]
@Smona Yes, but if you are checking out from `master` it should be working currently. Since we have changed to a faster workflow (stuff goes into master first after only basic sanity checking).

Albeit I am really behind at the moment, especially some really great PRs on hold.
