### ISSUE TITLE
Instead of glyphs, I see Chinese characters

### ISSUE THREAD

**Issue by jackiilong** [ryanoasis/vim-devicons#240]
![image](https://user-images.githubusercontent.com/11622076/41634853-3d8f97a6-7478-11e8-9014-9135d791386e.png)

**Comment by kutsan** [comment]
Could it be an encoding problem? Add this to your `.vimrc` and try again?

```vim
set encoding=UTF-8
```

**Comment by jackiilong** [comment]
already set this option.
it is still  this showing

**Comment by kutsan** [comment]
Then we need to you to provide a minimal `.vimrc` to produce your problem with your version and system.

**Comment by kutsan** [comment]
And just to make sure, are you sure you are using [a Nerd Font compatible font](https://github.com/ryanoasis/nerd-fonts/releases)?

**Comment by jackiilong** [comment]
well.
Do you mean that I should set my terminal font to be  the nerd font I have  installed ?

**Comment by kutsan** [comment]
Yes, exactly.

**Comment by cnscorpions** [comment]
Maybe those fonts are not recognized as Monospace fonts by Gnom terminal. you can refer to [Nerd Fonts #318](https://github.com/ryanoasis/nerd-fonts/issues/318). It works for me. :)

**Comment by tushar-c23** [comment]
It still isn't working for me. I set my terminal font to Hack Nerd Font but the glyphs are still chinese characters. I'm on PopOs!

**Comment by caracal4e** [comment]
I'm also on Pop!_OS. I think I tried out another distro and it fixed itself somehow... So it might be Pop!_OS' fault.

**Comment by adarshkunwar** [comment]
I am on POP_OS as well. I had the same problem till the morning. I solved it by going to prefernces and then to Pop and then chosing a nerd font
