### ISSUE TITLE
DevIconsEnableFoldersOpenClose can't open subdirectories recursively

### ISSUE THREAD

**Issue by rod-stuchi** [ryanoasis/vim-devicons#243]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)

- [x] What **version** of vim are you using?
NVIM v0.3.0
- [x] What **version** of vim-devicons are you using?
0.10.0 (updated today with vim-plug)
- [x] Are you using vim from the terminal or a GUI vim?
terminal (konsole / iTerm2)
- [x] Are you using Mac, Linux or Windows?
Arch / Mac

--------

NERDTree can't opens recursively subdirectories (the `O` command) if the option `let g:DevIconsEnableFoldersOpenClose = 1` in **vim-devicons** is set.

**Comment by ryanoasis** [comment]
Thanks @rod-stuchi and @kutsan

**Comment by ryanoasis** [comment]
closing via #314 :tada:
