### ISSUE TITLE
Many items show up as missing, but only in the console?

### ISSUE THREAD

**Issue by CaerphillyMediaLtd** [ryanoasis/vim-devicons#247]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)

- [ ] What **version** of vim are you using?
  - Nvim v0.3.1, Vim 8.1
- [ ] What **version** of vim-devicons are you using?
  - 0.10.0
- [ ] Are you using vim from the terminal or a GUI vim?
  - Both, works fine in gvim
- [ ] Are you using Mac, Linux or Windows?
  - Arch Linux

#### Optional Info

- [ ] Provide **screenshots** where appropriate
![image](https://user-images.githubusercontent.com/38424470/47444277-0b612f80-d7ae-11e8-9e05-9cce09d4a8f7.png)

As you can see the icons all work fine in gvim, but only some work in nvim, if I enable folder icons none work at all. My vimrc contains:

    set guifont=Droid\ Sans\ Mono\ for\ Powerline\ Nerd\ Font\ Complete\ 12
    set encoding=utf-8
    let g:airline_powerline_fonts = 1

I've tried different fonts, sizes, loads of things, but it just doesn't seem to fully work in the console? The console I'm using is URXVT, I did try xterm but they don't appear at all in there.

**Comment by Andrioshe** [comment]
I also got the same problems but could not find any solution for this

**Comment by kazukazuinaina** [comment]
Thanks for report.

- Will using the latest version of Neovim cause the same issue?
- Even if you update NERDTree to the latest state, can the problem be reproduced?
- Did you set NERDFont on the terminal?

### like this

![image](https://user-images.githubusercontent.com/36619465/81425050-d353ee80-9191-11ea-9652-334dd4c1572c.png)

e.g : iTerm2

**Comment by kazukazuinaina** [comment]
No reply, so I'm closing this issue.
Feel free to reopen this issue or create a new one if you have problems.
