### ISSUE TITLE
Icons doesnt show

### ISSUE THREAD

**Issue by n3rio** [ryanoasis/vim-devicons#256]
Icons doesn't show, i have run the troubleshooting commands, and the only one that it appears to be failing is:
`:echo g:WebDevIconsUnicodeDecorateFileNodesDefaultSymbol`, the output of this command is square, it's like to brackets together, this is really annoying, it's not preventing me for working, for it is annoying, i'm using Xubuntu 18.04, i was using Terminator, but now i'm using HyperJs

**Comment by ryanoasis** [comment]
I appreciate you running through the troubleshooting commands but you should've kept the issue template.

Which font are you using?

**Comment by n3rio** [comment]
Sorry about that and the delay, i'm using Backlog Medium, but before I was using another don't but the issue persist, in fact, I change fonts to check if the was the problem, should I upload a screenshot of the interface to show what I mean?

**Comment by n3rio** [comment]
I'm closing this, i had not installed nerd-fonts, sorry about that, all good
