### ISSUE TITLE
Slow scrolling in NERDTree when devicons active and directories open

### ISSUE THREAD

**Issue by sethen** [ryanoasis/vim-devicons#263]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?
  - hint: `vim --version`
NVIM v0.3.1
- [x] What **version** of vim-devicons are you using?
  - hint: `:echo webdevicons#version()`
0.11.0
- [x] Are you using vim from the terminal or a GUI vim?
Terminal
- [x] Are you using Mac, Linux or Windows?
Ubuntu Linux 18.04

#### Optional Info

- [ ] Provide **screenshots** where appropriate

When scrolling through in NERDTree (pressing J or K) scrolling is smooth if no directory trees are open.  When I start opening directories and scrolling up and down it gets very slow.  It skips to the point where I can't see the cursor any longer.  When I disable devicons in vim-plug the scrolling becomes smooth again regardless of how many directory trees are open.

**Comment by sethen** [comment]
Had some time to figure out what this is caused by.  Seems the culprit is actually `vim-nerdtree-syntax-highlight` and is a current open issue here: `https://github.com/tiagofumo/vim-nerdtree-syntax-highlight/issues/17`.

There are a few ways to get around this.  The first is to use the plugin `vim-nerdtree-syntax-highlight` and then put `set lazyredraw` in your `init.vim` or `.vimrc`.  The second is to follow the wiki and put in the function as described here: https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting#how-did-you-get-color-matching-based-on-file-type-in-nerdtree  -- though with the second approach it's a bit harder to just change the icons/glyphs.

I feel like this should be documented in this wiki.  I can make a PR for this.

**Comment by sethen** [comment]
I actually just updated the wiki with the above.  Thanks.

**Comment by pattrickrice** [comment]
`set lazyredraw` didn't work for me but `let NERDTreeHighlightCursorline = 0` did.
https://github.com/tiagofumo/vim-nerdtree-syntax-highlight/issues/17

**Comment by benlieb** [comment]
neither `set lazyredraw` nor `NERDTreeHighlightCursorline = 0` worked for me.

**Comment by nowave7** [comment]
I'm having a similar issue. The scrolling is not slow, but rather choppy, or sometimes slows down. Also neither `set lazyredraw` nor `let NERDTreeHighlightCursorline = 0` worked for me as well.
I'm going to try with this proposed function...

**Comment by Dhamma-valence** [comment]
So, for me NERDTree is *extra* slow when devicons are active, and disabling them certainly helps. However, it is still unbearably slow even with devicons disabled. It's such a pain because NERDTree is easily my favourite vim directory viewer in both form and function, but the slowness makes it literally unusable.

I also tried both `set lazyredraw` and `let NERDTreeHighlightCursorline = 0` but neither changed a thing.
