### ISSUE TITLE
Support new file/old file/point and file/rec Denite sources

### ISSUE THREAD

**Issue by ctaylo21** [ryanoasis/vim-devicons#265]
Denite has deprecated the `file_old`, `file_point`, `file_rec` sources and replaced them with `file/old`, `file/point`, and `file/rec`. Vim-devicons should support these new sources.

As a side note, I have never had icon colors work for `:Denite file_rec`. I'm not sure if I did something wrong or if that ever worked. I can separate that out into another issue if preferred.
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?
  - `NVIM v0.4.0-dev`
- [x] What **version** of vim-devicons are you using?
  - `0.11.0`
- [x] Are you using vim from the terminal or a GUI vim? terminal
- [x] Are you using Mac, Linux or Windows? Mac

#### Optional Info

- [x] Provide **screenshots** where appropriate

Main issue:
![image](https://user-images.githubusercontent.com/1427469/55742566-d572d900-59e4-11e9-8c25-c7921ace4316.png)
*Note* The above screenshot is using the vim "floating window" feature, but the result is the same for either way that Denite is rendered (in a split or floating window).

Colors not working in with `:Denite file_rec`:
![image](https://user-images.githubusercontent.com/1427469/55742733-3e5a5100-59e5-11e9-8001-f599cccb1621.png)

**Comment by Luxed** [comment]
Not home currently so can't make a PR, but you can add this to your config:
`call denite#custom#source('file,file/rec,file/mru,file/old,file/point', 'converters', ['devicons_denite_converter'])`

**Comment by ryanoasis** [comment]
Thanks @ctaylo21 and @Luxed

**Comment by ryanoasis** [comment]
fixed in #273
