### ISSUE TITLE
NERDTree broken X and O

### ISSUE THREAD

**Issue by ecx** [ryanoasis/vim-devicons#268]
**Required Info**

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] VimDevIcons is the last loaded vim plugin? Yes
- [x] What **version** of vim are you using?
VIM - Vi IMproved 8.1
- [x] What **version** of vim-devicons are you using?
0.11.0
- [x] Are you using vim from the terminal or a GUI vim? terminal, Kitty
- [x] Are you using Mac, Linux or Windows? Linux

Optional Info
- [ ] Provide screenshots where appropriate

No need in screenshots

After adding vim-devicons, NERDTree plugin's features:
O: recursively open node
X: close all child nodes of current node recursively
stops working properly

**Comment by ecx** [comment]
related to [#243](https://github.com/ryanoasis/vim-devicons/issues/243). Possible solution:
```
diff --git a/nerdtree_plugin/webdevicons.vim b/nerdtree_plugin/webdevicons.vim
index c873069..f5f3fca 100644
--- a/nerdtree_plugin/webdevicons.vim
+++ b/nerdtree_plugin/webdevicons.vim
@@ -210,8 +210,8 @@ endfunction
 function! WebDevIconsNERDTreeMapOpenRecursively(node)
   " normal original logic:
   call nerdtree#echo("Recursively opening node. Please wait...")
-  call a:node.openRecursively()
   call WebDevIconsNERDTreeDirOpenRecursively(a:node)
+  call a:node.openRecursively()
   " continue with normal original logic:
   call b:NERDTree.render()
   " glyph change possible artifact clean-up
```

**Comment by ryanoasis** [comment]
Thanks @ecx it's on the radar

**Comment by ryanoasis** [comment]
closing via #314 :tada:
