### ISSUE TITLE
Icon's are all the same Question mark

### ISSUE THREAD

**Issue by svliantiss** [ryanoasis/vim-devicons#269]
I've installed a Nerd-font and Devicons via Vim-Plug.
I've followed and consulted the manpages but all the configurations seem to be correct returning 1 or that the font is set.

you can find my neovim setup here https://github.com/svliantiss/dotfiles/tree/master/neovim

I am using 
set guifont=DroidSansMono\ Nerd\ Font\ 11
set guifont=DroidSansMono\ Nerd\ Font:h11

It doesn't work on any of these platforms, but it does respond 1 or the correct font:
Vim (on any of the plaforms below)
Neovim (on any of the platforms below)
Linux Ubuntu 19.04
MacOs Mojave iTerm2 and Terminal
Linux Manjaro (up-to-date)
Windows Subsystem for Linux (Ubuntu 18.04.02 TLS)

![image](https://user-images.githubusercontent.com/38691414/56932811-7b49cd00-6ae5-11e9-902e-bd41e8755e60.png)

**Comment by ryanoasis** [comment]
This might be encoding issue? 

Can you try:
```vim
set encoding=UTF-8
```

**Comment by gallor** [comment]
So I'm in the same boat using NeoVim. All 1s on all the debug items, set the `guifont` and matched the font in the iTerm settings. Using patched nerd fonts. Tried both `set encoding=UTF-8` and `set encoding=utf-8`. Any other ideas to try?

**Comment by svliantiss** [comment]
Sorry for the late response, but yes that option of ```set encoding=UTF-8``` has already been enabled.

**Comment by brettswift** [comment]
I don't know if this adds value to this post but I have a similar issue, except I'm getting chinese characters for javascript files, and .vim   config files. 

![image](https://user-images.githubusercontent.com/723989/61999166-a4dcab00-b078-11e9-9af6-09fa003f194b.png)

using neovim, i3, gnome-terminal, and that screenshot is from NERDTree.

**Comment by sanjays0101** [comment]
Same issue with me as well in mac

**Comment by jiftle** [comment]
![Uploading 深度截图_选择区域_20190902095551.png…]()

**Comment by kazukazuinaina** [comment]
@svliantiss

Did you set Nerdfont on the terminal?

## As below

<img width="249" alt="スクリーンショット 2019-10-28 19 05 01" src="https://user-images.githubusercontent.com/36619465/67669779-e8b3b900-f9b5-11e9-90c2-10b09245fe5a.png">

ps (it is iTerm2)

**Comment by cnscorpions** [comment]
@kazukazuinaina it does not work for setting up font in my gnom-terminal.
my .vimrc is as follows:
`
set encoding=UTF-8
set guifont=FiraCode\ NF\ 11
`

**Comment by ShinValor** [comment]
Setting Hack Nerd Font works for me (I am using iTerm2)

**Comment by ericheinmiller** [comment]
So is it safe to say there's no definite fix to the mass question mark issue?
Same situation here: Iterm2, neovim, terminal is using Hack Nerd Font, UTF-8.
All I see are mass question marks too

**Comment by kazukazuinaina** [comment]
@cnscorpions 

`set guifont` is a setting for GUI such as GVim. So if you are using Vim on a terminal I don't think it helps. You needs to be selected and set Nerd font from the GNOME terminal.

**Comment by kazukazuinaina** [comment]
I close this issue. If you have any problems, feel free to restart or create a new one.

**Comment by normancapule** [comment]
Installing it using `nerd-fonts` script fixed it for me https://github.com/ryanoasis/nerd-fonts#option-3-install-script

`./install.sh FiraCode`

**Comment by LeoAJ** [comment]
> Setting Hack Nerd Font works for me (I am using iTerm2)

same situation for me, only `Hack Nerd Font` works, change to other fonts will show `?` for all icons

**Comment by kyp0717** [comment]
If you are in Mac, uyou need to set Hack Nerd Font in your profile (under the section Profiles -> Text -> Non-Ascii Font. Remember set it under Non-Ascii Font!!!

**Comment by ryanoasis** [comment]
Thanks for the follow ups

**Comment by mikebobadilla** [comment]
After updating iterm, I had to quit it so the changes would take effect.

![image](https://user-images.githubusercontent.com/5985141/98326557-64234f80-1fa6-11eb-9a71-f149a81be6a4.png)

**Comment by gtsilva** [comment]
Setting Hack Nerd Font works for me (I am using iTerm2)

**Comment by vinybrasil** [comment]
for those using windows/WSL, download the fonts here: https://www.nerdfonts.com/font-downloads, install them by right clicking "install" on the selected files on windows and them switch to the new font on WSL.

**Comment by granteagon** [comment]
iTerm's profile select is not the most intuitive.  Make sure you're setting the font on the right profile.

**Comment by drjrm3** [comment]
I'm in a surprisingly nuanced and perhaps more confusion position.

I'm using iterm2, hack nerd font installed, ssh'ing into 2 of my own linux machines. One has question marks in places, the other does not (and looks perfectly fine as I would expected).

On my local laptop with nvim it looks more like the 'broken' (question mark) server. Any one else have this issue? Not sure how to resolve this one or even diagnose it.

**Comment by worldsayshi** [comment]
It finally worked for me on Windows Terminal after installing `Hack Nerd Font` *for all users* (right click -> show more options -> install for all users). And then setting the font in Settings -> Appearance -> Font Face. And restart the Terminal App. And maybe try doing it in a different order.

**Comment by blindstitch** [comment]
> It finally worked for me on Windows Terminal after installing `Hack Nerd Font` _for all users_ (right click -> show more options -> install for all users). And then setting the font in Settings -> Appearance -> Font Face. And restart the Terminal App. And maybe try doing it in a different order.

This plus a restart did the trick.
