### ISSUE TITLE
why have the word "[  ]"  front the directory

### ISSUE THREAD

**Issue by myname9** [ryanoasis/vim-devicons#274]
i installed nerdtree last version,i installed vim-devicons last version,i have a problem
why have the word "[  ]"  front the directory

#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?
  - hint: `vim --version`
- [x] What **version** of vim-devicons are you using?
  - hint: `:echo webdevicons#version()`
- [x] Are you using vim from the terminal or a GUI vim?
- [x] Are you using Mac, Linux or Windows?

```
$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 29 2017 18:37:46)
Included patches: 1-503, 505-680, 682-1283
Compiled by root@apple.com
```

![image](https://user-images.githubusercontent.com/8705998/60413644-3b4bb700-9c08-11e9-86ad-bb02b5749b71.png)

**Comment by dborinsk** [comment]
I updated nerdtree and devicons and since then im having the same issue.

**Comment by myname9** [comment]
@dborinsk   i download vim8.1 , absolute this issue, i think the issue is relation to vim8.0

**Comment by Campanula** [comment]
I have the same
with nvim 0.4.0

**Comment by myname9** [comment]
@dborinsk @Campanula  
let g:webdevicons_conceal_nerdtree_brackets = 1
complete

**Comment by Campanula** [comment]
@myname9 Thank you, but it doesn't work for mine. I find a strange place:

![image](https://user-images.githubusercontent.com/8176642/60480411-01d48380-9cbc-11e9-9411-c37570823980.png)

the dir type goes wrong while the regular type is good。

**Comment by dborinsk** [comment]
@myname9 Not working for me as well NVIM v0.3.1

**Comment by seemethere** [comment]
Most likely has something to do with https://github.com/ryanoasis/vim-devicons/pull/255,

cc @ryanoasis

**Comment by ryanoasis** [comment]
> @dborinsk @Campanula
let g:webdevicons_conceal_nerdtree_brackets = 1
complete

@myname9 did you mean that `let g:webdevicons_conceal_nerdtree_brackets = 1` solved the issue for you?

---

@dborinsk, @seemethere I was unable to replicate the issue on gvim or vim. I cleared my vimrc settings. Can you post your vimdevicon vimrc settings?

particularly check:
```
:set conceallevel?
:echo g:webdevicons_conceal_nerdtree_brackets
```

**Comment by myname9** [comment]
@ryanoasis  it did not solved the issue, but it can control the '[ ]' in a new vim.
i installed vim8.1  and  set `let g:webdevicons_conceal_nerdtree_brackets = 1` solved the issue.
however , my mac default vim8.0 have the issue now.

**Comment by ryanoasis** [comment]
I am only able able to test vim8.0

These worked for me:
```
:set conceallevel=2
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
```

`g:WebDevIconsUnicodeDecorateFolderNodes` should be on by default but current isn't: https://github.com/ryanoasis/vim-devicons/blob/4ba84019a5d4c10e01eff62089c7385a39af3be5/plugin/webdevicons.vim#L65

**Comment by Campanula** [comment]
@ryanoasis 
my nvim 0.4.0 :

```
:set conceallevel?  ==> conceallevel=3
:echo g:webdevicons_conceal_nerdtree_brackets ==> 1
:echo g:WebDevIconsUnicodeDecorateFolderNodes ==> 0
```

then , I set:
```
set conceallevel=2
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
```
It goes to:
![image](https://user-images.githubusercontent.com/8176642/60565539-9b706380-9d96-11e9-9e67-a0dc96bd6ad5.png)

the first dir still .

**Comment by dborinsk** [comment]
> let g:WebDevIconsUnicodeDecorateFolderNodes = 1

Same here, I did the same steps and now only the first directory has `[`

**Comment by dborinsk** [comment]
> @ryanoasis
> my nvim 0.4.0 （vim 8.1 occurs the same issue） :
> 
> ```
> :set conceallevel?  ==> conceallevel=3
> :echo g:webdevicons_conceal_nerdtree_brackets ==> 1
> :echo g:WebDevIconsUnicodeDecorateFolderNodes ==> 0
> ```
> 
> then , I set:
> 
> ```
> set conceallevel=2
> let g:WebDevIconsUnicodeDecorateFolderNodes = 1
> ```
> 
> It goes to:
> ![image](https://user-images.githubusercontent.com/8176642/60565539-9b706380-9d96-11e9-9e67-a0dc96bd6ad5.png)
> 
> the first dir still .

Same here, I did the same steps and now the first directory is with `[`

**Comment by seemethere** [comment]
> > @dborinsk @Campanula
> > let g:webdevicons_conceal_nerdtree_brackets = 1
> > complete
> 
> @myname9 did you mean that `let g:webdevicons_conceal_nerdtree_brackets = 1` solved the issue for you?
> 
> @dborinsk, @seemethere I was unable to replicate the issue on gvim or vim. I cleared my vimrc settings. Can you post your vimdevicon vimrc settings?
> 
> particularly check:
> 
> ```
> :set conceallevel?
> :echo g:webdevicons_conceal_nerdtree_brackets
> ```

@ryanoasis 

```
❯ nvim --headless +'set conceallevel?'
  conceallevel=0 
❯ nvim --headless +':echo g:webdevicons_conceal_nerdtree_brackets'
1
❯ nvim --version
NVIM v0.3.6
Build type: RelWithDebInfo
Lua 5.3
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wconversion -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/build/BUILD/neovim-0.3.6/build/config -I/builddir/build/BUILD/neovim-0.3.6/src -I/usr/include -I/builddir/build/BUILD/neovim-0.3.6/build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.3.6/build/include
Compiled by mockbuild

Features: +acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by astroshot** [comment]
![image](https://user-images.githubusercontent.com/24741314/60797287-939f2d80-a1a1-11e9-8e18-a19d3a5b1711.png)

I'm using vim 8.1 on MacOS and encounter this issue, with devicons settings as

```
" devicons config
if exists("g:loaded_webdevicons")
  call webdevicons#refresh()
endif
let g:airline_powerline_fonts = 1
let g:webdevicons_enable_vimfiler = 0
let g:webdevicons_conceal_nerdtree_brackets = 1
let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '
let g:WebDevIconsNerdTreeGitPluginForceVAlign = 0
```

**Comment by seemethere** [comment]
Appears as though 6902851 fixes most of the issues but does leave a leading `[`

<img width="832" alt="Screen Shot 2019-07-08 at 4 46 37 PM" src="https://user-images.githubusercontent.com/1700823/60849522-fbed0f80-a19f-11e9-9521-63c5b3cf5d90.png">

Thanks for jumping on this so quick @ryanoasis!

**Comment by netcan** [comment]
> Appears as though [6902851](https://github.com/ryanoasis/vim-devicons/commit/69028519c368304a6bf95f629b924c2ea85c69db) fixes most of the issues but does leave a leading `[`
> 
> <img alt="Screen Shot 2019-07-08 at 4 46 37 PM" width="832" src="https://user-images.githubusercontent.com/1700823/60849522-fbed0f80-a19f-11e9-9521-63c5b3cf5d90.png">
> 
> Thanks for jumping on this so quick @ryanoasis!

I have same problem, but while resource ~/.vimrc, it work ok @ryanoasis 
![image](https://user-images.githubusercontent.com/11377070/61588245-97cc4180-abca-11e9-927d-bcb4e0cce468.png)

**Comment by netcan** [comment]
> ![image](https://user-images.githubusercontent.com/24741314/60797287-939f2d80-a1a1-11e9-8e18-a19d3a5b1711.png)
> 
> I'm using vim 8.1 on MacOS and encounter this issue, with devicons settings as
> 
> ```
> " devicons config
> if exists("g:loaded_webdevicons")
>   call webdevicons#refresh()
> endif
> let g:airline_powerline_fonts = 1
> let g:webdevicons_enable_vimfiler = 0
> let g:webdevicons_conceal_nerdtree_brackets = 1
> let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '
> let g:WebDevIconsNerdTreeGitPluginForceVAlign = 0
> ```

I have tested it when closed rainbow plugin, may be conflit with rainbow plugin.

**Comment by astroshot** [comment]
> > ![image](https://user-images.githubusercontent.com/24741314/60797287-939f2d80-a1a1-11e9-8e18-a19d3a5b1711.png)
> > I'm using vim 8.1 on MacOS and encounter this issue, with devicons settings as
> > ```
> > " devicons config
> > if exists("g:loaded_webdevicons")
> >   call webdevicons#refresh()
> > endif
> > let g:airline_powerline_fonts = 1
> > let g:webdevicons_enable_vimfiler = 0
> > let g:webdevicons_conceal_nerdtree_brackets = 1
> > let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '
> > let g:WebDevIconsNerdTreeGitPluginForceVAlign = 0
> > ```
> 
> I have tested it when closed rainbow plugin, `leave a leading [` may be conflit with rainbow plugin.
> set it to .vimrc:
> 
> ```
> let g:rainbow_conf = {
> \    'separately': {
> \       'nerdtree': 0
> \    }
> \}
> ```
> 
> but when set cwd to DIR(eg Downloads) will see DIR hasn't folder icon:
> ![image](https://user-images.githubusercontent.com/11377070/61592795-8014ad80-ac0a-11e9-9e7a-72b982ad0664.png)
> 
> @seemethere @astroshot @dborinsk @Campanula

Awesome, it worked for me! Many thanks
