### ISSUE TITLE
The symbol for opened folder in NERDTree is not working

### ISSUE THREAD

**Issue by PetarMetodiev** [ryanoasis/vim-devicons#276]
First of all **thank you** for the great plugin. As someone who always wants things to have some visual cues, it helps me a lot and makes things look a lot nicer!

#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 16 2019 03:25:28)
macOS version
Included patches: 1-1700
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +cmdline_compl     +emacs_tags        +insert_expand     +modify_fname      +netbeans_intg     +ruby              +termguicolors     +visualextra
+arabic            +cmdline_hist      +eval              +job               +mouse             +num64             +scrollbind        +terminal          +viminfo
+autocmd           +cmdline_info      +ex_extra          +jumplist          -mouseshape        +packages          +signs             +terminfo          +vreplace
+autochdir         +comments          +extra_search      +keymap            +mouse_dec         +path_extra        +smartindent       +termresponse      +wildignore
-autoservername    +conceal           -farsi             +lambda            -mouse_gpm         +perl              -sound             +textobjects       +wildmenu
-balloon_eval      +cryptv            +file_in_path      +langmap           -mouse_jsbterm     +persistent_undo   +spell             +textprop          +windows
+balloon_eval_term +cscope            +find_in_path      +libcall           +mouse_netterm     +postscript        +startuptime       +timers            +writebackup
-browse            +cursorbind        +float             +linebreak         +mouse_sgr         +printer           +statusline        +title             -X11
++builtin_terms    +cursorshape       +folding           +lispindent        -mouse_sysmouse    +profile           -sun_workshop      -toolbar           -xfontset
+byte_offset       +dialog_con        -footer            +listcmds          +mouse_urxvt       -python            +syntax            +user_commands     -xim
+channel           +diff              +fork()            +localmap          +mouse_xterm       +python3           +tag_binary        +vartabs           -xpm
+cindent           +digraphs          +gettext           +lua               +multi_byte        +quickfix          -tag_old_static    +vertsplit         -xsmp
-clientserver      -dnd               -hangul_input      +menu              +multi_lang        +reltime           -tag_any_white     +virtualedit       -xterm_clipboard
+clipboard         -ebcdic            +iconv             +mksession         -mzscheme          +rightleft         -tcl               +visual            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim
     -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.14 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/
5.30.0/lib/perl5/5.30.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -
lpython3.7m -framework CoreFoundation  -lruby.2.6
```
- [x] What **version** of vim-devicons are you using?
  - `0.11.0`
- [x] Are you using vim from the terminal or a GUI vim?
  - Terminal
- [x] Are you using Mac, Linux or Windows?
  - Mac

#### Optional Info

- [x] Provide **screenshots** where appropriate
![image](https://user-images.githubusercontent.com/6378306/61583175-1ed2d880-ab3d-11e9-84d1-b0ee82d776cd.png)

#### Description
The symbol for opened folder in `NERDTree` is not working. As per the [docs](https://github.com/ryanoasis/vim-devicons/wiki/Extra-Configuration#character-mappings) I have the following settings in my `.vimrc`:
```viml
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:DevIconsEnableFoldersOpenClose = 1

let g:DevIconsDefaultFolderOpenSymbol='' " symbol for open folder (f07c)
let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol='' " symbol for closed folder (f07b)
```
It used to work, but lately I have noticed that when a folder is opened it does not get the symbol for open folder. I have tried with different symbols but the result is still the same - no decoration for open folder.

-----
Here a list of all my `vim-devicons` configurations
```viml
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:DevIconsEnableFoldersOpenClose = 1
let g:DevIconsEnableFolderExtensionPatternMatching = 1

let g:DevIconsDefaultFolderOpenSymbol=''
let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol=''

" Custom icons for file extensions
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {} " needed
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['js'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['ts'] = 'ﯤ'
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['json'] = 'ﬥ'

let g:WebDevIconsUnicodeDecorateFileNodesPatternSymbols = {} " needed
let g:WebDevIconsUnicodeDecorateFileNodesPatternSymbols['.test.ts'] = 'ﭧ'

" Custom icons for specific filenames
let g:WebDevIconsUnicodeDecorateFileNodesExactSymbols = {} " needed
let g:WebDevIconsUnicodeDecorateFileNodesExactSymbols['ormconfig.js'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExactSymbols['.env'] = 'ﭩ'
let g:WebDevIconsUnicodeDecorateFileNodesExactSymbols['.editorconfig'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExactSymbols['.npmrc'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExactSymbols['src'] = ''
```

**Comment by xvoidee** [comment]
+1
Doesn't work after one of the last updates (~July1 - ~Aug15). I see only 1 folder icon in NERDTree.

**Comment by PetarMetodiev** [comment]
After further investigation it turns out that `<CR>` is by default mapped to `custom open`. Having said that, when opening folders with `o` (which is by default mapped to `open & close node`), symbols for opened and closed folders are displayed properly.

**Comment by tinchogb** [comment]
Hi @aly199 

As you know I put the following line in my nerdtree.vim file:

`let NERDTreeMapCustomOpen='o'`

But icon folder open/close doesn't show up either.

So, I did what you tell me with the 6 block lines and put it in vim-devicons/nerdtree-plugin/webdevicons.vim like you suggest it ([here](https://github.com/ryanoasis/vim-devicons/pull/281/commits#))

It didn't work for me. I don't know, maybe I'm doing something wrong. Please, if you could help me with all the steps and after that simply start vim with icon nerdtree folder open/close function.

Best,
Martín

**Comment by aly199** [comment]
Maybe you fiddled with something else that is still interfering? Anyways, I'd remove both nerdtree and vim-devicons  plugin folders, reinstall them with your plugin manager, and reapply that patch from the pull request (at line 317, as indicated in the pull request).

Also, you have to have this set at your vim config file:
`let g:DevIconsEnableFoldersOpenClose = 1`

**Comment by tinchogb** [comment]
@aly199 
Thanks for your help but it didn't work removing and reinstalling nerdtree and vim-devicons and then reapply that patch. 
And yes, I have that set on "1" in my vim-devicons config file.

Anyway, I appreciate your help and time @aly199 !

**Comment by aly199** [comment]
@tinchogb, sorry I couldn't be of any help man. But hey, a good rule of thumb is you never set any config inside plugin scripts. Plugin configuration should be done in your vim config file. If you set a variable inside the script, it might get reset further down the code to a default value (actually, that might be what's going on with your config right now).

**Comment by kazukazuinaina** [comment]
@PetarMetodiev 

I tried but this issue was not reproduced.
Please  update `vim-devicons` and `NERDTree` to the latest version

**Comment by PetarMetodiev** [comment]
@kazukazuinaina seems to have been fixed in https://github.com/ryanoasis/vim-devicons/commit/df66de3a1bc062cebc0329ab6fbca465aea5a590 . After updating to the latest versions of both `vim-devicons` and `NERDTree` everything seems to be fine. Thanks!

**Comment by kazukazuinaina** [comment]
@PetarMetodiev : Thanks for reply!

@ryanoasis 
This issue has been resloved. We should close this issue. What do you think?

**Comment by ryanoasis** [comment]
Great to hear. Thanks for attempting to replicate @kazukazuinaina :smiley: 

I think some others here commented on related issues. If anyone else has this issue feel free to reopen.
