### ISSUE TITLE
Error under neovim

### ISSUE THREAD

**Issue by wave-blessed** [ryanoasis/vim-devicons#277]
Hi. I just try to lern vin/neovim and tried to use NERDTree and vim-devicons. It works excellent via vim, but doesn't via neovim.
After :NERDTreeToggle I get this:

Error detected while processing function <SNR>13_lod_cmd[3]..205[2]..206[12]..189[20]..192[8]..156[25]..154[15]..266:
line    4:
E117: Unknown function: NERDTreeWebDevIconsRefreshListener
Error detected while processing function <SNR>13_lod_cmd[3]..205[2]..206[12]..189[20]..192[8]..156:
line   25:
E171: Missing :endif
Error detected while processing function <SNR>13_lod_cmd[3]..205[2]..206:
line   12:
E171: Missing :endif
Press ENTER or type command to continue

and after this very-very bugy NERDTree panel shows.
If commenting `Plug 'ryanoasis/vim-devicons'` — NERDTree works excellent via neovim.

Both vim and neovim do installed NERDTree and vim-devicons by vim-plug plugin manager from their's repositories.
Neovim tested both 3.8 stable and 4 nightly from /neovim/neovim/releases
Windows version. Both console nvim.exe x64 and nvim-qt.exe x86.

**Comment by ryanoasis** [comment]
Thanks @wave-blessed . To be looked at..

**Comment by wave-blessed** [comment]
It seems to be the matter is [here](https://github.com/neovim/neovim/issues/10674)
Everything works screwed if vim-plug configurated in $VIM\runtime\plugin\init.vim
Now I rum my neovim as `path_to\nvim\bin\nvim.exe -u path_to\config\init.vim file_to_edit` and everything works fine.
May be this issue shoud close.

Thank you and sorry to trouble.

**Comment by ryanoasis** [comment]
Thanks for the update @wave-blessed. Sounds like we can close for now
