### ISSUE TITLE
Correctly detect JavaScript modules

### ISSUE THREAD

**Issue by aminnairi** [ryanoasis/vim-devicons#282]
JavaScript modules with extension `.mjs` should be correctly detected as JavaScript modules.

![image](https://user-images.githubusercontent.com/18418459/64728811-275fe380-d4dc-11e9-95a2-f20bcf9d6a6e.png)

See [JavaScript modules](https://v8.dev/features/modules).

**Comment by ryanoasis** [comment]
Thanks @aminnairi good suggestion

**Comment by kazukazuinaina** [comment]
@ryanoasis 

This issue has already been resolved.

**Comment by aminnairi** [comment]
Yes indeed. Working like a charm!

![image](https://user-images.githubusercontent.com/18418459/64907284-9746b780-d6f0-11e9-8a82-919eb2469863.png)

**Comment by kazukazuinaina** [comment]
@ryanoasis @aminnairi 
Thank you!
