### ISSUE TITLE
Add toml file's icon support

### ISSUE THREAD

**Issue by kazukazuinaina** [ryanoasis/vim-devicons#284]
# Overview

In vscode, a gear appears on the toml file icon, but this plugin does not yet support toml files. I thought it would be better to display the gear icon for the toml file.

# ScreenShot

- **On VSCode**
<img width="120" alt="スクリーンショット 2019-09-17 8 02 56" src="https://user-images.githubusercontent.com/36619465/64999126-96489c80-d921-11e9-8d23-a25570fa26c1.png">

- **On vim-devicons**
<img width="110" alt="スクリーンショット 2019-09-17 8 04 36" src="https://user-images.githubusercontent.com/36619465/64999206-d740b100-d921-11e9-9529-ea2e7a7146fb.png">

**Comment by ryanoasis** [comment]
Merged

**Comment by kazukazuinaina** [comment]
Thank you.

**Comment by vimalk78** [comment]
toml icon not visible
on commit 3ee60deaa539360518eaab93a6c701fe9f4d82ef

![image](https://github.com/ryanoasis/vim-devicons/assets/3284044/7f4fc451-29cf-43ef-a101-73a7313fb4f6)
