### ISSUE TITLE
GitLab CI icon

### ISSUE THREAD

**Issue by aminnairi** [ryanoasis/vim-devicons#292]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?

```console
$ vim --version | head -3
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 29 2019 22:27:49)
Included patches: 1-2102
Compiled by Arch Linux
```

- [x] What **version** of vim-devicons are you using?

```
0.11.0
```

- [x] Are you using vim from the terminal or a GUI vim?

From the terminal.

- [x] Are you using Mac, Linux or Windows?

```console
$ uname -a
Linux archlinux 4.19.77-1-lts #1 SMP Sat Oct 5 18:49:03 CEST 2019 x86_64 GNU/Linux
```

#### Optional Info

- [x] Provide **screenshots** where appropriate

![image](https://user-images.githubusercontent.com/18418459/68333029-185e7180-00d8-11ea-98ca-e4936909731b.png)

## Why opening this issue?

IMO the GitLab CI icon should have a better icon. We could use the official image which is an SVG located here: https://docs.gitlab.com/assets/images/gitlab-logo.svg.

For informational purposes, the `.gitlab-ci.yml` is a file located in the root of the git repository hosted on GitLab and is responsible for configuring the continuous integration/continous deployment on a GitLab Pipeline. Documentation can be found here: https://docs.gitlab.com/ee/ci/. Its name will always be the same.

What do you think?

**Comment by kazukazuinaina** [comment]
Thank you to suggest great idea!

I will try to add this feature.
