### ISSUE TITLE
vim-devicons conflicts with hunk-jumping from vim-gitgutter in the NERDTree

### ISSUE THREAD

**Issue by justin-nguyen-1996** [ryanoasis/vim-devicons#294]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?
  - hint: `vim --version`
- [x] What **version** of vim-devicons are you using?
  - hint: `:echo webdevicons#version()`
- [x] Are you using vim from the terminal or a GUI vim?
- [x] Are you using Mac, Linux or Windows?

Vim version: 8.1, huge version with GTK2 GUI
Vim-devicons version: 0.11.0
I am using vim from the terminal and am running a Linux machine (Ubuntu 16.04)

My issue involves being able to jump to the next and previous 'hunks' using `]c` and `[c` through the `vim-gitgutter` plugin. I am able to do this in both the NERDTree viewer AND the code.

As soon as I include the `vim-devicons` plugin, however, even though I can still move between hunks in the code, I can no longer do so in the NERDTree viewer.

I've tested this to (the best of my knowledge) by making a bare vimrc (see attached) that just includes the `NERDTree`, `gitgutter`, `nerdtree-git-plugin`, and the `devicons` plugins. When I comment out the `devicons` plugin, it works fine.

Just to clarify, in the image below, when I place my cursor on line 4 then type `]c` I can move to the next hunk so to speak as marked by the arrows. When I add the `devicons` plugin, this no longer works and the cursor just moves one line down while still printing the message "NERDTree: Jump to next hunk"

![image](https://user-images.githubusercontent.com/18724534/68829878-c5546380-066f-11ea-8b2f-2d345e80f8b9.png)

Great plugin though! Really enjoy using it. Please let me know if you can't recreate the issue

[vim_version.txt](https://github.com/ryanoasis/vim-devicons/files/3844706/vim_version.txt)
[vimrc_bare.txt](https://github.com/ryanoasis/vim-devicons/files/3844746/vimrc_bare.txt)

**Comment by ryanoasis** [comment]
appreciate this report and the details! thanks. I don't have time right now but I'd like to dig in...

**Comment by justin-nguyen-1996** [comment]
No worries! Thanks for getting back to me

**Comment by Xuyuanp** [comment]
@justin-nguyen-1996 , please see [here](https://github.com/Xuyuanp/nerdtree-git-plugin/pull/128)

**Comment by kazukazuinaina** [comment]
@Xuyuanp 

Thanks for your report!

@justin-nguyen-1996 

The nerdtree-git-plugin seems to have incorporated a new patch.
Does updating the plugin reproduce this bug?

**Comment by kazukazuinaina** [comment]
No reply. I close this issue.
If you have any problems, feel free to reopen this issue.
