### ISSUE TITLE
What is the .vimrc configuration for the showing result in the screeshots example?

### ISSUE THREAD

**Issue by jiangjianshan** [ryanoasis/vim-devicons#297]
#### Required Info
- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [8.2] What **version** of vim are you using?
  - hint: `vim --version`
- [0.11.0] What **version** of vim-devicons are you using?
  - hint: `:echo webdevicons#version()`
- [both] Are you using vim from the terminal or a GUI vim?
- [all] Are you using Mac, Linux or Windows?

#### Optional Info
- [x] Provide **screenshots** where appropriate
![image](https://user-images.githubusercontent.com/20179047/73541689-063d6680-446e-11ea-8c62-7a1e817185c8.png)

Hello, 
    What is the .vimrc configuration for the screenshot showing at https://github.com/ryanoasis/vim-devicons/wiki/screenshots? After I install the nerd font from patch by myself or even download from https://github.com/ryanoasis/nerd-fonts, the only can show some part of icons but not as the one seen at screenshot at t vim-devicons/wiki/screenshots.  
    Does the .vimrc configuration use some lines like 
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {}
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['go'] = 'ﳑ'
    to add the glyph to match the filetype? I don't know why I can't get the showing result as the screenshots from https://github.com/ryanoasis/vim-devicons/wiki/screenshots.

**Comment by ChrisMGeo** [comment]
Yeah, I think that's pretty much it, to get the correct glyphs do something like this

1.  Go to your vimrc using vim, then write the following:
```vim
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {}
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['whatever_extension'] = '#'
```
2. We replace the # with the glyph for the icon. In **INSERT MODE**, Press control+v, then type u and then type the code for the glyph in your font, which can be found [here](https://www.nerdfonts.com/cheat-sheet), and is the code in the bottom right, for example, e62e for nf-custom-electron.
3. Voila! You will notice a glyph in the editor, which will be used for other plugins like NERDTree.

NOTE: For folders, you do something similar
```vim
let g:DevIconsEnableFoldersOpenClose = 1 "Enables different glyphs for open and closed folders
let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = '#' "Symbol for closed folder
let g:DevIconsDefaultFolderOpenSymbol = '#' " Symbol for open folder
```

**Comment by ryanoasis** [comment]
@jiangjianshan, I believe I think @ChrisMGeo this very well (thanks!)

going to close this for now, feel free to re-open if there are still doubts.
