### ISSUE TITLE
There is no icons showing for vim-startify

### ISSUE THREAD

**Issue by jiangjianshan** [ryanoasis/vim-devicons#298]
#### Requirements

If you are **not** sure whether or not what you are reporting is actually an issue **or** you have a general question please message in the [Gitter Chat Room](https://gitter.im/ryanoasis/vim-devicons)

These items you must provide answers to. Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and _may_ choose to close the issue until there is enough information.

Please acknowledge that you understand by marking off the following list items below with an 'x'

_--- ✂ snip ✂ --- Delete this line and all of the ^above^ after reading and before submitting your issue please --- ✂ snip ✂ ---_

#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [8.2] What **version** of vim are you using?
  - hint: `vim --version`
- [0.11.0] What **version** of vim-devicons are you using?
  - hint: `:echo webdevicons#version()`
- [both] Are you using vim from the terminal or a GUI vim?
- [all] Are you using Mac, Linux or Windows?

#### Optional Info

- [x] Provide **screenshots** where appropriate
![image](https://user-images.githubusercontent.com/20179047/72044547-f5765680-32ee-11ea-8561-234c30d59ab7.png)

Hello, 

      When I directly open GVim without open any file, it will show the screen created by vim-startify. I can't see any icons for it. But the icons I can see them on NERDTree windows. The setting at my .vimrc is here:

set encoding=utf-8
if has('win32')
    set langmenu=zh_CN.UTF-8
    set guifont=Consolas\ NF:h11
else
    set langmenu=en_US.UTF-8
    set guifont=Consolas\ Nerd\ Font\ 13
endif

" -------------------------------------------------------------------
" => vim-devicons
" -------------------------------------------------------------------
" loading the plugin
let g:webdevicons_enable = 1
" adding the flags to NERDTree
let g:webdevicons_enable_nerdtree = 1
" adding to vim-airline's tabline
let g:webdevicons_enable_airline_tabline = 1
" adding to vim-airline's statusline
let g:webdevicons_enable_airline_statusline = 1
" adding to vim-startify screen
let g:webdevicons_enable_startify = 1
" turn on/off file node glyph decorations (not particularly useful)
let g:WebDevIconsUnicodeDecorateFileNodes = 1
" use double-width(1) or single-width(0) glyphs
" only manipulates padding, has no effect on terminal or set(guifont) font
let g:WebDevIconsUnicodeGlyphDoubleWidth = 1
" whether or not to show the nerdtree brackets around flags
let g:webdevicons_conceal_nerdtree_brackets = 1
" enable folder/directory glyph flag (disabled by default with 0)
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
" enable open and close folder/directory glyph flags (disabled by default with 0)
let g:DevIconsEnableFoldersOpenClose = 1

if has('macunix')
    let g:WebDevIconsOS = 'Darwin'
endif

**Comment by jiangjianshan** [comment]
Hello,

     After I put the vim-devicons at the last postition on the plugin loading list, it work now.

**Comment by Young1783** [comment]
Thank you !!! This is very helpful to me!!!
