### ISSUE TITLE
Unable to see the characters on Neovim using Windows 10 Terminal

### ISSUE THREAD

**Issue by andregpss** [ryanoasis/vim-devicons#300]
#### Required Info
- [x] `VimDevIcons` is the last loaded vim plugin?
   - Yes
- [x] What **version** of vim are you using?
  - Neo-Vim 0.4.3
- [x] What **version** of vim-devicons are you using?
   - 0.11.0
- [x] Are you using vim from the terminal or a GUI vim?
   - terminal
- [x] Are you using Mac, Linux or Windows?
   - Linux ubuntu over Windows WSL

I have followed all the steps on [FAQ "It's not working at all" section](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting#why-isnt-it-working-how-come-i-dont-see-any-icons) and i am unable to see icons when i type: `:echo g:WebDevIconsUnicodeDecorateFileNodesDefaultSymbol`

All the other checks work as expected. For example, when i type `:set guifont?`, the answer is: `guifont=Droid Sans Mono for Powerline Plus Nerd File Types 11`

On init.vim, i use: `set guifont=Droid\ Sans\ Mono\ for\ Powerline\ Plus\ Nerd\ File\ Types\ 11`

Also, i have tried:` set guifont=Fira\ Code:h12`

**Comment by Jorgexyx** [comment]
Had similar issue. You might need to manually install the fonts. https://github.com/ryanoasis/nerd-fonts.

Issue was fixed after installing  font-hack-nerd-font for mac

**Comment by ryanoasis** [comment]
you mentioned this is "terminal" vim. are you sure your terminal emulator has a Nerd Font set?

**Comment by kazukazuinaina** [comment]
I feel this problem is similar to #269

**Comment by andregpss** [comment]
I think i have found a solution for using `Liberation Mono NF` nerd font on NeoVim over Windows terminal. I still did not search for a solution that works on Linux.

I just executed the following PowerShell script (i don't remember where i've found it) and then changed the font on the Windows Terminal (right click on the title bar -> properties -> font):
[Power Shell script](https://github.com/ryanoasis/vim-devicons/files/4287085/patchedfonts.zip)

It was not necessary to do any change on my `.vimrc`

Here is a screenshot of a `Haskell `project:
![image](https://user-images.githubusercontent.com/24927386/75877343-3f168580-5df6-11ea-84d2-1d15fca0a661.png)

**Comment by kazukazuinaina** [comment]
Thanks for report. @andregpss 
As you can see in the screenshot, the icons appear to be displayed correctly. Can I close this question?

**Comment by andregpss** [comment]
> Can I close this issue?

Yes! I just suggest that you change the title of this current thread inserting that the problem is on Windows 10 Terminal. Something like: "Unable to see the characters on Neo-Vim using Windows 10 Terminal"

**Comment by kazukazuinaina** [comment]
Hmm?

I can see that vim-devicons is working fine from your screenshot.
What is the OS and terminal on the screenshot?

>  I just suggest that you change the title of this current thread inserting that the problem is on Windows 10 Terminal. Something like: "Unable to see the characters on Neo-Vim using Windows 10 Terminal"

Does that mean that the problem has not been solved?

**Comment by andregpss** [comment]
> Is it mean,
> 
> 1. fix this issue's titie >> "Unable to see the characters on Neo-Vim using Windows 10 Terminal"
> 2. close this issue
> 
> Is this wrong?

No. It is correct. I suggested for you to perform that two steps.

**Comment by kazukazuinaina** [comment]
Ok, I got it.
Thanks!
