### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by aminnairi** [ryanoasis/vim-devicons#304]
WebP is an image format which is developed by Google and starts to have more and more adoption in the browser.

Unfortunately, the default icon is used. I guess the image icon can be used since there is no official icon for WebP.

#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?
  - hint: `vim --version`

```console
$ vim --version | head -1
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 26 2020 11:45:38)
```

- [x] What **version** of vim-devicons are you using?
  - hint: `:echo webdevicons#version()`

```
0.11.0
```

- [x] Are you using vim from the terminal or a GUI vim?

I'm using Vim from the terminal.

- [x] Are you using Mac, Linux or Windows?

```console
$ uname -a
Linux 5.5.4-arch1-1 #1 SMP PREEMPT Sat, 15 Feb 2020 00:36:29 +0000 x86_64 GNU/Linux
```

#### Optional Info

- [x] Provide **screenshots** where appropriate

![image](https://user-images.githubusercontent.com/18418459/75037105-b291cc00-54b3-11ea-80e4-577a6b90a6dc.png)

**Comment by kazukazuinaina** [comment]
Thanks, I think it is good idea.
What do you think? @ryanoasis

**Comment by ryanoasis** [comment]
Thanks. Good suggestion @aminnairi 

@kazukazuinaina I agree and thanks for triaging

**Comment by ryanoasis** [comment]
now merged, thanks both of you
