### ISSUE TITLE
Folder icon missing in VimR

### ISSUE THREAD

**Issue by kuntau** [ryanoasis/vim-devicons#305]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin? **Yes**
- [x] What **version** of vim are you using? **NVIM v0.4.3**
  - hint: `vim --version`
- [x] What **version** of vim-devicons are you using? **0.11.0**
  - hint: `:echo webdevicons#version()`
- [x] Are you using vim from the terminal or a GUI vim? **VimR... so  GUI**
- [x] Are you using Mac, Linux or Windows? **Mac**

#### Optional Info

I'm using coc-explorer which support nerd icons. It work fine on terminal so I'm not sure what's the problem.

- [x ] Provide **screenshots** where appropriate

![Screenshot 2020-03-03 11 00 07](https://user-images.githubusercontent.com/327489/75740293-36fd0e00-5d42-11ea-9e61-d78e4242e0cf.png)

**Comment by kazukazuinaina** [comment]
What is coc-explorer?
Is this? > https://github.com/weirongxu/coc-explorer

**Comment by kazukazuinaina** [comment]
If you use > https://github.com/weirongxu/coc-explorer and you want to use `Nerdfont`,
you should write these config in `cocsettings.json`.

Do you write these config?

## Like this

`explorer.icon.enableNerdfont: Enable nerdfont. type: boolean`
Default:
```
false
```

It is offical screen shot

<img width="930" alt="スクリーンショット 2020-03-04 16 17 27" src="https://user-images.githubusercontent.com/36619465/75854626-009fbb80-5e34-11ea-919b-d5f07b7d0adf.png">

**Comment by kuntau** [comment]
of course I have it enabled otherwise other icons won't show up.. only folder icons missing.. Please see my screenshot

**Comment by kazukazuinaina** [comment]
you mentioned this is "gui" vim. do you write this config in your vimrc or init.vim?

## Like this

```
set guifont=Hack\ Nerd\ Font
```

**Comment by kazukazuinaina** [comment]
Either way, this seems like a problem with coc-explorer...
I seem to have nothing to do with vim-devicons.
Why don't you issue an issue with coc-explorer?
What do you think? @ryanoasis
