### ISSUE TITLE
GVim very slow when testing the lightline snippet from the docs

### ISSUE THREAD

**Issue by ntropia2** [ryanoasis/vim-devicons#312]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?   8.0
- [x] What **version** of vim-devicons are you using? 0.11
  - [x] Are you using vim from the terminal or a GUI vim? Gvim (from distro repository)
- [x] Are you using Mac, Linux or Windows? Linux (Kubuntu 18.04.4)
#### Optional Info

- [ ] Provide **screenshots** where appropriate

I just tested the example code for Lightline (section: devicons-lightline-setup) to enable the icons in the status and it works perfectly fine. I did not customize LightLine and I am using only the code in the example in my vimrc.
When I enable the two functions in the example (MyFiletype and MyFileFormat), the gui becomes terribly slow, barely usable.

For reference, I use the icons in NerdTree without any problem.
This is the list of all the plugins I use:

Plug 'tpope/vim-sensible'
Plug 'scrooloose/nerdtree'
Plug 'junegunn/goyo.vim'
Plug 'mhinz/vim-startify'
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'itchyny/lightline.vim'
Plug 'Shougo/echodoc.vim'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
Plug 'ervandew/supertab'
Plug 'Yggdroot/hiPairs'
Plug 'Yggdroot/indentLine'
Plug 'ryanoasis/vim-devicons'

**Comment by doronbehar** [comment]
I experience a similar issue tested on Neovim with airline and devicons **only** and I've bisected the issue to: https://github.com/ryanoasis/vim-devicons/pull/306 - right before it files load and are edited smoothly and right after it editing is sssssssslow.. Probably similar to what @petobens [was experiencing](https://github.com/ryanoasis/vim-devicons/pull/306#issuecomment-596148581).

Makes sense considering there's an external command there that's probably being run on every update of a status line or whatever. 

cc @Innei.

**Comment by ryanoasis** [comment]
@doronbehar is it resolved with #310 ?

**Comment by doronbehar** [comment]
Yes :).

**Comment by ntropia2** [comment]
I confirm it works on on my Vim, too!
Thanks!
