### ISSUE TITLE
Robots.txt icon

### ISSUE THREAD

**Issue by aminnairi** [ryanoasis/vim-devicons#318]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?

```console
$ vim --version | head -1
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  1 2020 17:21:03)
```

- [x] What **version** of vim-devicons are you using?

```
0.11.0
```

- [x] Are you using vim from the terminal or a GUI vim?

I'm using VIM from the terminal.

- [x] Are you using Mac, Linux or Windows?

```console
$ uname -a
Linux archlinux 5.4.28-1-lts #1 SMP Wed, 25 Mar 2020 13:04:22 +0000 x86_64 GNU/Linux
```

#### Optional Info

- [x] Provide **screenshots** where appropriate

![image](https://user-images.githubusercontent.com/18418459/79574883-25d54a00-80c1-11ea-98e8-b238ba1e1fbc.png)

#### Additional context

I think we can get inspiration from this little icon from VSCode Icons:

https://github.com/JimiC/vscode-icons/blob/84154ad7330a98e1288e8b60377957f8743c0d03/icons/file_type_robots.svg

**Comment by ryanoasis** [comment]
Nice. Well my proposal would be

![Screenshot_20200417-064857_Chrome](https://user-images.githubusercontent.com/8083459/79576212-c868db00-8077-11ea-98be-89de39dd6410.jpg)

**Comment by youyiqin** [comment]
How to add a new icon?Can we do that?

**Comment by ryanoasis** [comment]
Closing with #413 merged

Thanks all.
