### ISSUE TITLE
Certificate files (.pem) icon

### ISSUE THREAD

**Issue by aminnairi** [ryanoasis/vim-devicons#319]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?

```console
$ vim --version | head -1
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  1 2020 17:21:03)
```

- [x] What **version** of vim-devicons are you using?

```
0.11.0
```

- [x] Are you using vim from the terminal or a GUI vim?

I'm using VIM from the terminal.

- [x] Are you using Mac, Linux or Windows?

```console
$ uname -a
Linux archlinux 5.4.28-1-lts #1 SMP Wed, 25 Mar 2020 13:04:22 +0000 x86_64 GNU/Linux
```

#### Optional Info

- [x] Provide **screenshots** where appropriate

![image](https://user-images.githubusercontent.com/18418459/79575446-199dbc80-80c2-11ea-9a30-d766284ded33.png)

#### Additional context

In my opinion, this SVG icon would be perfect:

https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/OOjs_UI_icon_key.svg/1024px-OOjs_UI_icon_key.svg.png

**Comment by kazukazuinaina** [comment]
I think it is good idea.
What do you think? @ryanoasis

**Comment by ryanoasis** [comment]
Good suggestion, this one is pretty much a mirror image of your suggestion:

![Selection_047](https://user-images.githubusercontent.com/8083459/80893122-54881e80-8c84-11ea-8b6a-f730ce024748.png)

**Comment by SarveshMD** [comment]
@ryanoasis I think I can work on this issue. 

Option 1
![.pem icon choice 1](https://user-images.githubusercontent.com/8083459/80893122-54881e80-8c84-11ea-8b6a-f730ce024748.png ".pem icon choice 1").
Option 2
![.pem icon choice 2](https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/OOjs_UI_icon_key.svg/200px-OOjs_UI_icon_key.svg.png ".pem icon choice 2")

Shall I use option 1 or option 2 ?

PS :  It would be helpful if you create a small cheat sheet for how to add support for a file type.

**Comment by SarveshMD** [comment]
I've got my pr #412. Check it out!

**Comment by ryanoasis** [comment]
Sorry for the delay. Thanks for the contribution.
