### ISSUE TITLE
Makefile icon

### ISSUE THREAD

**Issue by aminnairi** [ryanoasis/vim-devicons#320]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?

```console
$ vim --version | head -1
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  1 2020 17:21:03)
```

- [x] What **version** of vim-devicons are you using?

```
0.11.0
```

- [x] Are you using vim from the terminal or a GUI vim?

I'm using VIM from the terminal.

- [x] Are you using Mac, Linux or Windows?

```console
$ uname -a
Linux archlinux 5.4.28-1-lts #1 SMP Wed, 25 Mar 2020 13:04:22 +0000 x86_64 GNU/Linux
```

#### Optional Info

- [x] Provide **screenshots** where appropriate

![image](https://user-images.githubusercontent.com/18418459/79575911-cc6e1a80-80c2-11ea-959b-3a3e35e91fad.png)

#### Additional context

I think we can use the artwork from the GNU project itself which is already an SVG image:

https://www.gnu.org/graphics/empowered-by-gnu.svg

**Careful!** There are actually two valid form for a makefile:

```console
$ touch makefile
```

Or

```console
$ touch Makefile
```

Notice the capitalized M letter. I'm not sure if the engine is case sensitive or not be just to be sure I add this note here.

**Comment by kazukazuinaina** [comment]
This issue has already been resolved.
Please see this PR.

> https://github.com/ryanoasis/vim-devicons/pull/313

**Comment by kazukazuinaina** [comment]
I close this issue.
If you have a problem, open the issue again or create a new one.
