### ISSUE TITLE
PWA Manifest (.webmanifest) icon

### ISSUE THREAD

**Issue by aminnairi** [ryanoasis/vim-devicons#321]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?

```console
$ vim --version | head -1
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  1 2020 17:21:03)
```

- [x] What **version** of vim-devicons are you using?

```
0.11.0
```

- [x] Are you using vim from the terminal or a GUI vim?

I'm using VIM from the terminal.

- [x] Are you using Mac, Linux or Windows?

```console
$ uname -a
Linux archlinux 5.4.28-1-lts #1 SMP Wed, 25 Mar 2020 13:04:22 +0000 x86_64 GNU/Linux
```

#### Optional Info

- [x] Provide **screenshots** where appropriate

![image](https://user-images.githubusercontent.com/18418459/79868290-fd5e9000-83df-11ea-880f-3ca463b12aca.png)

#### Additional context

`webmanifest` is the extension used in the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/Manifest) for PWA manifest files. Since it is a JSON file, it could have the JSON icon. This is also an officially supported type according to the [W3C](https://w3c.github.io/manifest/#media-type-registration) that is served with the `application/manifest+json` MIME type.

What do you think?

**Comment by kazukazuinaina** [comment]
Thanks for suggestion.
I created PR, please check.

**Comment by ryanoasis** [comment]
#325 merged. thanks.
