### ISSUE TITLE
Yarn package manager lockfile (yarn.lock) icon

### ISSUE THREAD

**Issue by aminnairi** [ryanoasis/vim-devicons#326]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?

```console
$ vim --version | head -1
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  1 2020 17:21:03)
```

- [x] What **version** of vim-devicons are you using?

```
0.11.0
```

- [x] Are you using vim from the terminal or a GUI vim?

I'm using vim from the terminal.

- [x] Are you using Mac, Linux or Windows?

```console
$ uname -a
Linux archlinux 5.4.28-1-lts #1 SMP Wed, 25 Mar 2020 13:04:22 +0000 x86_64 GNU/Linux
```

#### Optional Info

- [x] Provide **screenshots** where appropriate

![image](https://user-images.githubusercontent.com/18418459/80503558-52674c80-8972-11ea-85ea-49914ba4bd5f.png)

## Additional Context

I found one SVG icon that could fit the official Yarnpkg logo [here](https://vecta.io/symbols/103/brands-ya-yz/11/yarn-icon). Not sure if this is a good one I'll let you decide on which one you want to use but I found the one used by VSCode better since there is no surrounding around the cat [here](https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_yarn.svg?sanitize=true).

Since this is always the same filename for 99% of people, it would be great to have the little cat icon instead of the default one.

**Comment by ryanoasis** [comment]
Nerd Fonts doesn't currently have the yarn logo at all.. I wonder if something 'cat' like would work for a stop gap measure for now, e.g.

![Selection_043](https://user-images.githubusercontent.com/8083459/80892916-a92a9a00-8c82-11ea-8eed-b4135e172bbb.png)

**Comment by kazukazuinaina** [comment]
Is this really necessary?
I don't even have an icon in Gemfile.lock.
Forcing an icon on them can be confusing to users.

**Comment by kazukazuinaina** [comment]
I am closing this issue as I have not received a reply. If you have problems, reopen or create a new issue. Thank you.
