### ISSUE TITLE
bracket issue

### ISSUE THREAD

**Issue by ask1234560** [ryanoasis/vim-devicons#327]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of __nvim__ are you using?
  -  NVIM v0.4.3
- [x] What **version** of vim-devicons are you using?
  - 0.11.0
- [x] Are you using vim from the terminal or a GUI vim?
- nvim from terminal 

- [x] Are you using Mac, Linux or Windows?
- uses linux (arch)

#### Optional Info
nvim [config file](https://github.com/ask1234560/neovim-config/blob/master/init.vim)
- [x] Provide **screenshots** where appropriate

![Screenshot_from_2020-04-30_19:12:53](https://user-images.githubusercontent.com/25929911/80717974-2df8a500-8b17-11ea-9624-c53a76be1bf5.png)

when i used this commit 58e57b6eeb407dba7, single bracket remains
![Screenshot_from_2020-04-30_19:23:45](https://user-images.githubusercontent.com/25929911/80718793-39000500-8b18-11ea-9bf6-07e03c4b85ad.png)

i went deeper and found this
![Screenshot_from_2020-04-30_19:26:19](https://user-images.githubusercontent.com/25929911/80719043-88463580-8b18-11ea-99e6-36a68e356f3d.png)

anyone please help

**Comment by jim-at-jibba** [comment]
Same issue for me too

**Comment by ask1234560** [comment]
@jim-at-jibba u r using vim or neovim

**Comment by jim-at-jibba** [comment]
@ask1234560 Hey, it turns out it was clashing with a bracket coloriser I was using. Sorry for that.

**Comment by ask1234560** [comment]
lol , i also have https://github.com/luochen1990/rainbow which causes the issue.

**Comment by jim-at-jibba** [comment]
@ask1234560 I actually swapped to this one and it works fine. You can tell it to ignore Nerdtree

Add this to your `vimrc/init.vim`
```
let g:rainbow_conf = {
  \    'separately': {
  \       'nerdtree': 0
  \    }
  \}
```

Hope that helps

**Comment by ask1234560** [comment]
> @ask1234560 I actually swapped to the one you are using and it works fine. You can tell it to ignore Nerdtree
> 
> Add this to your `vimrc/init.vim`
> 
> ```
> let g:rainbow_conf = {
>   \    'separately': {
>   \       'nerdtree': 0
>   \    }
>   \}
> ```
> 
> Hope that helps

That fixes it,
![Screenshot_from_2020-05-01_23:09:08](https://user-images.githubusercontent.com/25929911/80827236-3cbb8680-8c01-11ea-9b7e-2dd27e3a9cd9.png)

but by changing vim-devicons plugin itself,
```
diff --git a/plugin/webdevicons.vim b/plugin/webdevicons.vim
index 1090e9f..8bb6958 100644
--- a/plugin/webdevicons.vim
+++ b/plugin/webdevicons.vim
@@ -357,8 +357,8 @@ function! s:setSyntax()
   if g:webdevicons_enable_nerdtree == 1 && g:webdevicons_conceal_nerdtree_brackets == 1
     augroup webdevicons_conceal_nerdtree_brackets
       au!
-      autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\]" contained conceal containedin=ALL
-      autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\[" contained conceal containedin=ALL
+      autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\]" contained conceal containedin=NERDTreeFlags
+      autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\[" contained conceal containedin=NERDTreeFlags
       autocmd FileType nerdtree setlocal conceallevel=3
       autocmd FileType nerdtree setlocal concealcursor=nvic
     augroup END
```
![Screenshot_from_2020-05-01_23:10:45](https://user-images.githubusercontent.com/25929911/80827793-e438b900-8c01-11ea-8d96-2f3d920cfcdb.png)

glyph color also changed, i like it this way

**Comment by svnty** [comment]
I have the same issue and the separately config hasn't fixed it

Using plguins vim-devicons and vim-rainbow the plugins collide and I have half rainbow folder brackets

```Vim
Plug 'ryanoasis/vim-devicons'
Plug 'frazrepo/vim-rainbow'
```

~/.vimrc

![Screen Shot 2020-06-08 at 6 04 50 pm](https://user-images.githubusercontent.com/47465827/84006728-90fd1780-a9b2-11ea-947c-db2de77fbab5.png)

**Comment by EtiamNullam** [comment]
@svnty the config snippet suggested by @jim-at-jibba works for `luochen1990/rainbow` plugin. Thanks.

For `frazrepo/vim-rainbow` maybe something like this will work instead:
```viml
let g:rainbow_load_separately = [
    \ [ 'nerdtree', 0 ],
    \ ]
```
(^According to: https://github.com/frazrepo/vim-rainbow#advanced-configuration)

or
```viml
let g:rainbow_load_separately = [
    \ { 'nerdtree': 0 },
    \ ]
```
