### ISSUE TITLE
Newly added files do not have icons next to them until refreshing nerd tree.

### ISSUE THREAD

**Issue by jordwalke** [ryanoasis/vim-devicons#33]
If you add new files through NERDTree (press m then a) the newly added files do not have icons next to them.

**Comment by ryanoasis** [comment]
:+1:  Ah, I have seen this before and I never put a ticket. At least I think it is pre-existing v0.4.0 so I am glad I didn't break that

**Comment by ryanoasis** [comment]
@jordwalke 
Sorry I keep pushing this off but bugs and easier fixes come up. I actually did delve into this but got a bit stuck, I might even need to submit a PR for NERDTree itself for listener on new nodes
