### ISSUE TITLE
!

### ISSUE THREAD

**Issue by arturfil** [ryanoasis/vim-devicons#331]
#### Requirements

If you are **not** sure whether or not what you are reporting is actually an issue **or** you have a general question please message in the [Gitter Chat Room](https://gitter.im/ryanoasis/vim-devicons)

These items you must provide answers to. Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and _may_ choose to close the issue until there is enough information.

Please acknowledge that you understand by marking off the following list items below with an 'x'

_--- ✂ snip ✂ --- Delete this line and all of the ^above^ after reading and before submitting your issue please --- ✂ snip ✂ ---_

#### Required Info

- [ ] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [ ] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [ ] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [ ] `VimDevIcons` is the last loaded vim plugin?
- [ ] What **version** of vim are you using?
  - hint: `vim --version`
- [ ] What **version** of vim-devicons are you using?
  - hint: `:echo webdevicons#version()`
- [ ] Are you using vim from the terminal or a GUI vim?
- [ ] Are you using Mac, Linux or Windows?

#### Optional Info

- [ ] Provide **screenshots** where appropriate

**Comment by kazukazuinaina** [comment]
Close this issue. If you have any problems, please follow the issue_templete and report the problem again with an appropriate title.
