### ISSUE TITLE
Feature Request: Ferris the Rustacean icon

### ISSUE THREAD

**Issue by pieps** [ryanoasis/vim-devicons#348]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [ ] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/pieps/neovim/build/config -I/home/pieps/neovim/src -I/home/pieps/neovim/.deps/usr/include -I/usr/include -I/home/pieps/neovim/build/src/nvim/auto -I/home/pieps/neovim/build/include
Compiled by pieps@[redacted]

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "[redacted]"

Run :checkhealth for more info
```
- [x] What **version** of vim-devicons are you using?
  0.11.0
- [x] Are you using vim from the terminal or a GUI vim?
Terminal
- [x] Are you using Mac, Linux or Windows?
Linux

#### Optional Info
The official Rust icon, [``](https://www.rust-lang.org/logos/rust-logo-blk.svg), doesn't really register for me quickly when I see it, but [Ferris the Rustacean](https://rustacean.net/) does! I'd love to add Ferris to the list of icons in this fantastic icon set.

I've got a pull request open in vorillaz' repo (vorillaz/devicons#147), but it looks like there hasn't been any activity in that repo for quite a while.

- [x] Provide **screenshots** where appropriate
![Monochromed SVG of Ferris](https://raw.githubusercontent.com/vorillaz/devicons/3a4a853d00c39cb91f708dafb151537380d0ce1a/ferris.svg)

![Source material](https://rustacean.net/assets/rustacean-flat-noshadow.svg)

[IcoMoon JSON](https://raw.githubusercontent.com/vorillaz/devicons/3a4a853d00c39cb91f708dafb151537380d0ce1a/ferris.json)

**Comment by kazukazuinaina** [comment]
I don't think this is currently possible because nerdfont does not support this icon.

**Comment by pieps** [comment]
Aw crud, right you are. Sorry about that. I got excited after seeing #318 and failed to check if this repo contains the icons themselves.

I realize this isn't the nerd-fonts repo, but given that valloric/devicons seems to be out of commission, would you happen to have any recommendations for icon repos that [nerd-fonts](http://github.com/ryanoasis/nerd-fonts) pulls from where Ferris might fit?

**Comment by kazukazuinaina** [comment]
I'm not sure.
Anyway, there's nothing vim-devicons can do to any fonts.
