### ISSUE TITLE
GitHub Attributes (.gitattributes) icon

### ISSUE THREAD

**Issue by aminnairi** [ryanoasis/vim-devicons#354]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?

```console
$ vim --version | head -1
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 21 2020 16:11:23)
```

- [x] What **version** of vim-devicons are you using?

```console
0.11.0
```

- [x] Are you using vim from the terminal or a GUI vim?

I'm using Vim from the terminal.

- [x] Are you using Mac, Linux or Windows?

```console
$ uname -a
Linux archlinux 5.4.52-1-lts #1 SMP Thu, 16 Jul 2020 19:35:06 +0000 x86_64 GNU/Linux1111
```

#### Optional Info

- [x] Provide **screenshots** where appropriate
![webdevicons](https://user-images.githubusercontent.com/18418459/90281790-8016c980-de6d-11ea-9a6d-b662993b225d.jpg)

Hi there, my guess is that the icon could be the same at the one used for the `.gitignore` file. What do you think?

**Comment by kazukazuinaina** [comment]
Thanks, I think it is good idea.
