### ISSUE TITLE
Yarn error log icon

### ISSUE THREAD

**Issue by aminnairi** [ryanoasis/vim-devicons#358]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?
  - hint: `vim --version`

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 21 2020 16:11:23)
```

- [x] What **version** of vim-devicons are you using?
  - hint: `:echo webdevicons#version()`

```
0.11.0
```

- [x] Are you using vim from the terminal or a GUI vim?

I'm using Vim from the terminal.

- [x] Are you using Mac, Linux or Windows?

I'm using Linux.

#### Optional Info

- [x] Provide **screenshots** where appropriate

![vim-devicons-issue](https://user-images.githubusercontent.com/18418459/91634673-596e9c00-e9f2-11ea-99dc-1b6e8a2e2550.png)

The icon could simply be the same that will be used for the Yarn lockfile. I'll open an issue once this is done for the color in https://github.com/tiagofumo/vim-nerdtree-syntax-highlight

**Comment by kazukazuinaina** [comment]
I don't think this is necessary.
Because it's a log file. I don't see why it's only for yarn.

**Comment by kazukazuinaina** [comment]
No reply, close.
