### ISSUE TITLE
.tex icon doesn't align properly

### ISSUE THREAD

**Issue by ghost** [ryanoasis/vim-devicons#367]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin? Yes
- [x] What **version** of vim are you using? Neovim v0.4.4
- [x] What **version** of vim-devicons are you using? 0.11.0
- [x] Are you using vim from the terminal or a GUI vim? Terminal, Tilix
- [x] Are you using Mac, Linux or Windows? Linux

#### Optional Info

- [x] Provide **screenshots** where appropriate

![webdevicons](https://user-images.githubusercontent.com/72464749/95893834-bf7f6a80-0d77-11eb-8b43-00d8c58c8e2d.png)

As seen in the screenshot, the .tex icon misaligns to the right edge of the statusline rather than being right next to the filetype "tex" as I've configured it. I'm using lightline.vim

**Comment by kazukazuinaina** [comment]
This user is not exists.
I closed this issue.
