### ISSUE TITLE
Showing Mandarin instead of real font

### ISSUE THREAD

**Issue by x3rxe5** [ryanoasis/vim-devicons#368]
- [X] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [X] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [X] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [X] `VimDevIcons` is the last loaded vim plugin?

- [X] What **version** of vim are you using?
  nvim v0.4.3
- [X] What **version** of vim-devicons are you using?
  - hint: 0.11.0
- [X] Are you using vim from the terminal or a GUI vim? -> 
 Terminal
- [X] Are you using Mac, Linux or Windows?
Pop-OS
#### Optional Info

- [X] Provide **screenshots** where appropriate

![ERROR](https://user-images.githubusercontent.com/45236447/96256505-6c572300-0fd6-11eb-9f9a-8ef9a74bd03e.png)

**Comment by gamarobert** [comment]
Having the same issue, also in Pop OS. However most icons show up besides js file extensions for some reason and all other fonts besides "Hack" font make my text in terminal look weird.

**Comment by ousszizou** [comment]
Having the same issue, All icons appear well just JavaScript icon.

**Comment by ryanoasis** [comment]
Hmm can you verify that the correct font is being used?

Please refer to https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting#why-isnt-it-working-how-come-i-dont-see-any-icons to see if it's any help.

**Comment by mrkvn** [comment]
Ensure that you're using a [NERD patched font](https://github.com/ryanoasis/nerd-fonts#patched-fonts).
- Download font
- Move downloaded fonts to `~/.fonts`
- run `fc-cache -fv`

**Comment by mrkvn** [comment]
Worked for me in Ubuntu but when I installed Pop OS, I got the same issue. Did you solve the problem?

**Comment by mrkvn** [comment]
Solved it by using alacritty as my terminal. Configured to use [Monaco Nerd Font](https://github.com/Karmenzind/monaco-nerd-fonts) on the `~/.config/alacritty/alacritty.yml` file.

```
# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: "Monaco Nerd Font"
    style: Regular
```

Not sure why Monaco Nerd Font is not showing as option in gnome-terminal

**Comment by JwanKhalaf** [comment]
Hello :wave:

I am just getting started with VIM and NerdTree. I would like to have these dev icons, but I do not want to change my color scheme's font.

I'm using the `gruvbox` color scheme. If I install additional fonts, wouldn't that affect my `gruvbox` color scheme?

Right now, this is what I see:

![image](https://user-images.githubusercontent.com/42877376/108872521-28160800-75f2-11eb-8bea-13003cf046c9.png)

**Comment by mrkvn** [comment]
You need to patch your font or probably it's already [here](https://github.com/ryanoasis/nerd-fonts). The important thing is, you need to have a Nerd patched font.

**Comment by kazukazuinaina** [comment]
No progress?

**Comment by kazukazuinaina** [comment]
If you have any problems, please feel free to resume or create a new problem.

close.
