### ISSUE TITLE
No display for the directory level using with NerdTree

### ISSUE THREAD

**Issue by ghost** [ryanoasis/vim-devicons#369]
![1603382979797](https://user-images.githubusercontent.com/25000315/96901393-c7e94b00-14c5-11eb-9132-9d278da67c11.jpg)
![1603383053455](https://user-images.githubusercontent.com/25000315/96901419-ce77c280-14c5-11eb-973f-cc6cf47ccc45.jpg)

**Comment by ryanoasis** [comment]
thanks but can you please provide more details? please fill out the issue template

**Comment by kazukazuinaina** [comment]
No reply?

**Comment by ryanoasis** [comment]
User is now a ghost. Closing
