### ISSUE TITLE
How to color the icons on the vim default statusline

### ISSUE THREAD

**Issue by hrqmonteiro** [ryanoasis/vim-devicons#372]
#### Required Info

- [x ] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [ x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x ] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [ x] `VimDevIcons` is the last loaded vim plugin?
- [x ] What **version** of vim are you using? NVIM 0.4.4
- [x ] What **version** of vim-devicons are you using? 0.11.0
- [X ] Are you using vim from the terminal or a GUI vim? Terminal
- [X ] Are you using Mac, Linux or Windows? Linux

#### Optional Info
![2020-12-06_16-38](https://user-images.githubusercontent.com/17055027/101290632-4d109100-37e2-11eb-8715-709d2c2aed25.png)

#### Issue

I am using the default vim statusline (i'm trying to move away from plugins like airline, lightline and stuff), and i read on the file [https://github.com/ryanoasis/vim-devicons/blob/master/doc/webdevicons.txt](https://github.com/ryanoasis/vim-devicons/blob/master/doc/webdevicons.txt) that you could set the devicons using the `set statusline=%f\ %{WebDevIconsGetFileTypeSymbol()}\ %h%w%m%r\ %=%(%l,%c%V\ %Y\ %=\ %P%)` options on the statusline config.

And i did and it worked. But it is showing using my white color (no. 7 on the colors), and i wanted to know how i can change that color

I tried setting

`hi WebDevIconsGetFileTypeSymbol ctermfg=3 cterm=NONE ctermbg=0` on my config, but no changes were applied.

I tried `echo synIDattr(synIDtrans(hlID("WebDevIconsGetFileTypeSymbol")), "fg")`on vim, and it indeed returns that the color applied is `3` but on my statusline, as you can see on the screenshot above, it is still white. 

Can someone help me how to color it?

**Comment by FarsanRashid** [comment]
@hrqmonteiro were you able to color the icon? I am using vim-airline and icon colors are not present.
