### ISSUE TITLE
Vala language has no icon?

### ISSUE THREAD

**Issue by ApolloDev0** [ryanoasis/vim-devicons#377]
Would be nice if you could add an icon for the vala language as there is none available for it.
to find out more about vala and getting its icon check below

https://wiki.gnome.org/Projects/Vala/

**Comment by kazukazuinaina** [comment]
Not currently available.
If the icon for the target language is added to the terminal font, it may become possible.

**Comment by hydrasho** [comment]
oooh ok, we have to ask the police directly
