### ISSUE TITLE
Move tab icons to the right

### ISSUE THREAD

**Issue by GentleHoneyLover** [ryanoasis/vim-devicons#380]
Hi,

Is there a possibility to move icons in tabs (I use airline) to the left? I read through the docs and didn't find an answer to that.

Currently the icons are on the right:
<img width="193" alt="Screen Shot 2021-02-15 at 10 34 46" src="https://user-images.githubusercontent.com/38346023/107930374-32456000-6f7b-11eb-85ac-06ae7ffb9e09.png">

**Comment by kazukazuinaina** [comment]
That feature is not available.
