### ISSUE TITLE
Elixir icon isn't working

### ISSUE THREAD

**Issue by luisfscoelho** [ryanoasis/vim-devicons#382]
#### Required Info

- [x ] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [ x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [ x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x ] `VimDevIcons` is the last loaded vim pl.ugin?
- [ x] What **version** of vim are you using? 8.2
- [ x] What **version** of vim-devicons are you using? 0.11.0
- [ x] Are you using vim from the terminal or a GUI vim? terminal tilix
- [ x] Are you using Mac, Linux or Windows? Fedora 33

#### Optional Info

- [x ] Provide **screenshots** where appropriate

![Screenshot-2021-02-21 16-56-16](https://user-images.githubusercontent.com/22839492/108639661-7dc4a600-7474-11eb-9dbe-22726be4a9b1.PNG)

![Screenshot-2021-02-21 18-14-35](https://user-images.githubusercontent.com/22839492/108639669-84ebb400-7474-11eb-9777-eebe8c834028.PNG)

As seen in the screenshots, the elixir icon shows an code instead of the icon, but only in .ex and .exs while other extensions are working well.

Does anyone know what's going on or what can i do?

**Comment by kazukazuinaina** [comment]
There are many different types of nerdfont. Try different fonts and see what happens.

**Comment by kazukazuinaina** [comment]
No reply?

**Comment by luisfscoelho** [comment]
I have tried different fonts but it din't work. After this I have formatted my computer and reinstalled, so now it is working as well

**Comment by kazukazuinaina** [comment]
@luisfscoelho 
I got it.
Thanks for your report.
