### ISSUE TITLE
Some icons show the sigma symbol

### ISSUE THREAD

**Issue by JeremyZabala** [ryanoasis/vim-devicons#386]
Hello friends, I have followed everything to the letter and I have not been able to get the icons to display, only Unicode or the symbol "sigma" is displayed.

I hope you can help me, I will be very grateful

#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
* What **version** of vim are you using?
`Neovim 0.4.4`
* What **version** of vim-devicons are you using?
`0.11.0`
* Are you using vim from the terminal or a GUI vim?
`Terminal`
* Are you using Mac, Linux or Windows?
`Linux`
* NerdFont
`JetBrainsMono`

![Screenshot_2021-03-23_19-23-42](https://user-images.githubusercontent.com/60724937/112244984-5563cf00-8c0d-11eb-8930-ed3edd7a1986.png)

**Comment by kazukazuinaina** [comment]
Are you using the proper terminal emulator font?
I don't think Jetbrainsmono is the right font. 
Try to use nerdfont.
