### ISSUE TITLE
Devicons not showing icons

### ISSUE THREAD

**Issue by pavanscoding** [ryanoasis/vim-devicons#387]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?
 neovim -> v0.4.3
- [x] What **version** of vim-devicons are you using?
vim-devicons -> 0.11.0
- [x] Are you using vim from the terminal or a GUI vim?
I am using NeoVim
- [x] Are you using Mac, Linux or Windows?
I am using Linux.
#### Optional Info
Instead of showing the actual icon, it just shows a little square box for everything.
- [x] Provide **screenshots** where appropriate
![nvim](https://user-images.githubusercontent.com/75864715/114093468-fe4a3500-986f-11eb-9bfc-2799c6559fb1.png)

**Comment by windvalley** [comment]
I run into the same problem.

**Comment by windvalley** [comment]
> #### Required Info
> * [x]  I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
> * [x]  I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
> * [x]  I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
> * [x]  `VimDevIcons` is the last loaded vim plugin?
> * [x]  What **version** of vim are you using?
>   neovim -> v0.4.3
> * [x]  What **version** of vim-devicons are you using?
>   vim-devicons -> 0.11.0
> * [x]  Are you using vim from the terminal or a GUI vim?
>   I am using NeoVim
> * [x]  Are you using Mac, Linux or Windows?
>   I am using Linux.
> 
> #### Optional Info
> Instead of showing the actual icon, it just shows a little square box for everything.
> 
> * [x]  Provide **screenshots** where appropriate
>   ![nvim](https://user-images.githubusercontent.com/75864715/114093468-fe4a3500-986f-11eb-9bfc-2799c6559fb1.png)

I have solved this problem. 
You need to install [nerd-fonts](https://github.com/ryanoasis/nerd-fonts#font-installation
) in advance, and set the font of iterm2 (or other types of terminals) to `Hack Nerd Font` or `Hack Nerd Font Mono`.

e.g. Install on macOS:
```bash
brew tap homebrew/cask-fonts && brew install font-hack-nerd-font
```

**Comment by windvalley** [comment]
@pavanscoding I have sovled this problem. I just forgot to install [nerd-fonts](https://github.com/ryanoasis/nerd-fonts#font-installation), and set font of item2 to `Hack Nerd Font` or `Hack Nerd Font Mono`, then it works.

**Comment by pavanscoding** [comment]
@windvalley, I am confused. What is item 2? How do I set it up?

**Comment by windvalley** [comment]
@pavanscoding `iterm2` is a terminal on macOS, just like your screenshots that you used on Linux.  Have you read this https://github.com/ryanoasis/vim-devicons/wiki/Installation ?

**Comment by pavanscoding** [comment]
@windvalley I have read that, but the installation isn't working.

**Comment by call-me-anything-you-want** [comment]
I ran into the same problem. I'm using windows10 and gVim 8.2
the font I'm using is BitstreamVeraSansMono NF (a font downloaded from nerd-fonts)
when I open vim from the cmd, everything is just fine.
However, when I'm using gVim, all the icons can't be displayed properly and they are all shown in little squares just like you.

**Comment by call-me-anything-you-want** [comment]
like this
<img width="190" alt="gvim_fkzoorh0L3" src="https://user-images.githubusercontent.com/70688565/115729745-42811d80-a3b8-11eb-9dd6-335249f2fab0.png">

**Comment by windvalley** [comment]
@call-me-anything-you-want Try add `set guifont=BitstreamVeraSansMono_NF:h13` in your .vimrc

**Comment by call-me-anything-you-want** [comment]
@windvalley I did that but it didn't work.
I even tried to set guifont to another nerd font I downloaded. But the problem still exists

**Comment by call-me-anything-you-want** [comment]
problem solved
although my guifont was a nerd font, my guifontwide wasn't.
So I deleted ` set gfw=... ` in my _vimrc
and everything is ok now.

**Comment by kazukazuinaina** [comment]
If you are using a terminal emulator, guifont has nothing to do with it.
Try changing the font of the terminal emulator itself.

**Comment by kazukazuinaina** [comment]
No reply?

**Comment by ryanoasis** [comment]
@pavanscoding I'm considering this solved. Please reopen if you still have the issue

**Comment by clint911** [comment]
Same issue mac os

**Comment by Aryan3212** [comment]
If you have `Use a different for non-ASCII text` checked on MacOS, Iterm2 -> Preferences/Settings -> Profiles -> Text UNCHECK IT.

**Comment by Rememberonly** [comment]
> 如果您已`Use a different for non-ASCII text`在 MacOS 上选中，则 Iterm2 -> 首选项/设置 -> 配置文件 -> 文本取消选中它。
I also encountered this kind of problem, but I changed the font to Hack Nerd Font Mono in the settings of iterm2, and the nvim code icon is still not displayed

**Comment by Aryan3212** [comment]
@Rememberonly Did you uncheck the setting [Iterm2 -> Preferences/Settings -> Profiles -> Text -> `Use a different for non-ASCII text`]? It needs to be turned off.

**Comment by ivandj0h** [comment]
> @Rememberonly Did you uncheck the setting [Iterm2 -> Preferences/Settings -> Profiles -> Text]? It needs to be turned off.

i got the same issues, but it's already fixed by :
installing [Nerd Font!](https://github.com/ryanoasis/nerd-fonts#font-installation) and 

i did this one :
**[Iterm2 -> Preferences/Settings -> Profiles -> Text]**

[Aryan3212](https://github.com/Aryan3212)
