### ISSUE TITLE
Wrong icon if `filetype` changes

### ISSUE THREAD

**Issue by WhyNotHugo** [ryanoasis/vim-devicons#393]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?
```
nvim --version
NVIM v0.5.0-dev+1359-g43956dea5
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2,-D_GLIBCXX_ASSERTIONS     -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/hugo/.cache/paru/clone/neovim-git/src/build/config -I/home/hugo/.cache/paru/clone/neovim-git/src/neovim-git/src -I/usr/include -I/home/hugo/.cache/paru/clone/neovim-git/src/build/src/nvim/auto -I/home/hugo/.cache/paru/clone/neovim-git/src/build/include
Compiled by hugo@victory

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- [x] What **version** of vim-devicons are you using?
`0.11.0`
- [x] Are you using vim from the terminal or a GUI vim?
terminal
- [x] Are you using Mac, Linux or Windows?
Linux

#### Steps to reproduce

For reference:

1. `nvim test.sh`
2. `:echo WebDevIconsGetFileTypeSymbol()` ->  

Actual issue:

1. `nvim test`
2. `:echo WebDevIconsGetFileTypeSymbol()` -> 
3. `:set ft=sh`
4. `:echo WebDevIconsGetFileTypeSymbol()` -> 

The last call should return the same icon as above: .

It seems that `WebDevIconsGetFileTypeSymbol()` returns the icon based on the initial value of `filetype`, and not the current one.

**Comment by kazukazuinaina** [comment]
@WhyNotHugo 

thanks for your bug report.
How about this patch?

```diff
diff --git a/plugin/webdevicons.vim b/plugin/webdevicons.vim
index 7087561..a75d83a 100644
--- a/plugin/webdevicons.vim
+++ b/plugin/webdevicons.vim
@@ -490,9 +490,9 @@ endfunction

 " a:1 (bufferName), a:2 (isDirectory)
 " scope: public
-function! WebDevIconsGetFileTypeSymbol(...)
+function! WebDevIconsGetFileTypeSymbol(...) abort
   if a:0 == 0
-    let fileNodeExtension = expand('%:e')
+    let fileNodeExtension = &filetype
     let fileNode = expand('%:t')
     let isDirectory = 0
```

Please try this patch!

**Comment by kazukazuinaina** [comment]
@WhyNotHugo 
Please also see #397 pull request
