### ISSUE TITLE
Colors don't work without "set termguicolors"

### ISSUE THREAD

**Issue by C-Rmoser** [ryanoasis/vim-devicons#394]
The icon colors don't work unless add "set termguicolors" in my init.vim.
However doing that messes with my colorschemes. Any idea how I can get the colors working with cterm colors enabled?

I am running the latest version of neovim (nightly) on Windows 10 Powershell 7.

**Comment by Foxtrod89** [comment]
same here, I didn't set _termguicolors_ intentionally due to lack of true colors support of native macOS terminal
