### ISSUE TITLE
Add solidity language (.sol file extension) icon instead of showing generic icon

### ISSUE THREAD

**Issue by Adoliin** [ryanoasis/vim-devicons#395]
#### Required Info

- [X] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [X] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [X] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [X] `VimDevIcons` is the last loaded vim plugin?
- [X] What **version** of vim are you using?
  - 8.2
- [X] What **version** of vim-devicons are you using?
  - 0.11.0
- [X] Are you using vim from the terminal or a GUI vim?
  - Terminal
- [X] Are you using Mac, Linux or Windows?
  - Linux

Missing language:
Add solidity (Ethereum based smart contract language) icon to the icons.
Maybe use the ethereum logo or something else

**Comment by kazukazuinaina** [comment]
@Adoliin 
Thanks.
Could you also add test?
