### ISSUE TITLE
The folder icon is surrounded by square brackets

### ISSUE THREAD

**Issue by pCandKa** [ryanoasis/vim-devicons#398]
- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [ ] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?
  - hint: `NVIM v0.6.0-dev`
- [x] What **version** of vim-devicons are you using?
  - hint: `0.11.0`
- [x] Are you using vim from the terminal or a GUI vim?
  - hint: `terminal`
- [x] Are you using Mac, Linux or Windows?
  - hint: `windows`

The folder is surrounded by square brackets.I need another plugin to run properly so I can't set Conceallevel =3, is there any other solution?

Another plug-in in the https://github.com/Yggdroot/indentLine

**Comment by liushuiyuan001** [comment]
I met a same problem.It not ok by setting
```
let g:webdevicons_conceal_nerdtree_brackets=1
```

**Comment by jiajun-c** [comment]
I just fixed this bug, you should set the font in your terminal as he said in the instruction.

**Comment by liushuiyuan001** [comment]
https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting#square-brackets-around-icons
I met this beacase I had 8.0v's vim.
I just update vim's version 
https://apple.stackexchange.com/questions/252433/how-to-upgrade-system-default-vim
I had met a problem In my Mac os.  ``` Error: Could not symlink share/man/de/man1/ex.1 ```
https://stackoverflow.com/questions/61901147/i-have-problems-linking-brews-vim-version

@13396433778

**Comment by 13396433778** [comment]
> 我刚刚修复了这个错误，您应该按照说明中的说明在终端中设置字体。

But my folders are still surrounded by [  ]

Sorry, English is not my first pronunciation, I am not good at using it

**Comment by 13396433778** [comment]
> 我刚刚修复了这个错误，您应该按照说明中的说明在终端中设置字体。

But my folder icon  are still surrounded by [     ]

Sorry, English is not my first language, I am not good at using it

**Comment by 13396433778** [comment]
> I just fixed this bug, you should set the font in your terminal as he said in the instruction.

But my folder icon is still surrounded by [   ]

English is not my first language, I am not good at using it

**Comment by 13396433778** [comment]
I try to
set conceallevel = 3
let g:webdevicons_conceal_nerdtree_brackets = 1
I'm sure I set it right
But the folder icon is still wrapped by [   ]

**Comment by 13396433778** [comment]
Because I'm using nvim,
So I followed the instructions and followed the steps below
nvim --version | grep conceal
But what is he not exporting

**Comment by liushuiyuan001** [comment]
> Because I'm using nvim,
> So I followed the instructions and followed the steps below
> nvim --version | grep conceal
> But what is he not exporting
Just update new version nvim @13396433778

**Comment by 13396433778** [comment]
> > 因为我使用的是 nvim，
> > 所以我按照说明进行操作，并按照以下步骤
> > nvim --version | grep 
> > hidden
> > 但他不导出什么只需更新新版本 nvim @13396433778



> > 因为我用的是nvim，
> > 所以我按照说明进行操作，并按照以下步骤
> > nvim --version | grep 
> > hidden
> > 但他不知道什么最新更新版本 nvim @13396433778

我试过了不行

**Comment by 13396433778** [comment]
> > Because I'm using nvim,
> > So I followed the instructions and followed the steps below
> > nvim --version | grep conceal
> > But what is he not exporting
> > Just update new version nvim @13396433778

I tried. No

**Comment by pCandKa** [comment]
I figured out why
luochen1990/rainbow
This plugin is causing problems
