### ISSUE TITLE
Compatibility issues with luochen1990/rainbow and Nerd Tree

### ISSUE THREAD

**Issue by pCandKa** [ryanoasis/vim-devicons#401]
When I started luochen1990/rainbow
Folder ICONS are surrounded by [ ]

**Comment by leo94666** [comment]
how to solve it?

**Comment by ajiepangestu** [comment]
to solve it, disable rainbow in nerdtree
```
let g:rainbow_conf = {
	\	'separately': {
	\		'nerdtree': 0,
	\	}
	\}
```

**Comment by Manuel-Camacho-Padilla** [comment]
> to solve it, disable rainbow in nerdtree
> 
> ```
> let g:rainbow_conf = {
> 	\	'separately': {
> 	\		'nerdtree': 0,
> 	\	}
> 	\}
> ```

Thanks, this also solves my problem

**Comment by get-me-power** [comment]
Thanks for Information @ajiepangestu @manu-camacho

**Comment by CodeConnoisseur74** [comment]
This also worked for me. Thank-you @ajiepangestu !
