### ISSUE TITLE
some icons not displaying with vim-airline

### ISSUE THREAD

**Issue by g-e-o-m-e-t-r-i-c** [ryanoasis/vim-devicons#402]
**P. S.**: this also applies for other icons, such as javascript.

#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
        - **Proof** (using `VimPlug`): 
![image](https://user-images.githubusercontent.com/79387351/128793319-29071560-0161-4086-b824-a4fe8be32459.png)

- [x] What **version** of vim are you using?
  - **Vim 8.1**
- [x] What **version** of vim-devicons are you using?
  - **0.11.0**
- [x] Are you using vim from the terminal or a GUI vim?
    - Vim via **Windows Terminal**
- [x] Are you using Mac, Linux or Windows?
    - Ubuntu 20.04 Linux WSL 
#### Optional Info

- [x] Provide **screenshots** where appropriate
Icons for other filetypes work fine on `vim-airline`, apart from Python.

#### For Comparison:
**Vim**
![image](https://user-images.githubusercontent.com/79387351/128793543-059418cf-613d-4dc5-b062-eeb83b9d566f.png)

**Markdown**
![image](https://user-images.githubusercontent.com/79387351/128793563-200767b9-a94c-4378-8e9c-84591c2da450.png)

***Python*** (the faulty one in question, falls back to default icon)
![image](https://user-images.githubusercontent.com/79387351/128793649-d842c7d1-7901-475b-99d6-e91f69bacb12.png)

**JavaScript** (also faulty)
![image](https://user-images.githubusercontent.com/79387351/128803673-04e84436-9bb7-42b9-a40e-e420f4a1f143.png)

**Comment by kazukazuinaina** [comment]
Thanks for your report.
It's bug.
I will fix this bug soon.

**Comment by kazukazuinaina** [comment]
@g-e-o-m-e-t-r-i-c 

How about this patch?

```diff
diff --git a/plugin/webdevicons.vim b/plugin/webdevicons.vim
index c718f65..deb4f51 100644
--- a/plugin/webdevicons.vim
+++ b/plugin/webdevicons.vim
@@ -493,7 +493,7 @@ endfunction
 " scope: public
 function! WebDevIconsGetFileTypeSymbol(...) abort
   if a:0 == 0
-    let fileNodeExtension = &filetype
+    let fileNodeExtension = !empty(expand('%:e')) ? expand('%:e') : &filetype
     let fileNode = expand('%:t')
     let isDirectory = 0
   else
```
