### ISSUE TITLE
Add support for Prolog with `.pro` file extension

### ISSUE THREAD

**Issue by sicr0** [ryanoasis/vim-devicons#418]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using? 8.2
- [x] What **version** of vim-devicons are you using? 0.11.0
- [x] Are you using vim from the terminal or a GUI vim? Terminal
- [x] Are you using Mac, Linux or Windows? Linux

#### Optional Info

- [x] Provide **screenshots** where appropriate
![Screenshot_20211105_212008](https://user-images.githubusercontent.com/49662650/140591314-63e65708-c164-4c6c-8049-110083c1236f.png)

The `.pl` file extension is used by both Perl and Prolog, but since Perl is more widespread I wouldn't mind if it were one of a camel (it actually looks like an onion for some reason). But Prolog also has `.pro` file extension, and Nerd Fonts has the `nf-dev-prolog` icon ().

Thanks for your time.

**Comment by sicr0** [comment]
I just found out that a symbol for Perl is the onion, I tought it was a camel. Nonetheless `.pro` files could be shown as Prolog since I don't think there's another interpretation

**Comment by sicr0** [comment]
Sorry, I just realized I put this issue here instead of NERDTree. I'm closing and reopening there.

**Comment by ryanoasis** [comment]
Sorry. I'm confused this _is_ the right place unless nerdtree now has glyphs for files out-of-the-box?

**Comment by sicr0** [comment]
NerdTree and Vim-DevIcons both have Prolog support, it was Vim that detected `.pro` files wrong. I fixed it with a line on my `.vimrc`

**Comment by ryanoasis** [comment]
You are talking about the glyph/icon right? I thought you were saying you wanted to have a file icon specific for `.pro` but sounds like you added it in your config?
