### ISSUE TITLE
Link of Powerline setup in wiki is broken

### ISSUE THREAD

**Issue by timsu92** [ryanoasis/vim-devicons#431]
#### Requirements

*Firstly, this is an issue about the Wiki, not the program.*

In 'Usage' section of the Wiki, there's [Powerline Setup](https://github.com/ryanoasis/vim-devicons/wiki/usage#powerline-setup).
The last sentence of this part is the link to the [sample file](https://github.com/ryanoasis/vim-devicons/wiki/samples/v0.10.x/powerline/themes/vim/default.json). However, I can't open it. HTTP Error 406 occured.

#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?
  - 8.1
- [x] What **font** are you using?
  - JetBrainsMono NF
- [x] Are you using vim from the terminal or a GUI vim?
  - Terminal (bash)
- [x] Are you using Mac, Linux or Windows?
  - WSL2 (Ubuntu 20.04.4 LTS)

**Comment by get-me-power** [comment]
@timsu92 

Thanks for your report.
I fixed link. Please check.
