### ISSUE TITLE
Colored Icons

### ISSUE THREAD

**Issue by cosigns** [ryanoasis/vim-devicons#444]
Amateur here, hello all!

I am new to neovim, and fonts. I am using neovim in WSL 2, and I've installed Jet Brains Mono font, but the icons are black & white? can I change it to colored ones?

**Comment by get-me-power** [comment]
vim-devicons does not provide coloring functionality.
Please refer to other plugins.

see also:
- https://github.com/lambdalisue/glyph-palette.vim

**Comment by cosigns** [comment]
Do I need to add `yaml:Plug lambdalisue/glyph-palette.vim` in my init.vimrc? to get the plugin work?
