### ISSUE TITLE
support unite.vim?

### ISSUE THREAD

**Issue by premjg** [ryanoasis/vim-devicons#54]
https://github.com/Shougo/unite.vim

Unite is gaining popularity and looks like the API is pretty streamlined.
It'd would great to have vim-devicons working with Unite.

**Comment by ryanoasis** [comment]
That's a good idea. No current plans but maybe if there is enough request for this.

I had briefly looked into adding something for `ctrlp.vim` because that is what I use but I know a lot of people also use 'unite.vim` so it could be worth it.

**Comment by ryanoasis** [comment]
Was curious about setting up a poll, I didn't realize this one adds a new issue :stuck_out_tongue_closed_eyes: 

http://poll.gitrun.com/ryanoasis/vim-webdevicons/issues/55

**Comment by DemonCloud** [comment]
Support it you would also support the Vimfiler.vim

**Comment by ryanoasis** [comment]
Going to try this when I get time: https://github.com/Shougo/unite.vim/issues/412

**Comment by ryanoasis** [comment]
Unite luckily seems pretty easy to implement :disappointed_relieved: 

![selection_19_06_15_15 39 26_964x264_001](https://cloud.githubusercontent.com/assets/8083459/8261574/9785b190-1699-11e5-8865-0d44b0c8533c.png)


But I might to ask for help on Vimfiler from

**Comment by ryanoasis** [comment]
With some direction from @Shougo I have a custom column type working for **vimfiler** :smiley: 

Work in progress:
![selection_20_06_15_12 23 51_727x531_001](https://cloud.githubusercontent.com/assets/8083459/8268136/cf787cdc-1747-11e5-9e90-0769521d9e24.png)

**Comment by Shougo** [comment]
:-)

**Comment by osleg** [comment]
:+1:

**Comment by delphinus35** [comment]
+1

**Comment by ryanoasis** [comment]
For anyone feeling brave you can give [0.5.0](https://github.com/ryanoasis/vim-webdevicons/tree/0.5.0) a try :smirk: :
* support for flagship
* support for perl
* added support for more languages
* support for unite and vimfiler
* API fix
* misc code formatting fixes
* misc readme and doc updates

(I still need to do more testing before a release **AND** _maybe_ try to get **ctrlp** support and **nerdtree added files no icon** but those might be pushed off to say 0.6.0 or something)
