### ISSUE TITLE
support ctrlp.vim?

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/vim-devicons#56]
support ctrlp.vim - add icons to mru and various lists ?

**Comment by ryanoasis** [comment]
http://poll.gitrun.com/ryanoasis/vim-webdevicons/issues/56

**Comment by adambiggs** [comment]
+1

**Comment by cnicolov** [comment]
+1

**Comment by SageEx** [comment]
+1

**Comment by ryanoasis** [comment]
This is gonna take some work to do properly and I hope it isn't too bad. So far all I have been able to do is modify ctrlp code directly:

![selection_18_06_15_19 42 18_819x143_001](https://cloud.githubusercontent.com/assets/8083459/8244729/6fb99520-15f2-11e5-815f-b8fb5a5b880b.png)


I want to eventually be able to obviously do it a proper way and also to avoid a PR

**Comment by muellan** [comment]
+1

**Comment by nicholasc** [comment]
+1

**Comment by vitaminless** [comment]
+1

**Comment by ryanoasis** [comment]
I have this working with a _somewhat_ ugly/hacky overwrite for the official/original [kien/ctrlp.vim](https://github.com/kien/ctrlp.vim) and I am going to submit a PR for a simpler implementation for the active fork [ctrlpvim](https://github.com/ctrlpvim/ctrlp.vim)
