### ISSUE TITLE
support vim-flagship (because it is easy)

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/vim-devicons#70]
support https://github.com/tpope/vim-flagship

![Image of testing support for vim-flagship](https://lh3.googleusercontent.com/bnEH2m0KGQhjm-x1ex2TLumKWqNzMJJXvNJYcRrRknQ=w764-h193-no)

**Comment by DemonCloud** [comment]
You working so hard... now in china at 2AM.... not sleep

**Comment by ryanoasis** [comment]
@DemonCloud Haha nah not too hard I think. I work on this when I have energy for the most part and it is important to have a good life balance thanks. Enjoy! :tada:

**Comment by ryanoasis** [comment]
For anyone feeling brave you can give [0.5.0](https://github.com/ryanoasis/vim-webdevicons/tree/0.5.0) a try :smirk: :
* support for flagship
* support for perl
* added support for more languages
* support for unite and vimfiler
* API fix
* misc code formatting fixes
* misc readme and doc updates

(I still need to do more testing before a release **AND** _maybe_ try to get **ctrlp** support and **nerdtree added files no icon** but those might be pushed off to say 0.6.0 or something)
