### ISSUE TITLE
Unable to set font to be used in terminal

### ISSUE THREAD

**Issue by osleg** [ryanoasis/vim-devicons#75]
Using rxvt-unicode I edited my .Xresources file with 
```
URxvt.font : xft:Terminess  Powerline:pixelsize=14
URxvt.boldFont : xft:Terminess Powerline:pixelsize=14:style=Bold
URxvt.italicFont : xft:Terminess Powerline:pixelsize=14
URxvt.boldItalicFont : xft:Terminess Powerline:pixelsize=14
```

The font looks broken, it doesn't honor the size, neither I can see glyphs/arrows in vim
I tried with couple of differents fonts from nerd-fonts repo but the result is always the same.
This is with `ProggyCleanTT`:

![201507081424](https://cloud.githubusercontent.com/assets/207721/8564316/333d4156-257d-11e5-8230-ef1f665fe797.png)

Though it doesn't really matter which font I'm using, always looks like this.

**Comment by ryanoasis** [comment]
@osleg that *might/hopefully* be the font name you have given. I tried testing it right now but I am having some issues with my rxvt terminal updating my settings :blush: 

I'll get back to you though. Thanks!

**Comment by osleg** [comment]
I tried with bizillion different names... though I actually took the name from `fc-list` command so should be correect one.
I also tried to the the very same way as described in your readme with Droid fonts, nothing helps :)

**Comment by ryanoasis** [comment]
Oh wow okay then sounds like a problem with the actual Mono fonts :worried: 

Sorry that it is not working, I'll have to see what's going on

**Comment by osleg** [comment]
If you need that i'll test something - let me know

**Comment by ryanoasis** [comment]
@osleg Sorry it looks like the bitmap fonts (bdf) are *NOT* being patched correctly.

Can you try the Droid Sans Mono or check your configuration lines?

## Droid Sans

`URxvt.font: xft:Droid Sans Mono for Powerline Plus Nerd File Types Mono:pixelsize=16:antialias=true:hinting=true`

![selection_12_07_15_14 52 41_657x802_001](https://cloud.githubusercontent.com/assets/8083459/8639363/af5c422a-28a5-11e5-9f28-19122fc90054.png)

## ProggyCleanTT:

`URxvt.font: xft:ProggyCleanTT Plus Nerd File Types Mono:pixelsize=16:antialias=true:hinting=true`

![selection_12_07_15_14 56 18_671x700_001](https://cloud.githubusercontent.com/assets/8083459/8639379/3af6155e-28a6-11e5-9af6-a8b5f2f0f7ca.png)

Some of the un-patched fonts do not have the powerline symbols by default so I *do* need to make sure all the patched version have them.. so some fonts right now you will not get the powerline symbols. I will post here when that is fixed :smile: 

P.S. Sorry about the color :laughing:

**Comment by osleg** [comment]
Here is the result, it looks the same with both Droid and Proggy 
![20150713032220](https://cloud.githubusercontent.com/assets/207721/8639492/6ed8a6bc-290e-11e5-9a2c-842d7f6d5897.png)

**Comment by osleg** [comment]
My bad, with droid it looks ok, though proggy is just as shown above.
How could I patch Terminus with the powerline arrows and your icons? Too used to terminus already :)

**Comment by ryanoasis** [comment]
@osleg To me it looks like it is not finding the font. The font in the screenshot looks different than Droid Sans.

Here is what I get running `fc-list`:
```
fc-list | grep "Droid Sans Mono for Powerline"
/home/ryan/.fonts/Droid Sans Mono for Powerline Plus Nerd File Types Mono.otf: Droid Sans Mono for Powerline Plus Nerd File Types Mono:style=Regular
/home/ryan/.fonts/Droid Sans Mono for Powerline Plus Nerd File Types.otf: Droid Sans Mono for Powerline Plus Nerd File Types:style=Regular
```

**Comment by ryanoasis** [comment]
@osleg Yeah sounds like a few fonts need fixing.

As for Terminus you can try the [font patcher](https://github.com/ryanoasis/nerd-fonts) but it doesn't  seem to be patching the bitmap fonts correctly at the moment.

**Comment by ryanoasis** [comment]
@osleg I think I want to close this issue and instead use this one: ryanoasis/nerd-fonts/issues/16

**Comment by ryanoasis** [comment]
Just confirming that I am leaving this ticket open so that I followup. Will remain open until https://github.com/ryanoasis/nerd-fonts/issues/16 is resolved

**Comment by ryanoasis** [comment]
I believe the latest ProggyClean I uploaded should now be fixed. Now just need to fix Terminus

**Comment by ryanoasis** [comment]
Closing for now. Terminus font patching issues probably still remain though.
