### ISSUE TITLE
Request: Typescript Icon

### ISSUE THREAD

**Issue by mhartington** [ryanoasis/vim-devicons#79]
A typescript icon would be great! Seti-ui for atom already has one in their fonts.

<img width="195" alt="screen shot 2015-07-13 at 9 55 39 pm" src="https://cloud.githubusercontent.com/assets/2835826/8664818/529313d8-29aa-11e5-9c98-0f1dd35447b6.png">

Nice and simple too.

**Comment by ryanoasis** [comment]
Yep! Actually I noticed there were new ones in seti-ui that I did not have and also some other ideas I have been playing with (more and custom folders)

These are the additions (highlighted in blue) I would like to make (including typescript) :smirk: 

![selection_13_07_15_22 41 59_878x461_001](https://cloud.githubusercontent.com/assets/8083459/8665304/7bf219e4-29b0-11e5-8d35-286022ccdf71.png)

**Comment by mhartington** [comment]
:+1:

**Comment by lerrua** [comment]
@ryanoasis nice that `e52a` Vi icon :+1:

**Comment by ryanoasis** [comment]
Done
