### ISSUE TITLE
Plugin seems to truncate 6 characters when opening with CtrlP

### ISSUE THREAD

**Issue by nicholasc** [ryanoasis/vim-devicons#80]
The plugin seems to affect CtrlP's behaviour since it supports it. When opening a file in a new tabs it seems to truncate the first six characters of the filename therefore opening a new buffer.

![screen shot 2015-07-14 at 10 24 24 am](https://cloud.githubusercontent.com/assets/2378304/8675830/fbfda168-2a13-11e5-9e0e-1e57511f8769.png)
![screen shot 2015-07-14 at 10 24 39 am](https://cloud.githubusercontent.com/assets/2378304/8675831/fbfe6b70-2a13-11e5-972b-e2d19bd7d2f1.png)

Am I missing a configuration? Or should I wait for the [pull request](https://github.com/ctrlpvim/ctrlp.vim/pull/104) you sent to CtrlP?

**Comment by ryanoasis** [comment]
It _should_ be working without the PR [with the hack](https://github.com/ryanoasis/vim-devicons/blob/master/plugin/webdevicons.vim#L371-L450). It looks like the `ctrlp_open_func` is working correctly but the customized `reformat` tweak is not executing (thus there are no glyph prefixes to remove).

My initial thought is maybe your ctrlp Plugin line is coming after devicons?

To temporarily get your ctrlp working you can disable vim-devicons interfering with it:
`let g:webdevicons_enable_ctrlp = 0`
^ looks like I am missing this from the readme and doc :disappointed: 

Whatever the case I think I need to adjust [webdevicons#ctrlPOpenFunc](https://github.com/ryanoasis/vim-devicons/blob/master/plugin/webdevicons.vim#L484) logic to *not* rely on truncated a fixed number but to only remove specific unicode pattern (would be safer going forward).

**Comment by nicholasc** [comment]
Ah perfect. I can temporarily disable the CtrlP option for now. I figured it was trying to remove the glyph from the filename so it could get the file path correctly. Doing so using unicode patterns would definitely be more reliable than with a fixed offset. How would I get the reformat tweak to execute correctly?

P.S: My devicons line is after CtrlP in my config.

**Comment by ryanoasis** [comment]
> How would I get the reformat tweak to execute correctly?

I am not sure at the moment. I tested as many scenarios as I could on my local including both [kien/ctrlp](https://github.com/kien/ctrlp.vim) and [ctrlpvim/ctrlp](https://github.com/ctrlpvim/ctrlp.vim) . I am guessing you use kien/ctrlp ?

You could try adding some `echom`s inside the `s:initializeCtrlPOverwrite()` function to see if it is even being called and/or get a better sense of what logic path is being taken

**Comment by nirum** [comment]
Hey! I ran into this same problem (see the issue above)

**Comment by nirum** [comment]
also: I'm using the active fork, ctrlpvim/ctrlp
