### ISSUE TITLE
Font Installation curl link is wrong

### ISSUE THREAD

**Issue by theRemix** [ryanoasis/vim-devicons#81]
Update the Font Installation curl url to https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/patched-fonts/DroidSansMono/Droid%20Sans%20Mono%20for%20Powerline%20Plus%20Nerd%20File%20Types.otf

**Comment by ryanoasis** [comment]
@theRemix Nice catch! Can you submit a PR so you can get the proper contribution?

**Comment by theRemix** [comment]
woops forgot to create a PR, https://github.com/ryanoasis/vim-devicons/pull/83
