### ISSUE TITLE
Dots appearing to the right of icons in NerdTree

### ISSUE THREAD

**Issue by rdlugosz** [ryanoasis/vim-devicons#84]
I'm seeing "dots" immediately to the right of the icons in NERDTree and it looks as if the dots partially cut off the right edge of the image. Any idea what's going on here? I do not see the dots when I don't have the devicons plugin loaded. Font in use here is patched "Sauce Code Pro", but I see the same results with any font (including unpatched fonts).

![screen shot 2015-07-23 at 4 37 23 pm](https://cloud.githubusercontent.com/assets/402328/8861791/572179be-315a-11e5-9997-ad495e5962ee.png)

My [vimrc is here](https://github.com/rdlugosz/dotfiles/blob/master/vimrc). I see this in both MacVim and Neovim (terminal). Running the latest/very recent of everything: `NVIM 0.0.0-alpha+201507221531 (compiled Jul 22 2015 21:29:54)`, `VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 15 2015 08:44:52)
MacOS X (unix) version
Included patches: 1-712`; All plugins current as of today.

**Comment by ryanoasis** [comment]
Hmm that is odd. Can you see what char code it gives when you highlight with cursor and enter `ga` ? 

You should see the hex and octal value.

I did add a display hack fix that adds a supposedly empty character that helps with glyphs being cut off but possibly on your system that char is not blank: https://github.com/ryanoasis/vim-devicons/blob/master/plugin/webdevicons.vim#L533-L537

**Comment by rdlugosz** [comment]
Ah! Doing a `ga` made the problem obvious: `< > 160, \240, U+00A0 NO-BREAK SPACE, ^KNS, &nbsp; ` …and in my vimrc: `let &listchars = "tab:>-,trail:\u2591,extends:>,precedes:<,nbsp:\u00b7"`

Disabling the special character for `nbsp` resolved the issue. Thx for pointing me in the right direction.

**Comment by ryanoasis** [comment]
@rdlugosz Awesome! :tada: Glad you were able to find the reason and resolve.

Do you think using `NO-BREAK SPACE` as a hack fix character is a bad idea? Should we use something else?

**Comment by rdlugosz** [comment]
If there's a better choice than NBSP I'm not aware of one. I think your usage is fine (and probably 99% of users aren't setting a listchar for nbsp like I was—and I wasn't really in need of that listchar anyway, so I'm not bothered by unsetting it.
