### ISSUE TITLE
Fonts (icons) not showing

### ISSUE THREAD

**Issue by radaniba** [ryanoasis/vim-devicons#85]
Hello 

I am using vim 7.4 (no macvim/gvim) and I am having troubles configuring this plugin
Icons are not showing up and all documentation is about ~/.gvimrc for the `guifont` part

Any idea on how to get fixed ?

(am using MacOs Yosemite)

![screen shot 2015-07-23 at 3 49 34 pm](https://cloud.githubusercontent.com/assets/1666443/8864069/c33a2fc2-3152-11e5-9664-2d01c2c08aeb.png)

**Comment by radaniba** [comment]
[This](https://github.com/ryanoasis/nerd-fonts/issues/13) fixed my problem

**Comment by ryanoasis** [comment]
@radaniba great! I was actually going to post a link to that ticket. Do you think if info on iterm settings in the readme would help?

**Comment by radaniba** [comment]
@ryanoasis absolutely ! Please do ! Also MacOs doesnt really overwrite fonts when you install them again, make sure to recommend remove a particular font and install the patched one instead

**Comment by sureshsaragadam** [comment]
mkdir -p ~/.local/share/fonts

cd ~/.local/share/fonts && curl -fLo "Droid Sans Mono for Powerline Nerd Font Complete.otf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf

**Comment by sureshsaragadam** [comment]
https://github.com/ryanoasis/nerd-fonts#option-1-download-and-install-manually
