### ISSUE TITLE
filenames of buffers get lost in unite filter

### ISSUE THREAD

**Issue by ahrse** [ryanoasis/vim-devicons#86]
I'd like to suggest the following patch:
`diff --git a/plugin/webdevicons.vim b/plugin/webdevicons.vim`
`index f7e1eb5..dcde594 100644`
`--- a/plugin/webdevicons.vim`
`+++ b/plugin/webdevicons.vim`
`@@ -319,6 +319,10 @@ function! s:initializeUnite()`
 ``
`         let icon = WebDevIconsGetFileTypeSymbol(filename, isdirectory(filename))`
`` 
`+        if filename != path`
`+          let path = printf("%s %s", filename, path)`
`+        endif`
`+`
`         " Customize output format.`
`         let candidate.abbr = printf("%s %s", icon, path)`
`       endfor`

**Comment by ryanoasis** [comment]
@ahrse nice fix thanks! 

Do you want to submit a Pull Request so you get credit for the code contribution? If not I will get this in soon :+1:

**Comment by ahrse** [comment]
eh' get it  in there I'd go to charge for real work :-)

kind regards


Zitat von Ryan L McIntyre <notifications@github.com>:

**Comment by ryanoasis** [comment]
@ahrse well thanks. Yep I understand. Just thought I'd make sure :smile:
