### ISSUE TITLE
Request: Alternative Ruby and Vim icons

### ISSUE THREAD

**Issue by lerrua** [ryanoasis/vim-devicons#89]
Hi @ryanoasis

I've saw the set 2 with others icons like ruby and vim:
https://github.com/ryanoasis/nerd-fonts#set-2-devicons

How to use it? It will be great if i can replace my ruby icon.

**Comment by ryanoasis** [comment]
Sure! I know the default ruby one I chose might be a bit ugly :laughing: 

Yeah so.. you should be able to change any match you want, try for example in your `vimrc`:

```vim
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {} " needed
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['rb'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['vim'] = ''
```

I have (what I think) is a better default vim icon coming in the next additions:
![upcoming icon additions](https://cloud.githubusercontent.com/assets/8083459/8665304/7bf219e4-29b0-11e5-8d35-286022ccdf71.png)

**Comment by lerrua** [comment]
@ryanoasis this new ruby icon is much better than other =p
But wtf, how i can see thats unicode in image? haha

**Comment by ryanoasis** [comment]
@lerrua you can grab most of the glyphs from here if you want: https://raw.githubusercontent.com/wiki/ryanoasis/vim-webdevicons/tests/utf8-markus-kuhn-plus-webdevicon-glyphs.txt

**Comment by lerrua** [comment]
@ryanoasis Nice! Thank man. :heart:
