### ISSUE TITLE
Problem in vim terminal - mac osx

### ISSUE THREAD

**Issue by marioidival** [ryanoasis/vim-devicons#90]

**Comment by marioidival** [comment]
![captura de tela 2015-08-03 as 22 38 51](https://cloud.githubusercontent.com/assets/1129263/9051387/83ff301e-3a30-11e5-85b3-f8e869e24f8f.png)

**Comment by ryanoasis** [comment]
can you tell me what font is set in the terminal?

are you using iterm?

See if this helps you: [#13](https://github.com/ryanoasis/nerd-fonts/issues/13)

**Comment by lerrua** [comment]
@marioidival maybe u must install with double click in ~/.fonts/file and set Droid font inside iterm

**Comment by marioidival** [comment]
Wow, Thank you @ryanoasis @lerrua . I use `Terminal` terminal app from osx. I just change the font directly in `Preferences`. 

Thank you again for fast support.

**Comment by ryanoasis** [comment]
@marioidival no problem, glad you got it working.

I am going to close this now
