### ISSUE TITLE
nerd tree rendering problem while using tmux

### ISSUE THREAD

**Issue by kiranps** [ryanoasis/vim-devicons#91]
I had rendering problems with vim nerd tree while using it with tmux. just like in this post http://stackoverflow.com/questions/22715071/vim-and-tmux-rendering-error

so i had to add a line in .tmux.conf to fix it

    set-window-option -g utf8 on

My current problem is, to make vim-dev icons works i had to remove the previous configuration from .tmux.conf. as remove the configuration redering problem comes back

every thing works perfect without tmux. i use ubuntu and xterm

**Comment by ryanoasis** [comment]
Hmm I will have to look into this and test more to get back to you. Sorry

**Comment by kiranps** [comment]
@ryanoasis which os do you use

**Comment by ryanoasis** [comment]
@kiranps I use Linux mostly. Have done some basic testing on Windows.

Which screenshot are you referring to?

I tried to take screenshots of most of the terminals I tested (Gnome, Urxvt). Most of the main screenshots you see are Xfce terminal.

The font I use most is probably the Droid Sans patched or the Literation (Liberation) patched one.

Btw, I tested a tmux session in xterm and I do not see any particular issues
I have a similar line in my `.tmux.conf`:
`set -g status-utf8 on`

Can you paste a screenshot?

**Comment by kiranps** [comment]
@ryanoasis please add 

    set-window-option -g utf8 on

to your tmux.conf and check whether vim dev-icons are working

**Comment by kiranps** [comment]
![tmux](https://cloud.githubusercontent.com/assets/3966804/9222924/5041515a-4113-11e5-9ee3-5e088800c7d1.png)

when open and close my nerdtree some part on the separator of the nerd tree remains in the window. also first line has some problems. some times first line merges with the airline plugin, this is caused due to the removal of `set-window-option -g utf8 on` from tmux.conf

**Comment by kiranps** [comment]
I found a solution to this. To get full support of unicode in tmux. open it like this

    tmux -u

**Comment by ryanoasis** [comment]
@kiranps great! I will try to add some more details to the readme :+1:
