### ISSUE TITLE
Getting Errors on Vim startup

### ISSUE THREAD

**Issue by SteveGZr** [ryanoasis/vim-devicons#92]
I'm getting the following Errors when I start Vim:

![2015-08-04-121105_1670x1024_scrot](https://cloud.githubusercontent.com/assets/12197139/9058558/4e624622-3aa2-11e5-8149-367598230481.png)

**Comment by ryanoasis** [comment]
@SteveGZr can you paste the order of the plugins you are loading?

**Comment by ryanoasis** [comment]
It looks like devicons and/or airline might be older versions.

Reference: #23 #24 #25

**Comment by SteveGZr** [comment]
I am using Pathogen for installing of Plugins, so I have no specific order of loading the plugins.

**Comment by SteveGZr** [comment]
Is fixed.. Just forgot to pull in the airline directory.. Sorry for stealing your time.. Shame on me :/

**Comment by ryanoasis** [comment]
@SteveGZr glad you figured it out :+1:

Don't worry it wasn't that much time :smile:
