### ISSUE TITLE
Support for vim-startify

### ISSUE THREAD

**Issue by michaelmrose** [ryanoasis/vim-devicons#94]
Support for vim-startify would be nice please see https://github.com/mhinz/vim-startify

**Comment by ryanoasis** [comment]
I have seen that plugin before and its a good idea. I haven't used it but hopefully wouldn't be too bad to implement.

And by support you mean to add icons for the filenames that startify lists?

**Comment by michaelmrose** [comment]
yes precisely thank you

**Comment by ryanoasis** [comment]
@michaelmrose,

**PR** has been submitted :smile:, you can follow progress: mhinz/vim-startify#177

Looks like it will be a while before/if it gets merged in however so I am going to go ahead with **v0.6.0** milestone *without* this support

**Comment by ryanoasis** [comment]
This should be ready to go but not sure when it'll get merged. I will just keep attaching this to the latest milestone until it gets merged in the vim-startify repo

**Comment by ryanoasis** [comment]
This is done: https://github.com/mhinz/vim-startify/commit/c193556225af93405cc87518781d48cf932efc2f

I will just add info to the readme that support is working in [v0.7.0](https://github.com/ryanoasis/vim-devicons/milestones/v0.7.0)
