### ISSUE TITLE
Can't seem to get icons in airlines tab or buffer line

### ISSUE THREAD

**Issue by michaelmrose** [ryanoasis/vim-devicons#95]
Icons show up in airlines statusline and in ctrlp
I have  let g:webdevicons_enable_airline_tabline = 1
I use pathogen so I can't explicity define loading order easily so I had to place your main file in ~/.vim/after/plugin

Tried leaving the autoload dir where it was underneath bundle to let pathogen load it, putting the whole thing under after/autoload and placing it in airlines own extension dir however now that I think of it that shouldn't work because your main file is in after.

Is the reasonable solution using something other than pathogen?

**Comment by ryanoasis** [comment]
Honestly I haven't tested with pathogen but definitely I will try to take a look. Sorry! :worried:

**Comment by ryanoasis** [comment]
I am assuming this is still an issue?
I will test out pathogen when I have time

**Comment by ryanoasis** [comment]
@michaelmrose is this still an issue for you?

**Comment by ryanoasis** [comment]
@michaelmrose It has been a while :stuck_out_tongue: I am going to close this. Please re-open if you still have the issue. Thanks!
